### ISSUE TITLE
Web visualize does not works

### ISSUE THREAD

**Issue by tvildo** [cayleygraph/cayley#111]
sigmajs throws exception :  "The node must have a string id"

![capture](https://cloud.githubusercontent.com/assets/8401382/3865755/3fc31bfc-1fa8-11e4-8e67-8b173795dd93.PNG)

**Comment by iostat** [comment]
For anyone who ends up on this issue and @barakmich's response wasn't entirely clear, the points actually HAVE to be tagged "source" and "target", not just have a label.

That was a few hours of head scratching!
