### ISSUE TITLE
mongo empty result

### ISSUE THREAD

**Issue by changeYi** [cayleygraph/cayley#130]
whatever query, cayley return empty result for me.

eg:
(1) g.V("Humphrey Bogart").All()
return 
{"result": [ { "id": ""  } ]}

(2) g.V().GetLimit(2)
{ "result": [
  {  "id": "" },
  { "id": "" }
 ]}

this is my command
1, cayley_0.3.1_linux_amd64
2, config to mongodb
3, load data like : ./cayley load --config=cayley.cfg --triples=30kmoviedata.nq.gz
4, found 471705 document in mongo

**Comment by dennwc** [comment]
Should be fixed with new versions of Mongo+Cayley
