### ISSUE TITLE
Tagging with properties works only for 1st record in result set

### ISSUE THREAD

**Issue by digal** [cayleygraph/cayley#14]
I'm playing with sample movies db and trying to use the name of start node as tag, but something goes wrong:

Here's my script:

```
var filmToActor = g.Morphism().Out("/film/film/starring").Out("/film/performance/actor")  
g.V().Has("name", "Casablanca").Save("name", "source").Follow(filmToActor).Tag("target").All()
```
 
And here's the output. Only the first record gets the correct "source" value, and others are somehow getting "/film/film":

``` 
{
 "result": [
  {
   "id": ":/en/humphrey_bogart",
   "source": "Casablanca",
   "target": ":/en/humphrey_bogart"
  },
  {
   "id": ":/en/ingrid_bergman",
   "source": "/film/film",
   "target": ":/en/ingrid_bergman"
  },
  {
   "id": ":/en/paul_henreid",
   "source": "/film/film",
   "target": ":/en/paul_henreid"
  },
  ...
 ]
}
```

I tried to replace `.Save("name", "source")` with `.Out("name").Tag("source")` and than getting `.Back`, but got the same result.

**Comment by dennwc** [comment]
Assuming it was fixed
