### ISSUE TITLE
BoltDB Backend always resolves Quad(result) to an empty Quad.

### ISSUE THREAD

**Issue by grahamcummins-wf** [cayleygraph/cayley#156]
In graph/bolt/quadstore.go, in (qs *QuadStore) Quad(k graph.Value) quad.Quad, the return value q is declared as a quad.Quad. A subsequent call gets data with

data = b.Get(qs.createDeltaKeyFor(in.History[len(in.History)-1]))

and then calls:

return json.Unmarshal(data, &q)

The structure returned by b.Get in my test cases looks like it is actually a graph.Delta, not a quad.Quad. The unmarshal call succeeds, but it doesn't find any of the fields of Quad. Instead it finds ID, Quad, Action, etc. The result is the that pointer to q is unmodified, and q is returned with 0 values (empty strings) in all fields. No errors are triggered. 

Changing the declaration of q to graph.Delta and the final return of the function to return q.Quad seems to resolve the issue for me.

**Comment by dennwc** [comment]
Should be fixed in #378
