### ISSUE TITLE
improve error handling and propagation

### ISSUE THREAD

**Issue by kortschak** [cayleygraph/cayley#157]
At the moment cayley does not return errors in many failable cases. This has arisen because new back ends have been added that have failable cases that did not exist in the original stores. Also it is partly historical.

This set of changes may require alterations to the Iterator and QuadStore interfaces.

**Comment by iddan** [comment]
@dennwc is this still relevant?

**Comment by dennwc** [comment]
It should be solved by a recent iterator refactoring. Closing.
