### ISSUE TITLE
Querying empty bolt database causes crash

### ISSUE THREAD

**Issue by benlivingood-wf** [cayleygraph/cayley#163]
If i query a fresh instance of cayley with something like 'g.V("d").Out().All()' the cayley instance panics and server dies.

I0923 12:06:38.366985 41895 http.go:76] Started POST /api/v1/query/gremlin for 127.0.0.1:49740
panic: runtime error: slice bounds out of range [recovered]
        panic: runtime error: slice bounds out of range [recovered]
        panic: runtime error: slice bounds out of range

**Comment by payneio** [comment]
It seems like this is fixed, but the issue hasn't been closed?
