### ISSUE TITLE
Improve result serialisation approach in query sessions

### ISSUE THREAD

**Issue by kortschak** [cayleygraph/cayley#168]
At the moment serialisation appears more complicated to potential client code than it should. Ideally we want to see something that works not unlike json.Marshal where a map[string]interface{} or a json tagged struct can be handed in to a MarshalResult method of the session and be filled. This should be able to happen without prior preparation of the results. ClearJSON would be renamed Reset.

**Comment by robertmeta** [comment]
Moved to the feature request part of the forum: https://discourse.cayley.io/t/improve-result-serialisation-approach-in-query-sessions/234
