### ISSUE TITLE
storage concerns of UUID and attribute naming

### ISSUE THREAD

**Issue by guidopatanella** [cayleygraph/cayley#170]
Observing the stored data by Cayley I have made the following observations

<b>1) IDENTIFIERS: </b> the node identifiers are stored as <b>40</b> character hashes hexadecimal string representations. UUID standard is just <b>32</b> characters long and already ensures lifetime uniqueness. Since the QUADs are stored combining various identifiers together, these extra 8 characters multiples to consume even more storage. Overall, resizing the identifiers from 40 to 32 would create a considerable size improvement. Secondly, if UUID standard is not a required deal since ids are stored as strings and not binary, Cayley could opt to use normal <b>mixed-case alphanumeric</b> representations, therefore a 20 string representation would exceed the alphanumeric's 30 cardinality. In short, representing 20 characters as "X5yEr3Z32f9B.." will over exceed the all needs for identifier uniqueness, allowing to halve the storage needs of all references and identifiers. This has also a benefit on performance, since the matching will be more compact.

<b>2) PROPERTIES: </b> The QUAD Properties are currently stored as <b>"subject", "predicate", "object", "label"</b>. Since this is stored on document databases ( MongoDB ) as a JSON document and repeated for every node, this consumes excessive data through the stores. Renaming these properties to <b>"S", "P", "O", "L"</b>  will save 23 bytes per stored node.

**Comment by dennwc** [comment]
Partially addressed in #378

**Comment by dennwc** [comment]
I consider this fixed, since #378 stores everything in a more compact way (binary data).
