### ISSUE TITLE
Cognitive dissonance in command-line and configuration-file flags

### ISSUE THREAD

**Issue by saidimu** [cayleygraph/cayley#172]
The expectation is that command-line and configuration-file flags will be identical, with perhaps an extra
`--` added by convention to command line flags.

In Cayley however we have this:
- `--db` vs `database`
- `--dbpath` vs `db_path`
- `--host` vs `listen_host` (this one bit me hard.)

Is there a particular reason for this?

**Comment by dennwc** [comment]
Fixed in https://github.com/cayleygraph/cayley/pull/492
