### ISSUE TITLE
SpiderMonkey VM instead of Otto VM?

### ISSUE THREAD

**Issue by igormarfin** [cayleygraph/cayley#173]
I'd like to propose to use multithreaded VM in gremlin queries. 
Is it possible to replace otto VM by SpiderMonkey VM
https://github.com/idada/monkey
without a big restructuring  the code?

At least it would be good enough to add a dynamical  altering (uploading user-defined js functions, libraries etc, when all bindings of gremlin query objects has been finished) of the otto runtime.
Otto allows this feature.

**Comment by robertmeta** [comment]
Moved to feature request section of the forum: https://discourse.cayley.io/t/spidermonkey-vm-instead-of-otto-vm/199
