### ISSUE TITLE
http.ResponseWriter and gzipResponseWrite in ServeV1Query?

### ISSUE THREAD

**Issue by igormarfin** [cayleygraph/cayley#175]
I'd like to ask to add the support for gzipResponseWrite for on-fly gzipping the output json.
In some situations, this helps to decrease the time needed to upload the output payload (json) to  a client (a database via apache, a browser via apace or a simple js in /static/ folder of the cayley).

I have notice  that the latency time (time needed to deliver the response back, I have tested  libcurl  ) may be twice larger than  the cayley query time  even for small jsons (~100 elements and each of ~ 100 bytes).

Here is a few examples of an optimization of http traffic:
http://www.phpied.com/reducing-tpayload/
http://zoompf.com/blog/2012/02/lose-the-wait-http-compression
and the gzipping plays the important role.

Because I transfer quite big JSONs (about 100K  elements) back,  I propose to introduce  GzipServeV1Query utilizing  gzipResponseWrite. Example  of  the  gzipResponseWrite  can be found here
https://groups.google.com/forum/#!topic/golang-nuts/eVnTcMwNVjM
and here
https://github.com/SlyMarbo/web

Cheers,
Igor.

**Comment by robertmeta** [comment]
Good idea, moved to feature request forum: https://discourse.cayley.io/t/http-responsewriter-and-gzipresponsewrite-in-servev1query/240
