### ISSUE TITLE
a couple of  questions on sexp query language

### ISSUE THREAD

**Issue by igormarfin** [cayleygraph/cayley#177]
I'm thinking  on possible way of tuning the cayley query language. As perhaps you read my previous issues, I proposed the working solution how one can  upload the user-defined libraries to the otto vm used in gremlin queries.  After a few months of playing (as a user) with cayley, I  understood that a few features in the gremlin are absent. One of them is regex patterns in .Has(), .Is() etc functions.
I'm using regex pattern on the level of Otto VM to find nodes, but it is too slow (because it iterates on all vertices). So, why not to have this support at the go-level:
For example , it would be nice to have something  g.V().Has(".*cool$","^[p,m]a[p,m]a.*").All() in the gremlin.

Spending a few hours to browse the cayley's code, I have found the patterns are not possible in the gremlin because of  the "FixedIterator",  with its "Identity" function as a comparator, used here. 

But then I have found "OptionalIterator" and sexp language which seems might support the regex patterns. So I have basically two questions:

1) Why did you not implement a support for sexp in http/query.go? 
2) Is it possible to use sexp with  backends  different from "memstore",  I mean leveldb, mongodb etc?

**Comment by nii236** [comment]
Has there been progress with regex support for cayley db? I'm in the process of loading a cayley db with a Japanese-English dictionary and it would be handy to be able to lookup partial matches especially since Japanese compounds can vary often (but have the same root kanji).

**Comment by robertmeta** [comment]
@dennwc what does needs approval mean in this case?

**Comment by dennwc** [comment]
Meaning that @barakmich should take a look. It looks resolved for me.
