### ISSUE TITLE
App Engine Datastore backend.

### ISSUE THREAD

**Issue by panamafrancis** [cayleygraph/cayley#178]
I'm of the opinion that an appengine datastore backend would be useful to some people myself included.

I've had the chance to read over the code and hack away at this problem and thus far i've only come across one blocking issue, that of google appengine sdk using go 1.2 where as cayley is using go 1.3 packages, however there's some talk of appengine being updated to 1.3 in the coming weeks re: this thread here:
https://groups.google.com/forum/#!topic/google-appengine-go/fUNE3jpYFeU
In the meantime i can temporarily revert commits related to Go 1.3

I'd like to implement this myself, but i'm aware there might be other people also working on this, if so let me know!

plus any guidance would be grand!

S

**Comment by dennwc** [comment]
Merged. Closing now.
