### ISSUE TITLE
Delete quad API  causes panic in leveldb

### ISSUE THREAD

**Issue by igormarfin** [cayleygraph/cayley#181]
It seems that there are some critical problems  with " ... iterator isn't skipping quad from the log ..." described here https://github.com/google/cayley/issues/164

You can find details on the issue in this git
https://gist.github.com/igormarfin/21655596ab0b40adae96

**Comment by dennwc** [comment]
Should be fixed in HEAD. Feel free to reopen if you still have this problem.
