### ISSUE TITLE
Enable Sourcegraph

### ISSUE THREAD

**Issue by jseely** [cayleygraph/cayley#183]
I want to use [Sourcegraph code search and code review](https://sourcegraph.com) with cayley. A project maintainer needs to enable it to set up a webhook so the code is up-to-date there.

Could you please enable cayley on @Sourcegraph by going to https://sourcegraph.com/github.com/google/cayley and clicking on Settings? (It should only take 15 seconds.)

Thank you!

**Comment by mtunique** [comment]
+1

**Comment by amirouche** [comment]
it works :)

**Comment by dennwc** [comment]
Sorcegraph works, closing. Feel free to reopen if there is any issues with it.
