### ISSUE TITLE
Primary Keys : Refactoring sequential keys & new UUID based keys

### ISSUE THREAD

**Issue by panamafrancis** [cayleygraph/cayley#185]
Currently ID generation is only suitable for running a single instance of cayley. 

There are a few issues with using a continuous series for ID's, better outlined here: 
http://blog.codinghorror.com/primary-keys-ids-versus-guids/

Given there is a lot of existing code using sequential id's, i don't propose refactoring all backends to use UUID's that would be cumbersome and given the use case for most backends not needed.

So i propose refactoring the IDs to accommodate both UUID's and sequential IDs.

**Comment by dennwc** [comment]
Merged
