### ISSUE TITLE
Redis backend

### ISSUE THREAD

**Issue by varadharajan** [cayleygraph/cayley#193]
As most of us are aware, redis is just another K-V store. I was wondering if adding a redis backend to cayley would help people to make use of their already existing K-V infrastructure. I've already started working on it and will send a PR soon. I'm interested in knowing if there are concerns around this (as an idea).

**Comment by proteneer** [comment]
Most people use redis as a in-memory cache layer. In this case, the size of the graph is essentially limited by the size of available memory. In addition, Redis's AOF/BGSAVE method of persistence is shakey at best. So I'm not sure what the value proposition is.

**Comment by keremgocen** [comment]
Can you expand "shakey" please? While i have not experienced myself i
recently heard Josiah Carlson on SE radio episode 209 about redis and they
were quite satisfied with the persistence options although thats not the
main focus for redis.

**Comment by proteneer** [comment]
AOFs with anything other than fsync at every query is generally not considered reliable enough for anything mission critical. I wouldn't trust using Redis to do AOF saves every second (the default policy).  And If you're saving on every query, then you might as well as just use a DB where you're not limited by memory space. 

Related: Redis also doesn't have any "easy" transactional guarantees so if your AOF dies in between an all-or-nothing set of queries, you've got to deal with corruption. Yes, hacking LUA/abusing pipelines are good alternatives, but they are not the most fun things to work with.

**Comment by varadharajan** [comment]
@proteneer  I was wondering, Doesn't most of the mainstream NoSQL (like Mongo, Rethink) stores make use of BGSAVE? I was under the impression that it was the triumph card that makes them faster, as they tradeoff durability for performance.

**Comment by GrayTShirt** [comment]
Wouldn't Redis be useful to cache a computationally expensive graph traversal and invalidate if edges that are updated in the traversal are added/deleted?

**Comment by iddan** [comment]
Another approach to this will be making use of [Redis Graph](https://oss.redislabs.com/redisgraph/)

**Comment by iddan** [comment]
Backend support was moved to a [separate project](https://github.com/hidal-go/hidalgo).

**Comment by iddan** [comment]
This issue is now tracked [here](https://github.com/hidal-go/hidalgo/issues/1)
