### ISSUE TITLE
"cayley http --dbpath=30kmoviedata.nq.gz" run on Windows failed

### ISSUE THREAD

**Issue by liudonghua123** [cayleygraph/cayley#197]
When I run "cayley http --dbpath=30kmoviedata.nq.gz" on my Windows(8.1 x64), whether start from common cmd or administrator cmd, it give me the same error as belows ("cayley repl --dbpath=30kmoviedata.nq.gz" no problem)

D:\Program_Files\cayley_0.4.0_windows_amd64>cayley repl --dbpath=30kmoviedata.nq.gz
creating new history file: ".cayley_history"
cayley>
D:\Program_Files\cayley_0.4.0_windows_amd64>
D:\Program_Files\cayley_0.4.0_windows_amd64>cayley http --dbpath=30kmoviedata.nq.gz
Cayley now listening on 127.0.0.1:64210
F0107 16:30:03.649552 13808 http.go:150] ListenAndServe: listen tcp 127.0.0.1:64210: bind: An attempt was made to access a socket in a way forbidden by its access permissions.
goroutine 16 [running]:
github.com/barakmich/glog.stacks(0xc082035d00, 0x0, 0x0, 0x0)
        /home/barak/src/cayley/src/github.com/barakmich/glog/glog.go:810 +0xd3
github.com/barakmich/glog.(*loggingT).output(0xfda9a0, 0xc000000003, 0xc08200c0c0)
        /home/barak/src/cayley/src/github.com/barakmich/glog/glog.go:761 +0x47b
github.com/barakmich/glog.(*loggingT).print(0xfda9a0, 0x3, 0xc082055ce8, 0x2, 0x2)
        /home/barak/src/cayley/src/github.com/barakmich/glog/glog.go:686 +0x169
github.com/barakmich/glog.Fatal(0xc082055ce8, 0x2, 0x2)
        /home/barak/src/cayley/src/github.com/barakmich/glog/glog.go:1103 +0x57
github.com/google/cayley/http.Serve(0xc082005380, 0xc08204c000)
        /home/barak/src/cayley/src/github.com/google/cayley/http/http.go:150 +0x44e
main.main()
        /home/barak/src/cayley/src/github.com/google/cayley/cayley.go:245 +0x967

D:\Program_Files\cayley_0.4.0_windows_amd64>
D:\Program_Files\cayley_0.4.0_windows_amd64>

Even I built from source and then run show me the similary error like the following

C:\Users\Liu.D.H\go\bin>cayley http --dbpath=30kmoviedata.nq.gz
Cayley now listening on 127.0.0.1:64210
F0107 16:28:28.542981 13596 http.go:145] ListenAndServe: listen tcp 127.0.0.1:64210: bind: An attempt was made to access a socket in a way forbidden by its access permissions.
goroutine 1 [running]:
github.com/barakmich/glog.stacks(0xc08202bb00, 0x0, 0x0, 0x0)
        C:/Users/Liu.D.H/go/src/github.com/barakmich/glog/glog.go:810 +0xd4
github.com/barakmich/glog.(*loggingT).output(0xff7d80, 0xc000000003, 0xc08200a0c0)
        C:/Users/Liu.D.H/go/src/github.com/barakmich/glog/glog.go:761 +0x48c
github.com/barakmich/glog.(*loggingT).print(0xff7d80, 0xc000000003, 0xc0863f9d50, 0x2, 0x2)
        C:/Users/Liu.D.H/go/src/github.com/barakmich/glog/glog.go:686 +0x183
github.com/barakmich/glog.Fatal(0xc0863f9d50, 0x2, 0x2)
        C:/Users/Liu.D.H/go/src/github.com/barakmich/glog/glog.go:1103 +0x57
github.com/google/cayley/http.Serve(0xc082002b00, 0xc08205c280)
        C:/Users/Liu.D.H/go/src/github.com/google/cayley/http/http.go:145 +0x591
main.main()
        C:/Users/Liu.D.H/go/src/github.com/google/cayley/cayley.go:245 +0xb10

C:\Users\Liu.D.H\go\bin>

**Comment by david-schor** [comment]
That error message vaguely indicates the sock was blocked/denied (or in use). Do you have a firewall or an antivirus running that's possibly blocking it?

**Comment by liudonghua123** [comment]
When I tried again, it worked without that problem.
ds's answser is correct. Maybe it is because my firewall or antivirus issue.
Thanks!
