### ISSUE TITLE
Case insensitive queries

### ISSUE THREAD

**Issue by ecesena** [cayleygraph/cayley#200]
I'm playing with Cayley and Freebase and one of the biggest "ux" issues is the lack of a case insensitive queries in Cayley. 

I was wondering if this is a feature you could see added to Cayley (maybe via a case insensitive iterator?), or if there is any specific design/implementation choice that goes against it. 

(I've read the guidelines and TODO, I didn't find anything related, sorry if I missed something.)

**Comment by robertmeta** [comment]
Great feature request -- moved to our feature request forum: https://discourse.cayley.io/t/case-insensitive-queries/231
