### ISSUE TITLE
Vendoring?

### ISSUE THREAD

**Issue by barakmich** [cayleygraph/cayley#211]
I've been seriously considering vendoring dependencies. 

I hate to, I really do. I like that the Go default is to pull the latest and greatest and break as necessary.

But it'd also be great (esp. re #64 and #208) to be able to have a stable Cayley dependency. Right now, we can't build the old versions, and the binaries are all that's left.

So what to do?

`gopkg.in` seems alright for users of Cayley. I like it. Godep is a pain and a half, but the current best way of going about things.

I'd also love an option which allows vendoring without full Godep pain, but I'm unfamiliar of the landscape beyond that.

Open to thoughts!

**Comment by proteneer** [comment]
Thoughts on gom?

https://github.com/mattn/gom

Though this does require the end-user to have gom installed as well. Not sure if this is too onerous.

**Comment by barakmich** [comment]
@proteneer Yeah, then it wouldn't be `go get`-able because it would require gom. 

A middle ground (use gom for management and then rewrite the imports to use `_vendor` path, a la godep) may be possible. This would mean only needing gom for updating the packages. 

That's not the worst idea I've ever heard; one of the things I hate most about Godep is trying to update or add individual packages.

**Comment by abourget** [comment]
git subtree and GO15VENDOREXPERIMENT .. this way, you depend on no tool at all, and you can manage how you update dependencies with one or two git commands.. that,s what I do.. I ditched all the 3rd-party tools for just those two things.

**Comment by jzelinskie** [comment]
This issue is a bit old these days. Cayley already uses Godep, but only checks in the JSON manifest, so you can "godep restore" to get all the dependencies in your GOPATH at the correct versions. We made this tradeoff because we _didn't_ want to include all dependencies code in the cayley repository. I don't think we've had a dialog since Go 1.5's vendor support was added.

**Comment by robertmeta** [comment]
We picked a vendoring solution, and while it might be updated soon, I think we can consider this closed.
