### ISSUE TITLE
Live Queries

### ISSUE THREAD

**Issue by ncammarata** [cayleygraph/cayley#213]
I haven't used Cayley much but I've used Neo4j extensively and love using graph databases. I'm building a new programming language that compiles to JS that allows you to bind templates to database queries using http://rethinkdb.com/blog/1.16-release/. I think efficient live querying is a fantastic new data access model that could fit really well with a graph database like Cayley. 

Would love to hear some thoughts about potentially supporting this. If GH issues is not the correct place to post this please let me know and I'll delete it and start a discussion in another place.

**Comment by barakmich** [comment]
(GH issues is fine, btw) 

I think I understand what you're getting at, but it's not what I'd call a *new* data access model. Triggers have existed in databases for quite a long time; yes, maybe not as web triggers or live queries or whatever, but as a general notion, update-a-query-(or-view)-on-write is fairly well-known.

So then, as it applies to graphs. You're right, it is an access model that is actually really cool; I've seen prototypes in this general direction on graphs before. (A public example of which in the old days was [mwdeathbot](https://twitter.com/mwdeathbot) -- triggered on /people/person/deceased_person type triples)

It's a thing I'd love to support in Cayley. 

The question then comes on how to get there. There are a couple steps:
* Add support for replication -- for three reasons:
   1. This tends to be more server-taxing, so replicas are a good thing.
   2. It will probably force the abstraction of AddDelta() into its own interface. 
   3. You now have a separate replica stream (update stream -- you can see the connection).
* Write a "triple responder" store. 
    * This need not be a pluggable store; total storage is minimal, possibly even ephemeral.
    * This would be aided by cursors/iterator-serialization, but is not required for v0.
    * This could be prototyped with (and benefit from) Cayley-as-a-library (#64, #208), as a separate binary which reads the replication stream and updates all listening queries.
    * The API for which is also interesting, when it comes to accepting queries. Sure, they need to be valid Cayley queries, but you might also want server limits on how complicated of a query, etc.

This is a really interesting bit of code with a bit of a difficulty factor. You have to be able to take an iterator tree, find which quads it could possibly respond to ((*,*,*,*) at worst) and the points in the query that those correspond to, and on event, rewrite the iterator tree with the new information (likely:u sing  and iterators and fixed iterators) and rerun the (now simpler) query. The back-of-envelope upper bound on response time per write is the time it took to run the initial query, often much better.

But it's nicely separable, in the sense that, again, it could just be a binary listening on the replica stream. This binary, incidentally, can also become the basis of a graph cache as it gets more intricate. 

 * Once that gets working, combine all the code, and add the appropriate HTTP endpoint directly into Cayley. (You'll notice the "event" I mentioned is once again the AddDelta() interface, exposed through the replica stream)

That's my rough sketch anyway. I'm thinking of taking a run at replication in the next few days.

I'd **love** the help if you've got some spare cycles. It's also nice in that the bulk can be written in a more-or-less brand-new-module/directory way. As you can tell, I've thought a lot about this, so I'm totally up for being literally on-call for questions if you're free.

**Comment by ncammarata** [comment]
Wow, thanks for such a detailed answer. Unfortunately, right now I don't have any spare cycles, as NoSql dbs are in higher demand so we have to focus on that now(even though I'm more excited by graph dbs). If we end up hiring more devs though, this would be something we'd love to try to contribute to. Regardless, I'll definitely stay in the loop and see how it progresses.

**Comment by robertmeta** [comment]
This is an awesome discussion, but hasn't yet yielded specific implementations -- so moving it over to feature requests: https://discourse.cayley.io/t/live-queries/230
