### ISSUE TITLE
Fix g.Emit([]) on the REPL

### ISSUE THREAD

**Issue by barakmich** [cayleygraph/cayley#220]

**Comment by paritosh-gupta** [comment]
I think this can be closed. I am getting the output as 

<pre> cayley> g.Emit([])

=> &ltnil&gt
-----------
1 Results
Elapsed time: 0.404136 ms
</pre>

which seems correct?

**Comment by robertmeta** [comment]
I honestly am not 100% sure what the right behavior is here.  @barakmich -- this good to close?
