### ISSUE TITLE
New log package

### ISSUE THREAD

**Issue by barakmich** [cayleygraph/cayley#221]
Probably need one. glog is great and all, but if one can also use Cayley as a library, it'd be nice to separate the global logger out into a more composable one.

Open to suggestions. There are way too many logging packages out there.

**Comment by kortschak** [comment]
There are a number of events (all errors) that currently get logged in the function where they occur, but which should be logged at the caller in the application (in the first instance cayley). This depends on fixing the error handling, which I haven't had time to work on yet.

As far as logging the rest of things, I think having a logger that is semantically aware would make sense here - we define an interface that knows about the various actions that cayley's internals make and then users can provide implementations that convert these events to human readable log form for the interface if they want logging.
