### ISSUE TITLE
Cayley appears to drop quads on loads when duplicate rows exist

### ISSUE THREAD

**Issue by buley** [cayleygraph/cayley#223]
In the tests below, which simplifies to a `.nq` with just few rows, the "Alice" vertex will disappear depending on the load order of the items. This is using the "cquad" format on 0.4.0.

A `sort | uniq` on the command line may be a workaround.

---

**expected behavior** `testcase1.nq`:

      "Bob" "knows" "A" .   
      "Alice" "knows" "B" .
      "Bob" "knows" "A" .

`g.Emit(g.V("Bob").All())`

      {
       "result": [
        {
         "id": "Bob"
        },
        "null"
       ]
      }

`g.Emit(g.V("Alice").All())`

      {
       "result": [
        {
         "id": "Alice"
        },
        "null"
       ]
      }

**buggy behavior** `testcase2.nq`:

      "Bob" "knows" "A" .   
      "Bob" "knows" "A" .
      "Alice" "knows" "B" .

`g.Emit(g.V("Bob").All())`

      {
       "result": [
        {
         "id": "Bob"
        },
        "null"
       ]
      }

`g.Emit(g.V("Alice").All())`

      {
       "result": [
        {
         "id": ""
        },
        "null"
       ]
      }

**expected behavior** `testcase3.nq`:
      
      "Alice" "knows" "B" .
      "Bob" "knows" "A" .
      "Bob" "knows" "A" .
      "Alice" "knows" "B" .

`g.Emit(g.V("Bob").All())`

      {
       "result": [
        {
         "id": "Bob"
        },
        "null"
       ]
      }

`g.Emit(g.V("Alice").All())`

      {
       "result": [
        {
         "id": "Alice"
        },
        "null"
       ]
      }

**Comment by barakmich** [comment]
Probably a good catch, and I can repro on v0.4.0. I think you're running off of the binary distro? There's been some helpful changes around duplicate quads (including explicit ignoring thereof) on HEAD.

So I think the real issue here is I need to release a 0.4.1 soon. There are enough minor bugs to warrant it.

**Comment by buley** [comment]
I'm on a binary and will checkout HEAD. Thank you. :+1:

**Comment by dennwc** [comment]
Resolved on HEAD. Closing.
