### ISSUE TITLE
Indexing Morphisms

### ISSUE THREAD

**Issue by paultag** [cayleygraph/cayley#228]
Heyya!

It'd be really neat to set Cayley up to index on a Morphism, so that expensive queries can be done while loading, rather than taking that hit every time a query is done.

I know this is a massive feature request and quite nebulous, but I figure I'll put it on the issue tracker.

**Comment by robertmeta** [comment]
We can continue this discussion on the feature request forum: https://discourse.cayley.io/t/indexing-morphisms/232
