### ISSUE TITLE
Morphism composition

### ISSUE THREAD

**Issue by jakedt** [cayleygraph/cayley#232]
I would like to be able to fork and join a path through a graph in interesting and exciting ways. As I understand it, this would be a graph shape query.

I think a way to accomplish this might be to use a union or intersection on an unbound morphism. Example:

```
var morphismA = g.Morphism().Out(oneintermediate).Out(destination)
var morphismB = g.Morphism().Out(anotherintermediate).Out(destination)
var combined = morphismB.Union(morphismA)
g.V().Has(type, startingpoint).Follow(combined).Has(athing, onlyondestinations).All()
```

**Comment by dennwc** [comment]
I think it can be done now by either Follow or And. @barakmich what do you think?
