### ISSUE TITLE
Add a Count function to query language

### ISSUE THREAD

**Issue by theRanalyst** [cayleygraph/cayley#240]
There should be a way to query the graph to see how many nodes exist without printing all of the values. This can currently be achieved with _size(g.V( ).ToArray( )), but it should be implement in cayley as something like g.V( ).count( ), but the count function should be applicable to any type of call. For example, calling g.V( ).Tag("source").Out("follows").count( ) on the testdata.nq graph should return the number of people each person follows.

**Comment by Quentin-M** [comment]
+1
I am interested in counting the number of nodes without loading all the data in memory (it may be big)

**Comment by omeid** [comment]
:+1: I would very much like this feature too.

**Comment by mindeavor** [comment]
:+1:

**Comment by semblano** [comment]
:+1:

**Comment by jcmartins** [comment]
:+1:

**Comment by robertmeta** [comment]
Moved to feature requests on the forum: https://discourse.cayley.io/t/add-a-count-function-to-query-language/244

**Comment by dennwc** [comment]
Implemented as `g.V().Count()` in v0.6
