### ISSUE TITLE
Handy functions in Go API

### ISSUE THREAD

**Issue by Quentin-M** [cayleygraph/cayley#266]
With PR #265, it becomes easy to open a database in Go. I think that Cayley has a brilliant future working as Go Library but while most of the queries are easily doable - in my opinion, some functions are missing.

More specifically, I am thinking about these functions:
* Save
* Back
- Has

Could you please implement these functions and/or every other functions you think about which would be really handy ? JS Gremlin-like API makes Cayley awesome and easy-to-use, but that is not yet the case in Go. I believe that it would not take too much time doing these improvements but will improve a lot Cayley.

A shortcut for `handle.NameOf(iterator.Result())` and a `ToValue(path *path.Path)` shortcut (basically doing `path.BuildIterator()`, `cayley.RawNext(iterator)` and `return handle.NameOf(iterator.Result())`) would be helpful too I believe.

Finally, I think that the imports.go is a bit messy but it might just be because I don't have too much experience in Golang. What is the point of having the following things in it ?

```
type Iterator graph.Iterator
type QuadStore graph.QuadStore
type QuadWriter graph.QuadWriter

type Path path.Path

var StartMorphism = path.StartMorphism
var StartPath = path.StartPath

var RawNext = graph.Next
```

```
func Quad(subject, predicate, object, label string) quad.Quad {
	return quad.Quad{subject, predicate, object, label}
}
```

(#208 Go Api)

Thank you a lot.

**Comment by dennwc** [comment]
Merged to master, closing.
