### ISSUE TITLE
Reason for different visualisation frameworks

### ISSUE THREAD

**Issue by nii236** [cayleygraph/cayley#272]
Is there a reason why the "Query Shapes" feature use D3.js, yet the "Visualize" feature uses Sigma.js?

**Comment by iddan** [comment]
Not really... The new UI will use one of them only.

**Comment by nii236** [comment]
Cool, thanks for the speedy reply! Which one will Cayley use for the new UI?

**Comment by iddan** [comment]
Currently D3, but I haven't checked Sigma yet.

**Comment by iddan** [comment]
Tracked on [Cayley Web](https://github.com/cayleygraph/web)
