### ISSUE TITLE
using mongodb: wrong documentation 

### ISSUE THREAD

**Issue by matteoredaelli** [cayleygraph/cayley#275]
Using cayley with mongo db requires using "mongo" string instead of "mondodb" that is suggested in the official documentation and --help

I use version

  cayley_0.4.1_linux_amd64> ./cayley version

Cayley v0.4.1 built 2015-04-25T19:37-0400

Please update the documentation

Regards
Matteo

**Comment by Quentin-M** [comment]
```host:port
mongodb://host:port```

Both works for me.
