### ISSUE TITLE
CockroachDB backend

### ISSUE THREAD

**Issue by siddhanathan** [cayleygraph/cayley#299]
CockroachDB is a Scalable, Geo-Replicated, Transactional Datastore, written in Go. Details on https://github.com/cockroachdb/cockroach

The project is currently in early development. It uses RocksDB internally (https://github.com/google/cayley/issues/67 might be related). I think it's a viable alternative to Cassandra.

**Comment by espeed** [comment]
+1

**Comment by beauhoyt** [comment]
+1

**Comment by dennwc** [comment]
Initial implementation (as SQL backend): #489

**Comment by dennwc** [comment]
Done
