### ISSUE TITLE
fatal error: runtime: out of memory

### ISSUE THREAD

**Issue by jcmartins** [cayleygraph/cayley#301]
Hi,
I received this message when I did a JSON POST.

Cayley v0.4.1 built 2015-04-25T19:37-0400
Setting GOMAXPROCS to 4

./cayley http --config=cayley.cfg --dbpath=data/30kmoviedata.nq.gz --host=0.0.0.0
Cayley now listening on 0.0.0.0:64210
fatal error: runtime: out of memory

runtime stack:
runtime.SysMap(0xc323040000, 0x79f0000, 0x435300, 0x1022898)
        /home/barak/local/go/src/runtime/mem_linux.c:149 +0x98
runtime.MHeap_SysAlloc(0x1027f80, 0x79f0000, 0x430322)
        /home/barak/local/go/src/runtime/malloc.c:284 +0x124
runtime.MHeap_Alloc(0x1027f80, 0x3cf8, 0x100000000, 0xc20808ed80)
        /home/barak/local/go/src/runtime/mheap.c:240 +0x66

goroutine 124 [running]:
runtime.switchtoM()
        /home/barak/local/go/src/runtime/asm_amd64.s:198 fp=0xc27d2cb3e8 sp=0xc27d2cb3e0
runtime.mallocgc(0x79f0000, 0x0, 0x3, 0x7f4c6f1a1030)
        /home/barak/local/go/src/runtime/malloc.go:199 +0x9f3 fp=0xc27d2cb498 sp=0xc27d2cb3e8
runtime.rawmem(0x79f0000, 0x79f0000)
        /home/barak/local/go/src/runtime/malloc.go:371 +0x39 fp=0xc27d2cb4c0 sp=0xc27d2cb498
runtime.growslice(0x9a3640, 0x0, 0x0, 0x0, 0x79ee465, 0x0, 0x0, 0x0)
        /home/barak/local/go/src/runtime/slice.go:83 +0x237 fp=0xc27d2cb520 sp=0xc27d2cb4c0
fmt.(*fmt).padString(0xc21c9fb648, 0xc31b644000, 0x79ee465)
        /home/barak/local/go/src/fmt/format.go:130 +0x387 fp=0xc27d2cb608 sp=0xc27d2cb520
fmt.(*fmt).fmt_s(0xc21c9fb648, 0xc31b644000, 0x79ee465)
        /home/barak/local/go/src/fmt/format.go:311 +0x68 fp=0xc27d2cb638 sp=0xc27d2cb608
fmt.(*pp).fmtString(0xc21c9fb5f0, 0xc31b644000, 0x79ee465, 0xc300000076)
        /home/barak/local/go/src/fmt/print.go:508 +0x148 fp=0xc27d2cb668 sp=0xc27d2cb638
fmt.(*pp).printArg(0xc21c9fb5f0, 0x9a2ec0, 0xc297959ee0, 0xc200000076, 0x0, 0x100000000)
        /home/barak/local/go/src/fmt/print.go:787 +0xa82 fp=0xc27d2cb738 sp=0xc27d2cb668
fmt.(*pp).doPrint(0xc21c9fb5f0, 0xc27d2cb938, 0x1, 0x1, 0x0)
        /home/barak/local/go/src/fmt/print.go:1218 +0x2ac fp=0xc27d2cb810 sp=0xc27d2cb738
fmt.Fprint(0x7f4c75e47468, 0xc22b5205a0, 0xc27d2cb938, 0x1, 0x1, 0x0, 0x0, 0x0)
        /home/barak/local/go/src/fmt/print.go:222 +0x6e fp=0xc27d2cb858 sp=0xc27d2cb810
github.com/google/cayley/http.(*API).ServeV1Query(0xc22b52ebc0, 0x7f4c75e47408, 0xc22b5205a0, 0xc21d4add40, 0xc2618bb380, 0x1, 0x1, 0x3)
        /home/barak/src/cayley/src/github.com/google/cayley/http/query.go:102 +0x68b fp=0xc27d2cb9b8 sp=0xc27d2cb858
github.com/google/cayley/http.*API.ServeV1Query·fm(0x7f4c75e47408, 0xc22b5205a0, 0xc21d4add40, 0xc2618bb380, 0x1, 0x1, 0xc200000000)
        /home/barak/src/cayley/src/github.com/google/cayley/http/http.go:133 +0x63 fp=0xc27d2cba00 sp=0xc27d2cb9b8
github.com/google/cayley/http.func·001(0x7f4c75e47408, 0xc22b5205a0, 0xc21d4add40, 0xc2618bb380, 0x1, 0x1)
        /home/barak/src/cayley/src/github.com/google/cayley/http/http.go:82 +0x2f3 fp=0xc27d2cbb38 sp=0xc27d2cba00
github.com/julienschmidt/httprouter.(*Router).ServeHTTP(0xc22b41cc00, 0x7f4c75e47408, 0xc22b5205a0, 0xc21d4add40)
        /home/barak/src/cayley/src/github.com/julienschmidt/httprouter/router.go:299 +0x18e fp=0xc27d2cbc58 sp=0xc27d2cbb38
net/http.(*ServeMux).ServeHTTP(0xc20803d740, 0x7f4c75e47408, 0xc22b5205a0, 0xc21d4add40)
        /home/barak/local/go/src/net/http/server.go:1541 +0x17d fp=0xc27d2cbcb0 sp=0xc27d2cbc58
net/http.serverHandler.ServeHTTP(0xc22aa07680, 0x7f4c75e47408, 0xc22b5205a0, 0xc21d4add40)
        /home/barak/local/go/src/net/http/server.go:1703 +0x19a fp=0xc27d2cbd08 sp=0xc27d2cbcb0
net/http.(*conn).serve(0xc22b520460)
        /home/barak/local/go/src/net/http/server.go:1204 +0xb57 fp=0xc27d2cbfd8 sp=0xc27d2cbd08
runtime.goexit()
        /home/barak/local/go/src/runtime/asm_amd64.s:2232 +0x1 fp=0xc27d2cbfe0 sp=0xc27d2cbfd8
created by net/http.(*Server).Serve
        /home/barak/local/go/src/net/http/server.go:1751 +0x35e

goroutine 1 [IO wait]:
net.(*pollDesc).Wait(0xc22b58ed80, 0x72, 0x0, 0x0)
        /home/barak/local/go/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc22b58ed80, 0x0, 0x0)
        /home/barak/local/go/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).accept(0xc22b58ed20, 0x0, 0x7f4c86816e08, 0xc24f692168)
        /home/barak/local/go/src/net/fd_unix.go:419 +0x40b
net.(*TCPListener).AcceptTCP(0xc20803a0e8, 0x47d3be, 0x0, 0x0)
        /home/barak/local/go/src/net/tcpsock_posix.go:234 +0x4e
net/http.tcpKeepAliveListener.Accept(0xc20803a0e8, 0x0, 0x0, 0x0, 0x0)
        /home/barak/local/go/src/net/http/server.go:1976 +0x4c
net/http.(*Server).Serve(0xc22aa07680, 0x7f4c75e47250, 0xc20803a0e8, 0x0, 0x0)
        /home/barak/local/go/src/net/http/server.go:1728 +0x92
net/http.(*Server).ListenAndServe(0xc22aa07680, 0x0, 0x0)
        /home/barak/local/go/src/net/http/server.go:1718 +0x154
net/http.ListenAndServe(0xc22b52edc0, 0xd, 0x0, 0x0, 0x0, 0x0)
        /home/barak/local/go/src/net/http/server.go:1808 +0xba
github.com/google/cayley/http.Serve(0xc20801e960, 0xc208096080)
        /home/barak/src/cayley/src/github.com/google/cayley/http/http.go:167 +0x44e
main.main()
        /home/barak/src/cayley/src/github.com/google/cayley/cayley.go:242 +0xb0d

goroutine 5 [chan receive]:
github.com/barakmich/glog.(*loggingT).flushDaemon(0x1016780)
        /home/barak/src/cayley/src/github.com/barakmich/glog/glog.go:923 +0x78
created by github.com/barakmich/glog.init·1
        /home/barak/src/cayley/src/github.com/barakmich/glog/glog.go:408 +0x363

goroutine 17 [syscall, 140 minutes, locked to thread]:
runtime.goexit()
        /home/barak/local/go/src/runtime/asm_amd64.s:2232 +0x1

goroutine 7 [syscall, 140 minutes]:
os/signal.loop()
        /home/barak/local/go/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init·1
        /home/barak/local/go/src/os/signal/signal_unix.go:27 +0x35

goroutine 110 [IO wait]:
net.(*pollDesc).Wait(0xc22b5cc060, 0x72, 0x0, 0x0)
        /home/barak/local/go/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc22b5cc060, 0x0, 0x0)
        /home/barak/local/go/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).Read(0xc22b5cc000, 0xc22b5d4000, 0x1000, 0x1000, 0x0, 0x7f4c86816e08, 0xc277eab448)
        /home/barak/local/go/src/net/fd_unix.go:242 +0x40f
net.(*conn).Read(0xc22b53e000, 0xc22b5d4000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /home/barak/local/go/src/net/net.go:121 +0xdc
net/http.(*liveSwitchReader).Read(0xc22b520048, 0xc22b5d4000, 0x1000, 0x1000, 0x1c00000000000087, 0x0, 0x0)
        /home/barak/local/go/src/net/http/server.go:214 +0xab
io.(*LimitedReader).Read(0xc22b411160, 0xc22b5d4000, 0x1000, 0x1000, 0x5f, 0x0, 0x0)
        /home/barak/local/go/src/io/io.go:408 +0xce
bufio.(*Reader).fill(0xc21d626000)
        /home/barak/local/go/src/bufio/bufio.go:97 +0x1ce
bufio.(*Reader).ReadSlice(0xc21d626000, 0xa, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/barak/local/go/src/bufio/bufio.go:295 +0x257
bufio.(*Reader).ReadLine(0xc21d626000, 0x0, 0x0, 0x0, 0xc201015200, 0x0, 0x0)
        /home/barak/local/go/src/bufio/bufio.go:324 +0x62
net/textproto.(*Reader).readLineSlice(0xc277ead1d0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/barak/local/go/src/net/textproto/reader.go:55 +0x9e
net/textproto.(*Reader).ReadLine(0xc277ead1d0, 0x0, 0x0, 0x0, 0x0)
        /home/barak/local/go/src/net/textproto/reader.go:36 +0x4f
net/http.ReadRequest(0xc21d626000, 0xc21cdd0270, 0x0, 0x0)
        /home/barak/local/go/src/net/http/request.go:598 +0xcb
net/http.(*conn).readRequest(0xc22b520000, 0x0, 0x0, 0x0)
        /home/barak/local/go/src/net/http/server.go:586 +0x26f
net/http.(*conn).serve(0xc22b520000)
        /home/barak/local/go/src/net/http/server.go:1162 +0x69e
created by net/http.(*Server).Serve
        /home/barak/local/go/src/net/http/server.go:1751 +0x35e

goroutine 123 [IO wait]:
net.(*pollDesc).Wait(0xc22b58e300, 0x77, 0x0, 0x0)
        /home/barak/local/go/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitWrite(0xc22b58e300, 0x0, 0x0)
        /home/barak/local/go/src/net/fd_poll_runtime.go:93 +0x43
net.(*netFD).Write(0xc22b58e2a0, 0xc313c54f7a, 0x79ed4eb, 0x79ef086, 0x35f0d0, 0x7f4c86816e08, 0xc26c001100)
        /home/barak/local/go/src/net/fd_unix.go:335 +0x5ee
net.(*conn).Write(0xc22b5c2010, 0xc313c54f7a, 0x79ed4eb, 0x79ef086, 0x0, 0x0, 0x0)
        /home/barak/local/go/src/net/net.go:129 +0xdc
net/http.checkConnErrorWriter.Write(0xc22b5200a0, 0xc313c54f7a, 0x79ed4eb, 0x79ef086, 0x0, 0x0, 0x0)
        /home/barak/local/go/src/net/http/server.go:2091 +0x78
bufio.(*Writer).Write(0xc23b7709c0, 0xc313c54f7a, 0x79ed4eb, 0x79ef086, 0xf7a, 0x0, 0x0)
        /home/barak/local/go/src/bufio/bufio.go:562 +0xd5
net/http.(*chunkWriter).Write(0xc22dbb6020, 0xc313c54000, 0x79ee465, 0x79f0000, 0x0, 0x0, 0x0)
        /home/barak/local/go/src/net/http/server.go:269 +0x2f3
bufio.(*Writer).Write(0xc239a2c900, 0xc313c54000, 0x79ee465, 0x79f0000, 0x0, 0x0, 0x0)
        /home/barak/local/go/src/bufio/bufio.go:562 +0xd5
net/http.(*response).write(0xc22dbb6000, 0x79ee465, 0xc313c54000, 0x79ee465, 0x79f0000, 0x0, 0x0, 0xc21d594000, 0x0, 0x0)
        /home/barak/local/go/src/net/http/server.go:1005 +0x1d3
net/http.(*response).Write(0xc22dbb6000, 0xc313c54000, 0x79ee465, 0x79f0000, 0x0, 0x0, 0x0)
        /home/barak/local/go/src/net/http/server.go:977 +0x77
fmt.Fprint(0x7f4c75e47468, 0xc22dbb6000, 0xc27d2cd938, 0x1, 0x1, 0x0, 0x0, 0x0)
        /home/barak/local/go/src/fmt/print.go:223 +0x9f
github.com/google/cayley/http.(*API).ServeV1Query(0xc22b52ebc0, 0x7f4c75e47408, 0xc22dbb6000, 0xc21d4ade10, 0xc239a3abc0, 0x1, 0x1, 0x3)
        /home/barak/src/cayley/src/github.com/google/cayley/http/query.go:102 +0x68b
github.com/google/cayley/http.*API.ServeV1Query·fm(0x7f4c75e47408, 0xc22dbb6000, 0xc21d4ade10, 0xc239a3abc0, 0x1, 0x1, 0xc200000000)
        /home/barak/src/cayley/src/github.com/google/cayley/http/http.go:133 +0x63
github.com/google/cayley/http.func·001(0x7f4c75e47408, 0xc22dbb6000, 0xc21d4ade10, 0xc239a3abc0, 0x1, 0x1)
        /home/barak/src/cayley/src/github.com/google/cayley/http/http.go:82 +0x2f3
github.com/julienschmidt/httprouter.(*Router).ServeHTTP(0xc22b41cc00, 0x7f4c75e47408, 0xc22dbb6000, 0xc21d4ade10)
        /home/barak/src/cayley/src/github.com/julienschmidt/httprouter/router.go:299 +0x18e
net/http.(*ServeMux).ServeHTTP(0xc20803d740, 0x7f4c75e47408, 0xc22dbb6000, 0xc21d4ade10)
        /home/barak/local/go/src/net/http/server.go:1541 +0x17d
net/http.serverHandler.ServeHTTP(0xc22aa07680, 0x7f4c75e47408, 0xc22dbb6000, 0xc21d4ade10)
        /home/barak/local/go/src/net/http/server.go:1703 +0x19a
net/http.(*conn).serve(0xc22b5200a0)
        /home/barak/local/go/src/net/http/server.go:1204 +0xb57
created by net/http.(*Server).Serve
        /home/barak/local/go/src/net/http/server.go:1751 +0x35e

goroutine 149 [sleep]:
github.com/google/cayley/query/gremlin.func·011()
        /home/barak/src/cayley/src/github.com/google/cayley/query/gremlin/session.go:113 +0x45
created by github.com/google/cayley/query/gremlin.(*Session).runUnsafe
        /home/barak/src/cayley/src/github.com/google/cayley/query/gremlin/session.go:126 +0x335

goroutine 164 [IO wait]:
net.(*pollDesc).Wait(0xc22b5cc3e0, 0x77, 0x0, 0x0)
        /home/barak/local/go/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitWrite(0xc22b5cc3e0, 0x0, 0x0)
        /home/barak/local/go/src/net/fd_poll_runtime.go:93 +0x43
net.(*netFD).Write(0xc22b5cc380, 0xc2fc674f7a, 0x79ed4eb, 0x79ef086, 0x35f0d0, 0x7f4c86816e08, 0xc245c51898)
        /home/barak/local/go/src/net/fd_unix.go:335 +0x5ee
net.(*conn).Write(0xc24c8ceae0, 0xc2fc674f7a, 0x79ed4eb, 0x79ef086, 0x0, 0x0, 0x0)
        /home/barak/local/go/src/net/net.go:129 +0xdc
net/http.checkConnErrorWriter.Write(0xc22dbb6140, 0xc2fc674f7a, 0x79ed4eb, 0x79ef086, 0x0, 0x0, 0x0)
        /home/barak/local/go/src/net/http/server.go:2091 +0x78
bufio.(*Writer).Write(0xc215ac66c0, 0xc2fc674f7a, 0x79ed4eb, 0x79ef086, 0xf7a, 0x0, 0x0)
        /home/barak/local/go/src/bufio/bufio.go:562 +0xd5
net/http.(*chunkWriter).Write(0xc22dbb6200, 0xc2fc674000, 0x79ee465, 0x79f0000, 0x0, 0x0, 0x0)
        /home/barak/local/go/src/net/http/server.go:269 +0x2f3
bufio.(*Writer).Write(0xc215ac6a80, 0xc2fc674000, 0x79ee465, 0x79f0000, 0x0, 0x0, 0x0)
        /home/barak/local/go/src/bufio/bufio.go:562 +0xd5
net/http.(*response).write(0xc22dbb61e0, 0x79ee465, 0xc2fc674000, 0x79ee465, 0x79f0000, 0x0, 0x0, 0xc21d4adee0, 0x0, 0x0)
        /home/barak/local/go/src/net/http/server.go:1005 +0x1d3
net/http.(*response).Write(0xc22dbb61e0, 0xc2fc674000, 0x79ee465, 0x79f0000, 0x0, 0x0, 0x0)
        /home/barak/local/go/src/net/http/server.go:977 +0x77
fmt.Fprint(0x7f4c75e47468, 0xc22dbb61e0, 0xc27d2c9938, 0x1, 0x1, 0x0, 0x0, 0x0)
        /home/barak/local/go/src/fmt/print.go:223 +0x9f
github.com/google/cayley/http.(*API).ServeV1Query(0xc22b52ebc0, 0x7f4c75e47408, 0xc22dbb61e0, 0xc21cdd04e0, 0xc2459b3460, 0x1, 0x1, 0x3)
        /home/barak/src/cayley/src/github.com/google/cayley/http/query.go:102 +0x68b
github.com/google/cayley/http.*API.ServeV1Query·fm(0x7f4c75e47408, 0xc22dbb61e0, 0xc21cdd04e0, 0xc2459b3460, 0x1, 0x1, 0xc200000000)
        /home/barak/src/cayley/src/github.com/google/cayley/http/http.go:133 +0x63
github.com/google/cayley/http.func·001(0x7f4c75e47408, 0xc22dbb61e0, 0xc21cdd04e0, 0xc2459b3460, 0x1, 0x1)
        /home/barak/src/cayley/src/github.com/google/cayley/http/http.go:82 +0x2f3
github.com/julienschmidt/httprouter.(*Router).ServeHTTP(0xc22b41cc00, 0x7f4c75e47408, 0xc22dbb61e0, 0xc21cdd04e0)
        /home/barak/src/cayley/src/github.com/julienschmidt/httprouter/router.go:299 +0x18e
net/http.(*ServeMux).ServeHTTP(0xc20803d740, 0x7f4c75e47408, 0xc22dbb61e0, 0xc21cdd04e0)
        /home/barak/local/go/src/net/http/server.go:1541 +0x17d
net/http.serverHandler.ServeHTTP(0xc22aa07680, 0x7f4c75e47408, 0xc22dbb61e0, 0xc21cdd04e0)
        /home/barak/local/go/src/net/http/server.go:1703 +0x19a
net/http.(*conn).serve(0xc22dbb6140)
        /home/barak/local/go/src/net/http/server.go:1204 +0xb57
created by net/http.(*Server).Serve
        /home/barak/local/go/src/net/http/server.go:1751 +0x35e

goroutine 166 [sleep]:
github.com/google/cayley/query/gremlin.func·011()
        /home/barak/src/cayley/src/github.com/google/cayley/query/gremlin/session.go:113 +0x45
created by github.com/google/cayley/query/gremlin.(*Session).runUnsafe
        /home/barak/src/cayley/src/github.com/google/cayley/query/gremlin/session.go:126 +0x335

goroutine 126 [sleep]:
github.com/google/cayley/query/gremlin.func·011()
        /home/barak/src/cayley/src/github.com/google/cayley/query/gremlin/session.go:113 +0x45
created by github.com/google/cayley/query/gremlin.(*Session).runUnsafe
        /home/barak/src/cayley/src/github.com/google/cayley/query/gremlin/session.go:126 +0x335

**Comment by kortschak** [comment]
What was the query?

**Comment by jcmartins** [comment]
curl -X POST http://localhost:64210/api/v1/write -d '[{ "subject": "marcus", "predicate": "/person/phone", "object": "55555", "label": "Label" }]'; echo

**Comment by kortschak** [comment]
I can't replicate that failure:

```
$ curl -X POST http://localhost:64210/api/v1/write -d '[{ "subject": "marcus", "predicate": "/person/phone", "object": "55555", "label": "Label" }]'; echo
{"result": "Successfully wrote 1 quads."}
```

Please try with current tip: b8b3e1b45a78743c8c8c9b09f7f7eeb47115ed10.

**Comment by dennwc** [comment]
Assuming that it's fixed in HEAD.
