### ISSUE TITLE
Pyley is returning error code from cayley server recently

### ISSUE THREAD

**Issue by droidresearch** [cayleygraph/cayley#307]
I have tried using pyley python client of cayley to access the small graph database I have been building. However the response is returning an error. Is it because of any new development happened in cayley because pyley is not updated recently.

from pyley import *
client = CayleyClient()
query=g.Vertex("Humphrey Bogart").All();
response = client.Send(query)
print response.result
{u'error': u'(anonymous): Line 1:8 Unexpected identifier (and 3 more errors)'}

**Comment by paritosh-gupta** [comment]
Hey this is an error with pyley and not cayley. If after 
<code>
query=g.Vertex("Humphrey bogart").All()
</code>
You add
<code>
print query
</code>
The result is 
<code>
g.V('('Humphrey Bogart',)').All()
</code>
which is incorrect in syntax. I browsed pyley's source code really quickly and this error looks like it is in the vertex function. Some string formatting should fix it.

**Comment by dennwc** [comment]
Related to third party lib, not Cayley itself. Closing.
