### ISSUE TITLE
Wire up Optional() for Gremlin API

### ISSUE THREAD

**Issue by pdf** [cayleygraph/cayley#311]
It looks like much of the code already exists, and the iterator is used for the MQL API already.  I started looking at what would be required, but my brain is melting a little trying to onboard all the logic.

**Comment by robertmeta** [comment]
Good idea, moved to feature request forum: https://discourse.cayley.io/t/wire-up-optional-for-gremlin-api/236

**Comment by barakmich** [comment]
This is just a matter of the correct choice of syntax. This appears to be the precident: http://tinkerpop.apache.org/docs/current/reference/#optional-step

Which is really just `.Optional(*Path)` -- and that's about all it intuits....

So this looks valid and has an implementation plan. Reopened
