### ISSUE TITLE
Create a tool to convert/import a relational database into a graph

### ISSUE THREAD

**Issue by betawaffle** [cayleygraph/cayley#321]
It would be nice to have a tool that can take an existing relational database and allow you to convert it into triples/quads. Crazy idea?

**Comment by jzelinskie** [comment]
sounds like a whole 'nother project

**Comment by danbri** [comment]
There are indeed projects (and more recently W3C technologies) devoted to this.

* http://d2rq.org/ "The D2RQ Platform is a system for accessing relational databases as virtual, read-only RDF graphs. It offers RDF-based access to the content of relational databases without having to replicate it into an RDF store. "
* W3C's http://www.w3.org/TR/r2rml/  "This document describes R2RML, a language for expressing customized mappings from relational databases to RDF datasets. Such mappings provide the ability to view existing relational data in the RDF data model, expressed in a structure and target vocabulary of the mapping author's choice."
* Most recently at W3C we have also been working on conventions for describing a map from collections of CSV files into RDF graphs, see http://www.w3.org/TR/csv2rdf/ and nearby, including implementation at http://greggkellogg.net/2015/04/implementing-csv-on-the-web/

@betawaffle - if you're interested maybe a quick writeup showing how e.g. D2RQ could be plugged into Cayley that would be awesome. But the tools already exist, I think this is more a matter of documentation / writeup etc.

**Comment by betawaffle** [comment]
Thanks!

I started reading about R2RML and my eyes glazed over. This may take a while :)

**Comment by dennwc** [comment]
Maybe need to move this to Wiki before closing.

**Comment by robertmeta** [comment]
Moved to feature request section of the forum: https://discourse.cayley.io/t/tool-to-convert-import-a-relational-database-into-a-graph/245
