### ISSUE TITLE
How to have a cayley instance password protected?

### ISSUE THREAD

**Issue by fselcukcan** [cayleygraph/cayley#322]
How to have a cayley instance password protected?
Like in most db having a db account with a username and a password.
Is that done in a different layer, I mean in the perssitence layer that cayley depends on?
If so, how to connect it with nodejs driver for example with `cayley`on npm since it does not offer such option?

**Comment by dennwc** [comment]
There is [an answer](https://groups.google.com/forum/?hl=en#!searchin/cayley-users/password/cayley-users/UjR8gj1l13o/oAtwcBOBCgAJ) on mailing list. In short, Cayley does not provide any authentication mechanisms for now.

**Comment by iddan** [comment]
I think we can close this for now. The discussion can continue on https://discourse.cayley.io/t/10-24-15-cayley-db-username-and-password/128
