### ISSUE TITLE
Document backup of Bolt

### ISSUE THREAD

**Issue by oren** [cayleygraph/cayley#326]
I am not sure if Cayley should expose it or not but as a start we should have a section in the docs about backing up Bolt. Here is the relevant section from Bolt's readme: https://github.com/boltdb/bolt#database-backups

**Comment by robertmeta** [comment]
This is actually something we have to expose to make work -- so this is an enhancement

**Comment by robertmeta** [comment]
The backup issue goes beyond just bolt and is important, moved it to feature request: https://discourse.cayley.io/t/backup-data-via-cayley/237
