### ISSUE TITLE
Kubernetes Replica Controller and Service

### ISSUE THREAD

**Issue by lucmichalski** [cayleygraph/cayley#327]
Hey guys,

Is there any kubernetes files available for deploying cayley ?

And are u working with this team too ? https://github.com/google/primarysources
All could be coded with golang ^^

Cheers,
Luc Michalski

**Comment by robertmeta** [comment]
Interesting idea!  Moved to feature request forum: https://discourse.cayley.io/t/kubernetes-replica-controller-and-service/235

**Comment by barakmich** [comment]
Reopening; this is relatively straightforward to do, a la https://github.com/coreos/torus/blob/master/contrib/kubernetes/torus-k8s-oneshot.yaml -- we even have the quay.io build.
