### ISSUE TITLE
Procedure to use Cayley with a Postgres backend

### ISSUE THREAD

**Issue by marcusmonteiro** [cayleygraph/cayley#339]
Hi guys,

Today I asked [this question](http://stackoverflow.com/questions/33769116/how-to-use-cayley-with-a-postgres-backend/33770627#33770627) on StackOverflow about using Cayley with a Postgres backend, a feature I saw referenced as implemented in [this issue](https://github.com/google/cayley/pull/289). However, it is not documented yet.

Thanks to the answer I got, who referenced the [lib/pq documentation](https://godoc.org/github.com/lib/pq), I managed to connect with a `cfg` file like this:

```
{
    "database": "sql",
    "db_path": "user=user dbname=mydb password=mypassword sslmode=disable",
    "read_only": false
}
```

After that, running the `cayley load --config=cayley.cfg.overview --quads=data/30kmoviedata.nq.gz` command, I ran into the following errors:
    `quadstore.go:302] Couldn't execute horizon: pq: relation "quads" does not exist`
    `cayley.go:277] db: failed to load data: pq: relation "quads" does not exist`

Which I managed to get around executing the following query by hand, on psql:

```
CREATE TABLE quads (
        subject TEXT NOT NULL,
        predicate TEXT NOT NULL,
        object TEXT NOT NULL,
        label TEXT,
        horizon BIGSERIAL PRIMARY KEY,
        id BIGINT,
        ts timestamp,
        subject_hash TEXT NOT NULL,
        predicate_hash TEXT NOT NULL,
        object_hash TEXT NOT NULL,
        label_hash TEXT,
        UNIQUE(subject_hash, predicate_hash, object_hash, label_hash)
    );
```

After that, the `cayley load --config=cayley.cfg.overview --quads=data/30kmoviedata.nq.gz` command loaded the data and I could use the repl.

My questions are: will you update the docs? Did I do anything wrong above? If not, could I update it? Or do you want to do some more tests and development before it?

Thanks.

**Comment by barakmich** [comment]
@marcusmonteiro Great question. The one thing you're missing is the preliminary step
```
cayley init --config=cayley.cfg.overview
```
It'll create the table and indices for you based on the config. Then go ahead and `load`. You're done! If you want to add the line to the docs that'd be super helpful, otherwise this issue tracks it.

**Comment by yiyunyaya** [comment]
Hi all.
I also want to use Cayley with a Postgres backend. But I have got a problem.
Here is my cayley.cfg
`{
"database": "sql",
"db_path": "postgres://test:test@192.168.0.8:5432/test_cayley?sslmode=disable",
"read_only": false
}
`
And the preliminary step goes well
`cayley init -config=cayley.cfg`
But when I run the command 
`cayley load  -config=cayley.cfg -quads="data/testdata.nq"`,
I got the following errors:`E0325 14:15:07.055641 03038 cayley.go:290] db: failed to load data: pq: copyin statement has already been closed`.
How can I solve this problem?
Thanks.

**Comment by oren** [comment]
This setup worked for me a few months ago: https://github.com/oren/cayley-postgres
I haven't try that recently. if you give it a try and it's not working, please let me know.

**Comment by yiyunyaya** [comment]
@oren, thank you for your reply. 
I try it following your steps. But when I run the conmand `cayley load --config=cayley.cfg --quads=canada.nq`, I still got the errors `E0325 17:56:15.118697 13351 cayley.go:290] db: failed to load data: pq: copyin statement has already been closed`.
Cayley I used is built from the source. And postgresql I used is postgresql-8.4.20-5.el6_7.x86_64.

**Comment by dennwc** [comment]
@yiyunyaya I had the same issue recently and fixed it in #378. I could switch back to master branch and cherry-pick the fix for you, or you might try the new branch as alternative solution.

**Comment by AnthonyMete** [comment]
@dennwc - I'm experiencing the same error - could you cherry pick the fix on master to see if that works for me?

**Comment by dennwc** [comment]
@AnthonyMete Done. Check [dennwc/pq_copy](https://github.com/dennwc/cayley/tree/pq_copy) branch.

**Comment by AnthonyMete** [comment]
Thanks @dennwc 

Made the changes but still getting the error when following @oren's setup:

> amete@amete:~/work/src/github.com/google/cayley$ ./cayley load --config=cayley.cfg --quads=canada.nq
> E0427 15:28:59.448573 25331 cayley.go:290] db: failed to load data: pq: copyin statement has already been closed

**Comment by rspeer** [comment]
In case this helps anyone else: I tried following these directions, but the binary version of Cayley I had didn't have a "sql" backend. It turns out you have to install it from source, even though this is presented as the option for people who want to hack on Cayley itself.

**Comment by dennwc** [comment]
SQL works well, docs contains address templates for different database types, so I'm closing this.
