### ISSUE TITLE
Question: Using Cayley as a library backend for other services and extending

### ISSUE THREAD

**Issue by d4l3k** [cayleygraph/cayley#344]
Hey, I'm the developer for https://github.com/degdb/degdb. @barakmich left a comment on the Hacker News post and I was wondering if you could answer some questions.

[@barakmich's comment](https://news.ycombinator.com/item?id=10587568):
> Hey, maintainer of Cayley ( https://github.com/google/cayley ) here. Glad to see more people interested in this space!
> It looks like your code is mostly stubbed out right now -- using gorm for any persistence. You'll find that storing a basic graph is easy; doing more complex traversals and optimization is a harder problem.
> I can appreciate your concept of experimenting with adding monetary incentives on top of requests and datasets. Graphs can be a useful for this, if you view a graph as a (requestable) URI of triples.
> I'd recommend linking in Cayley as your backend (you can use it as a library), and dealing with the requests/economics as an API layer on top. The benefit of open source is you don't have to reimplement everything yourself.
> And if you have novel notions on how to distribute a graph that could be interesting, feel free to ping me. I warn you that it's a hard problem and bold claim in a number of ways -- it's not something you just build without working with a couple people.

My response and questions:
> Hey, I'm the developer for degdb. I'm really glad to see all the interest in this project, even in its very rough initial state.
> I'm aware that gorm isn't a great option for graph storage but seemed to be the easiest way of handling data storage initially. A lot of this project was written at a hackathon in ~36 hours but I've been refactoring.
> I looked at Cayley (and have it as a dependency in an attempt to borrow the Gremlin parser). However, it doesn't seem to have a great way to store "metadata". How would you recommend adding fields to triples such as language, author, creation date, and cryptographic signature? Serializing and shoving them into Quad.Label seems kinda hacky.

I was wondering if you could elaborate on my last question. I'd really like to use Cayley since it makes things a lot easier.

Thanks!

**Comment by robertmeta** [comment]
Better late than never I guess. :)  

You got the way to do it -- your metadata is just more related data -- so attach it with predicates!
