### ISSUE TITLE
Cayley does not bind on all interfaces by default

### ISSUE THREAD

**Issue by matiwinnetou** [cayleygraph/cayley#349]
Current behaviour:
When I start cayley without a host parameter it gets only bound to 127.0.0.1 instead of on all interfaces.

```
[pi@raspberry_pi2 cayley]$ cayley http --dbpath=data/testdata.nq   
Cayley now listening on 127.0.0.1:64210
```

Expected:
When I start cayley I expect that it is bound to all interfaces

Notes:
It does work when I bind to a specific port though:

```
[pi@raspberry_pi2 cayley]$ cayley http --dbpath=data/testdata.nq --host="192.168.1.100"
Cayley now listening on 192.168.1.100:64210
```

Cayley version:
git sha1: f143602b8ae880ec975e4c154dd010047de80c1f

Environment: Arch Linux - Rasberry PI  2 - (arm7)

Interface details:

```
[pi@raspberry_pi2 cayley]$ ifconfig
docker0: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        inet 172.17.0.1  netmask 255.255.0.0  broadcast 0.0.0.0
        ether 02:42:92:82:77:a8  txqueuelen 0  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.1.100  netmask 255.255.255.0  broadcast 192.168.1.255
        inet6 fe80::ba27:ebff:fe9e:9496  prefixlen 64  scopeid 0x20<link>
        ether b8:27:eb:9e:94:96  txqueuelen 1000  (Ethernet)
        RX packets 759688  bytes 534723126 (509.9 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 557066  bytes 96142091 (91.6 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 0  (Local Loopback)
        RX packets 61403  bytes 98526718 (93.9 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 61403  bytes 98526718 (93.9 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
```

**Comment by paultag** [comment]
I'd argue this is a feature - in fact, most webservers bind to localhost unless you give it an explicit interface to bind to -- in fact, I've seen other projects get bug reports when they bind to all interfaces (and not just localhost).

What's the motivation behind binding to 0.0.0.0 by default? I might not be totally groking

**Comment by paultag** [comment]
(such as [rethinkdb](https://github.com/rethinkdb/rethinkdb/issues/3154) or [elasticsearch](https://github.com/elastic/elasticsearch/issues/9064))

**Comment by matiwinnetou** [comment]
@paultag this is what the documentation describes:

```
[pi@raspberry_pi2 cayley]$ cayley
Cayley is a graph store and graph query layer.

...
  -host="127.0.0.1": Host to listen on (defaults to all).
 ...

```

**Comment by paultag** [comment]
@matiwinnetou Ah, might be good to rename the bug to the docs lie :)

**Comment by matiwinnetou** [comment]
@paultag depends how one looks at this. My expectation would be to bind to all interfaces but it is a question of a taste and an opinion.

**Comment by barakmich** [comment]
Then the documentation is out of date, and @paultag is correct in the general case. In fact, if you look through previous issues, it started out as open to all and the issue was to constrain it to 127.0.0.1 (unless otherwise specified)

--Barak
(mobile)

-----Original Message-----
