### ISSUE TITLE
cayley init and cayley load disagree on behaviour when using mem back end

### ISSUE THREAD

**Issue by kortschak** [cayleygraph/cayley#35]
db.Init() returns true and does nothing, while db.Load() depends on the existence of a file via db.Open().

This is primarily a documentation issue. When running cayley with a mem back end, init and load should print meaningful messages - that those commands are not necessary.

The behaviour for loading triples differs when using mem too; the data are specified through the config and not via the triples parameter. This is confusing.

**Comment by dennwc** [comment]
Fixed in a new CLI
