### ISSUE TITLE
Is the Cassandra-backend branch still in develop?

### ISSUE THREAD

**Issue by ustczen** [cayleygraph/cayley#350]
In my opinion, With the emergence of ScyllaDB, a Cassandra backend  would be the "killer backend" of cayley. But the last commit of Cassandra-beckend branch appears at 8 month ago..

**Comment by oren** [comment]
Related question from ScyllaDB's group: https://groups.google.com/forum/#!topic/scylladb-users/_IewBKoa7Ek

**Comment by jcmartins** [comment]
+1 to Scylla backend

**Comment by dennwc** [comment]
Considering as a duplicate of #20
