### ISSUE TITLE
query: Schema/RDFS

### ISSUE THREAD

**Issue by dennwc** [cayleygraph/cayley#353]
I've been working on a schema layer for Cayley recently to make querying/writing structured data easier. I want to discuss it's design, if someone interested in it as I do. It can be really useful, because you still can do sophisticated graph queries and then query structured data for results.

For example, lets consider this data set. It describes a `Thing` class with two properties.

```
<http://schema.org/Thing> <http://www.w3.org/2000/01/rdf-schema#label> "Thing" .
<http://schema.org/Thing> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://www.w3.org/2000/01/rdf-schema#Class> .
<http://schema.org/Thing> <http://www.w3.org/2000/01/rdf-schema#comment> "The most generic type of item." .

<http://schema.org/url> <http://schema.org/domainIncludes> <http://schema.org/Thing> .
<http://schema.org/url> <http://www.w3.org/2000/01/rdf-schema#label> "url" .
<http://schema.org/url> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://www.w3.org/1999/02/22-rdf-syntax-ns#Property> .
<http://schema.org/url> <http://schema.org/rangeIncludes> <http://schema.org/URL> .
<http://schema.org/url> <http://www.w3.org/2000/01/rdf-schema#comment> "URL of the item." .

<http://schema.org/name> <http://schema.org/domainIncludes> <http://schema.org/Thing> .
<http://schema.org/name> <http://www.w3.org/2000/01/rdf-schema#label> "name" .
<http://schema.org/name> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://www.w3.org/1999/02/22-rdf-syntax-ns#Property> .
<http://schema.org/name> <http://schema.org/rangeIncludes> <http://schema.org/Text> .
<http://schema.org/name> <http://www.w3.org/2000/01/rdf-schema#comment> "The name of the item." .
```

I came up with a few rules for mapping quads to fields:
- `"."` tag means "save current node to this field"
- `"pred"` (`"pred > *"` in full form) means "save object(s) with this predicate"; maps to `path.Save`
- `"pred < *"` is a reverse of previous action; maps to `SaveReverse`
- `"pred > obj1,obj2"` means "filter nodes that have a specific object on predicate"; maps to `Has`
- `"pred < obj1,obj2"` is a reverse of previous action; maps to `HasReverse`
- Node names in struct tags can be compacted: `rdfs:label` is the same as `http://www.w3.org/1999/02/22-rdf-syntax-ns#label`

Using these rules one can write a following mapping for an example data set:

``` Go
// IRI is built into the library.
type IRI string

// A custom type, have no special meaning.
type Property struct {
    // Private field for filtering nodes of certain type. Has no special meaning.
    rdfType struct{} `quad:"rdf:type > rdf:Property"`
    // Current node, used as an ID.
    IRI     IRI     `quad:"."`
    // Saves an object's name for rdfs:label predicate.
    Name    string `quad:"rdfs:label"`
    Comment string `quad:"rdfs:comment"`
    // Saves all objects for schema:rangeIncludes predicate.
    Expects []IRI `quad:"schema:rangeIncludes"` 
}

type Class struct {
    rdfType    struct{} `quad:"rdf:type > rdfs:Class"`
    IRI        IRI    `quad:"."`
    Name       string `quad:"rdfs:label"`
    Comment    string `quad:"rdfs:comment"`
    // Custom types in fields are also supported.
    // This field is an analog of `In("schema:domainIncludes").Save(...)`.
    // It will load and save all nodes with the structure described above.
    Properties []Property `quad:"schema:domainIncludes < *"`
}
```

The resulting path for the `Class` will be in a following form:

``` Go
// Node names are in short form for convenience
path.StartMorphism().
  Has("rdf:type","rdfs:Class").
  Tag("IRI"). // name of the field in Go struct
  Save("rdfs:label","Name"). // actually an OptionalSave if the field is not required
  Save("rdfs:comment","Comment").
  SaveReverse("schema:domainIncludes","Properties")
```

And the same for `Property`:

``` Go
path.StartMorphism().
  Has("rdf:type","rdf:Property").
  Tag("IRI").
  Save("rdfs:label","Name").
  Save("rdfs:comment","Comment").
  Save("schema:rangeIncludes","Expects")
```

And finally, we will get the following struct value after query:

``` Go
result := Class{
  Name:    `Thing`,
  IRI:     `http://schema.org/Thing`,
  Comment: `The most generic type of item.`,
  Properties: []Property{
    {IRI: `http://schema.org/name`, Name: `name`, Comment: `The name of the item.`, Expects: []IRI{`http://schema.org/Text`}},
    {IRI: `http://schema.org/url`, Name: `url`, Comment: `URL of the item.`, Expects: []IRI{`http://schema.org/URL`}},
  },
}
```

Reverse operation is also easy, you can describe your data with a struct tags and write these structs to graph directly.

There is also an interesting consequence: if graph data includes RDFS class definitions, you can load the graph, query all classes from it using mapping described above and then generate Go source file with definitions of all classes in that graph (including the struct tags for reverse mapping).
There is an example of the same `Property` class auto-generated from [schema.org](https://schema.org) data:

``` Go
// A property, used to indicate attributes and relationships of some Thing; equivalent to rdf:Property.
type Property struct {
    rdfType struct{} `quad:"rdf:type > schema:Property"`
    IRI     quad.IRI `quad:"."`

    Intangible

    // Relates a property to a class that is (one of) the type(s) the property is expected to be used on.
    DomainIncludes []Class    `quad:"schema:domainIncludes"`
    // Relates a property to a property that is its inverse. Inverse properties relate the same pairs of items to each other, but in reversed direction. For example, the 'alumni' and 'alumniOf' properties are inverseOf each other. Some properties don't have explicit inverses; in these situations RDFa and JSON-LD syntax for reverse properties can be used.
    InverseOf      []Property `quad:"schema:inverseOf"`
    // Relates a property to a class that constitutes (one of) the expected type(s) for values of the property.
    RangeIncludes  []Class    `quad:"schema:rangeIncludes"`
    // Relates a term (i.e. a property, class or enumeration) to one that supersedes it.
    //
    // Allowed types: [http://schema.org/Class http://schema.org/Enumeration http://schema.org/Property]
    SupersededBy []quad.IRI `quad:"schema:supersededBy"`
}
```

Any feedback is welcome. If the design looks good, I can file a PR for it.

**Comment by dennwc** [comment]
Merged already

**Comment by amritsingh1** [comment]
Can we control the depth upto which the schema will try to load the nested child nodes.
I mean if A->B->C->D->E are connected nodes each of type "MyClass" such that "B" is childOf "A" and "C"  is childOf of "B" and so on, can we do something that will make the loading stop after reaching the depth at which "D" is residing. It will really be of great help if somebody can tell me how to accomplish this.

**Comment by akankshachandel** [comment]
Do we have a generic SPARQL query which extracts RDF schema of a any ontology?

**Comment by dennwc** [comment]
@akankshachandel We don't support SPARQL yet. This library uses internal query primitives to build a query that return a schema from the dataset.

**Comment by akankshachandel** [comment]
Do you have any tips or leads, actually I have been working on retrieving the RDF schema of ontology for a while now! any information helps!
