### ISSUE TITLE
Dockerfile not work

### ISSUE THREAD

**Issue by quchunguang** [cayleygraph/cayley#357]
1. By change `RUN go install -v github.com/google/cayley` to `RUN go install -v github.com/google/cayley/cmd/cayley`, i can `sudo docker run ...` now.

2. It seems the default port of http exposed ":64321" in Dockerfile are different with the command `cayley` "64210", i changed it in Dockerfile, `EXPOSE 64210`.

3. Unknown issue. Still, I can not get web interface in "127.0.0.1:64210". Does the command 'cayley' depend on any file in the repos path? If so, may be the `RUN` command (reference 1.) need to changed to `RUN go build /go/src/github.com/google/cmd/cayley`, and change the command `CMD` to `CMD ["/go/src/github.com/google/cayley/cayley", "http", "-config", "/data/cayley.cfg", "-init"]`.

Sorry, i have no mush time to inspect the source, all of above are based on guess.

```bash
cat data/cayley.cfg
{
    "database": "leveldb",
    "db_path": "/data/snsrobot",
    "read_only": false
}
```

**Comment by mayankasthana** [comment]
The changes required to fix this are - 
1. Changing the port in the Dockerfile to 64210.
2. Making cayley bind to all interfaces. (127.0.0.1 inside a container is not accessible outside)
