### ISSUE TITLE
Add recursive support

### ISSUE THREAD

**Issue by Quentin-M** [cayleygraph/cayley#358]
Creating an issue to track the state of that feature request. Some work has been done in barakmich/transitive_closure.

The recursive iterator works just fine for me, all my test passes with it. It could probably be merged in my opinion. The SQL recursive iterator is not finished yet and my attempt to make it work did not succeed so far - the generated SQL is wrong and I have been unsure how to replace a FixedIterator by a sqlIterator to create a new SQL recursive iterator.

**Comment by robertmeta** [comment]
@dennwc -- want this to live here or bumped over to feature-request?

**Comment by dennwc** [comment]
Let it be here. We have an experimental implementation at least.

**Comment by dennwc** [comment]
Implemented via #470 / #547
