### ISSUE TITLE
Cayley returns non-null results for non-existent vertices

### ISSUE THREAD

**Issue by isikfsc** [cayleygraph/cayley#362]
1. *On [cayley-graph.appspot.com](http://cayley-graph.appspot.com)*, Cayley returns a non-null result when a non existent vertex queried.
(**first query**)
```
g.V("qwe").All()
```
**result of the first query**
```
{
 "result": [
  {
   "id": ""
  }
 ]
}
```

wheras it returns when edges asked too;
(**second query**)
```
**result of the second query**
g.V("qwe").Both().All()
```
```
{
 "result": null
}
```

I think that first result should be `null`, as well, If there is not something that I miss here.

2. *Also, on my laptop*, on http://localhost:64210 and on repl, cayley loaded with 30Kmovies sample data, I have different results for above queries. I have the very latest source builds of Cayley.

for the **first query** above for a non-existent vertex again, the result is, not even empty string:
```
{
 "result": [
  {
   "id": "qwe"
  }
 ]
}
```

For the **second query** it is `null` again as above second result.

What do you think?

**Comment by dennwc** [comment]
Cannot reproduce on HEAD. Please try latest release (0.5) and reopen if necessary.
