### ISSUE TITLE
Implement GraphQL

### ISSUE THREAD

**Issue by jcmartins** [cayleygraph/cayley#370]
Please see it:
https://github.com/graphql-go/graphql

**Comment by dennwc** [comment]
Quick look shows, that it relies on prior knowledge about schema. To implement this we need at least to support `sameAs` to allow usage of any RDF dictionary.
Btw, #353 may be handy to query current schema, but it may also be done by hand.

**Comment by batwicket** [comment]
Perhaps dataloader is the new point of integration.
https://github.com/facebook/dataloader

**Comment by dennwc** [comment]
Actually we can make it work, by using the parser from [graphql-go](https://github.com/graphql-go/graphql) directly.

**Comment by jcmartins** [comment]
Great! 
+1 to graphql-go

**Comment by pinghe** [comment]
+1

**Comment by robertmeta** [comment]
Since no implementation work as been done on this (though we are excited about it!) we are moving this to the feature request forum: https://discourse.cayley.io/t/implement-graphql/228

**Comment by evseevnn** [comment]
When we can try that?
