### ISSUE TITLE
SQlite backend

### ISSUE THREAD

**Issue by gozes** [cayleygraph/cayley#377]
Barak Michener said on his GopherCon 2015 talk that tables are graphs and graphs are tables. If so then it would be really useful to have a SQlite backend  so that one can use cayley in a go application where disk space is the, like a mobile devices, rather then performance

**Comment by mro** [comment]
I went along that path for librdf – I've not fully arrived, however. http://purl.mro.name/librdf.sqlite/

Hope it helps.

**Comment by gozes** [comment]
@mro I am not sure what I should do with that, sorry.

**Comment by mro** [comment]
@gozes if in doubt: nothing.

**Comment by gozes** [comment]
@mro that is good life advices :smile:

**Comment by robertmeta** [comment]
Haha, the way this ended was the best.  Moving it to feature request forum: https://discourse.cayley.io/t/sqlite-storage-engine/219
