### ISSUE TITLE
How to approach temporality

### ISSUE THREAD

**Issue by Thijxx** [cayleygraph/cayley#381]
I wonder how I can add temporality to my graph, just adding a time-stamp node doesn't seem smart.

**Comment by dennwc** [comment]
@Thijxx I think it is the only option for now. Do you want to add timestamps to quads or nodes?

**Comment by Thijxx** [comment]
@dennwc to quads, I use the HTTP API so I'll just cook up all my quads for a fact and then give them all the same time-stamp when writing. This way I should be able to track graph pieces in time.

**Comment by dennwc** [comment]
@Thijxx Technically all quads are written with the current timestamp, but this information is not accessible for now. Probably we should provide some way to use it in the API.
Yes, I'm already thinking of ways to allow attaching additional data to both nodes and quads. Some preparation work is done in #378, but it's not enough.

**Comment by robertmeta** [comment]
Moved to the feature request forum for the moment: https://discourse.cayley.io/t/support-temporary-data/208
