### ISSUE TITLE
Docker run command: FATA[0008] Tag latest not found in repository

### ISSUE THREAD

**Issue by GustavoRPS** [cayleygraph/cayley#382]
I'm trying to run X but I'm getting this message:
```
~$ sudo docker run -v $PWD/databases/cayley/data:/data -p 64321:64321 -d quay.io/barakmich/cayley
Unable to find image 'quay.io/barakmich/cayley:latest' locally
```
Could add some tags to the repository in quay.io?

**Comment by dennwc** [comment]
Fixed now. Please check [cayleygraph/cayley](https://quay.io/repository/cayleygraph/cayley) repository.
