### ISSUE TITLE
succinct way to get shortest paths

### ISSUE THREAD

**Issue by rogeronline** [cayleygraph/cayley#388]
Hi there,
I got following query for shortest path from germlindocs

gremlin> g.v(1).out.loop(1){it.object.id != "5" && it.loops < 6}.path
==>[v[1], v[4], v[5]]

http://gremlindocs.spmallette.documentup.com/#shortest-path

But it seems cayley does not fully support Germlin grammar...that query doesn't work
Anyone can shed some light here?
Thanks a ton!

**Comment by rogeronline** [comment]
let me put this way, is there a way to check if 2 objects are connected?
same question was post by someone else
https://groups.google.com/forum/#!msg/cayley-users/Ml4X9FZsQcQ/BgCZNkA4H4IJ

**Comment by dennwc** [comment]
Hi @rogeronline,

There is no way to check it directly right now.
The [barakmich/transitive_closure](https://github.com/barakmich/cayley/tree/transitive_closure) branch implements functionality necessary for "loop" command in Gremlin, but it is exposed only to Golang.
You may also try to achieve the same result with manual iteration, as described in the mailing list.

**Comment by robertmeta** [comment]
@dennwc should this get moved over to the feature-request area -- or is this something more in-flight in your mind?

**Comment by dennwc** [comment]
@robertmeta May be moved. Not a priority right now.

**Comment by robertmeta** [comment]
Moved to the feature request list: https://discourse.cayley.io/t/succinct-way-to-get-shortest-paths/243
