### ISSUE TITLE
Cayley not work after delete a quad

### ISSUE THREAD

**Issue by anchem** [cayleygraph/cayley#390]
Hello! I'm new here and have a poor English. What I found was that when I delete a quad using command like this:
`cayley> :d emily follows fred .`
cayley not work when I query who follows fred. Command like this:
`cayley> g.V("fred").In("follows").All()`
The data I use is "testdata.nq" under "data" fold in release binary version.
Is there any thing wrong of my usage?

**Comment by dennwc** [comment]
Hi @anchem !

What backend are you using for this example?

**Comment by anchem** [comment]
levelDB @dennwc

**Comment by robertmeta** [comment]
@anchem I can not reproduce this issue.

```
cayley repl --dbpath=.\data\testdata.nq
cayley> :d emily follows fred .
cayley> g.V("fred").In("follows").All()

****
id : bob
=> <nil>
-----------
2 Results
Elapsed time: 2.6428 ms

cayley>
```

**Comment by robertmeta** [comment]
If you can give us more information on your environment, we can reopen this.
