### ISSUE TITLE
installing cayley from go get dose not produce a binary to run

### ISSUE THREAD

**Issue by gozes** [cayleygraph/cayley#391]
I just notice that after using go get to install cayley there is nothing under bin in my go workspace. How I am to run cayley so I can be use by other projects if it dose not binary to run it from?

**Comment by rusenask** [comment]
Hi, `go get` only fetches dependencies, although Cayley uses Godep for dependency management. To build Golang binary use `go build`, it's in the docs:

```
git clone https://github.com/google/cayley
cd cayley
go get github.com/tools/godep
godep restore
go build ./cmd/cayley
```
