### ISSUE TITLE
Main repo moved from google. How to be oriented?

### ISSUE THREAD

**Issue by Losiara** [cayleygraph/cayley#398]
Noticed that google's repo renamed? And mainteiner changed. Also know that maintainer has other fork. Which of the repos will be main? Are there plans for further cayley development?

May be some marks needed on readme about it?

**Comment by dennwc** [comment]
Maintainer is the same, @barakmich will still be working on Cayley :) The only change is the location of repo and core team was expanded a bit (check [cayleygraph](https://github.com/cayleygraph)).

Now we have plans to merge some PR from forks, so Cayley is in active development again.

**Comment by Losiara** [comment]
Good news!

**Comment by robertmeta** [comment]
Just before closing, to be absolutely clear. 

> Noticed that google's repo renamed? 

Yep, it is no longer a Google project, it is a true community project. 


> And mainteiner changed. 

Did not.


> Also know that maintainer has other fork.

Does not.


> Which of the repos will be main?

This one.


> Are there plans for further cayley development?

Yes, which is why it is no longer under Google.


> May be some marks needed on readme about it?

Coming soon.
