### ISSUE TITLE
Optimize HasA Iterator

### ISSUE THREAD

**Issue by robertmeta** [cayleygraph/cayley#405]
There are some simple optimizations that can be done there. And was the first one to get right, this is the next one.
A simple example is just to convert the HasA to a fixed (next them out) if the subiterator size is guessable and small.

**Comment by iddan** [comment]
As this is stale for 3 years can we close it for now @robertmeta @dennwc ?

**Comment by dennwc** [comment]
Yes, I think it may be solved for some queries already. Further optimizations are either backend-specific or deserve a new issue.
