### ISSUE TITLE
Replication

### ISSUE THREAD

**Issue by robertmeta** [cayleygraph/cayley#417]
Technically it works now if you piggyback on someone else's replication, but that's cheating.  We speak HTTP, we can send quad sets over the wire to some other instance. Bonus points for a way to apply morphisms first -- massive graph on the backend, important graph on the frontend.

**Comment by dennwc** [comment]
Related to #302

**Comment by robertmeta** [comment]
Closed and moved to forum: https://discourse.cayley.io/t/replication/215
