### ISSUE TITLE
Ultimate Direction

### ISSUE THREAD

**Issue by pjebs** [cayleygraph/cayley#426]
Obviously the Cayley project doesn't have the resources and 'star' power that Neo4J has, atleast at the moment.

I was wondering what the ultimate direction was for Cayley?
Is it meant to be a powerful substitute to Neo4J for super serious projects and operate in a production capacity?

Will it be built to scale and operate in large scale projects - not necessarily to facebook's level - but something slightly less (i.e. the _kind_ of stuff Neo4J is being used for)?

I'm just asking because I wondering whether I should invest learning Neo4J or Cayley.

I think a lot of people new to graph databases would also like to know.

**Comment by robertmeta** [comment]
pjebs, love the question!  But I think it fits better on our discussion forum: https://discourse.cayley.io/ under [Technical Discussions](https://discourse.cayley.io/c/technical-discussions) and maybe an entry should go on the [FAQ Thread](https://discourse.cayley.io/t/faq-frequently-asked-questions/127).

If you want to have a longer conversation we should have it over there, but briefly I will answer your top level questions.  Cayley intends to be a performant, best in class graph database layer supporting all scales (using correct backends).  Cayley is already used in business critical places.  As for the bolder long-term vision, I will leave those pronouncements to @barakmich.

**Comment by pjebs** [comment]
@robertmeta Is there any information on what the different advantages/disadvantages are of the different backends? particularly speed.

Also are you familiar with the way Neo4J works?
If not, there is a small image near the top of this page which shows conceptually the difference in the way data _can_ be handled: http://blog.thefrontiergroup.com.au/2014/10/look-cayley/

My question is, is their an artificial way to store and extract data similar to the way Neo4J does it. Obviously Cayley doesn't work like this as per image on Right Hand side. But would storing data as a json string work? Would we lose ability to query if we even attempt to store data like Neo4J?

**Comment by robertmeta** [comment]
Lets keep the conversation on discourse.
