### ISSUE TITLE
Postgres in Cayley 0.5 not writing to database

### ISSUE THREAD

**Issue by carnalim** [cayleygraph/cayley#429]
I've initialized a new postgres database in the most recent Cayley release, when I look at the database I see the quads table. If I go to upload sample data it will successfully upload and will say successful write, but nothing will appear in the database and nothing with return as a result. I have done the inert quad UI as well and that does not insert. 

When I try and do a command line load function I am getting this error:
E0706 13:53:07.036332 06409 cayley.go:290] db: failed to load data: pq: copyin statement has already been closed

**Comment by dennwc** [comment]
I'm aware of the issue, it will be fixed soon.

**Comment by dennwc** [comment]
Quick fix can be found here: [dennwc/pq_copy](https://github.com/dennwc/cayley/tree/pq_copy)
But probably it's better to wait for #378 to land, since the issue was fixed there already.

**Comment by carnalim** [comment]
Thanks, do we know an ETA when #378 will land? I've actually used your branch before but thought .5 would have had the Postgres fixes.

**Comment by robertmeta** [comment]
@dennwc Can we not shit these fixes separately from #378?

**Comment by dennwc** [comment]
Already thinking that I need to push a fix before #378, as a hotfix for 0.5.1, probably.

**Comment by carnalim** [comment]
Yeah I think a hotpatch is needed for 0.5 as SQL is completely unusable right now.

**Comment by robertmeta** [comment]
@carnalim I am tempted to agree with you.  @barakmich ?
