### ISSUE TITLE
Better startup banner

### ISSUE THREAD

**Issue by robertmeta** [cayleygraph/cayley#431]
A startup banner with a little more information on backends and any important config settings would be useful.  From https://github.com/cayleygraph/cayley/issues/430 and @kortschak.  This also would be a fairly solid starting issue for someone to tackle.

**Comment by dennwc** [comment]
Also, need to bake in commit hash of the build. It usually done via linker flags.

**Comment by robertmeta** [comment]
This feels about at my level, I will grab it.

**Comment by dennwc** [comment]
v0.7 prints a path to config and what backend is used. Closing for now. If you have something else in mind, please reopen.
