### ISSUE TITLE
Object persistence interfaces 

### ISSUE THREAD

**Issue by robertmeta** [cayleygraph/cayley#432]
The idea is fairly simple, it lets you take objects or structs in languages that have them and write them to Cayley and then read them back into complex objects.  The interface will take care of all the annoying busy work of creating the preds and so forth. 

This requires two "special" things to be involved, one is an ID (generally a UUID) and the other is a object type property, so that avoids trying to load into a nonsense object or struct. 

@barakmich has some good ideas for doing this on the Cayley side that I mostly grasp, but not enough to implement.  This first pass will probably just be Go via tags -- and then maybe we try to do it in Node, Python or Ruby next just for fun.

**Comment by dennwc** [comment]
Same as #353. I have implemented it already. But it's not a PR as you can see, because it is relatively slow. Before proceeding we need to fix how query optimization works. I also have a change for this, but we need to discuss it in details.

**Comment by robertmeta** [comment]
@dennwc I think the two things are a little different -- you are talking about like a native to Cayley solution, which is along the lines of what @barakmich talked to me about, he used the term "Topic Queries" which seems very close to your #353 so he has some ideas baking on this too.

What I am talking about is client libraries that take an object or struct in LanguageX and persist it down to Cayley and can later bring it back up.  If #353 got in -- these object persistence layers would take advantage of it, but it wouldn't be a replacement for them, because part of their value is understanding what an object looks like in Go / Ruby / Python (whatever) and how to walk it in both directions.

**Comment by dennwc** [comment]
@robertmeta Makes sense :)

For me Ruby / Python / etc are external, so we can only influence it by supporting some query language. Probably GraphQL will be a good fit for it. But I don't know how mutations are made there.

**Comment by robertmeta** [comment]
This isn't even really a Cayley feature as @dennwc pointed out -- removing it from our issues list.
