### ISSUE TITLE
Firebase backend

### ISSUE THREAD

**Issue by quentinR** [cayleygraph/cayley#433]
Hi guys I was wondering if a Firebase backend would be possible with Cayley and why if not. Thoughts?

**Comment by dennwc** [comment]
Definitely possible. Maybe will try to implement it later)

**Comment by robertmeta** [comment]
Moved to feature request forum until it is a bit more flushed out: https://discourse.cayley.io/t/firebase-storage-engine/200

**Comment by quentinR** [comment]
Thanks ! 👍
