### ISSUE TITLE
Any way to use Cayley on a Mobile device platform?

### ISSUE THREAD

**Issue by joshglenn** [cayleygraph/cayley#438]
Is there any way to use this on a mobile device (actually having Cayley on the device where the user can interact with the graph database even while the device is disconnected)?

**Comment by pjebs** [comment]
Yes but you have to know Go programming language and use gomobile to make objective c  bindings etc. It'd be a bit messy but doable since go is not the native language for iOS or android. You'll probably also be restricted to the in memory storage engine.

**Comment by pjebs** [comment]
I plan to work on this in a few months time actually. I've already got plans on how to tackle it and organise the interface.

**Comment by robertmeta** [comment]
Yeah, in theory this would work right now using a pure-go stack (Cayley / Bolt) and GoMobile.  It seems like this is worth having a continued discussion on the list about it: https://discourse.cayley.io/t/cayley-on-mobile/187

**Comment by zhuguocheng29** [comment]
@pjebs Do you migrate cayley to mobile device platform successfully? now I want to migrate cayley to Android, but encounter some troubles. Could you give me some advice？
