### ISSUE TITLE
Incomplete insertion of quads

### ISSUE THREAD

**Issue by offero** [cayleygraph/cayley#441]
>  wc -l rels_all.nq
>  93000 rels_all.nq
> 
> uniq rels_all.nq | wc -l
> 92999
> 
>  curl http://127.0.0.1:64210/api/v1/write/file/nquad -F NQuadFile=@rels_all.nq
> {"result": "Successfully wrote 93000 quads."}

Mongo:

> db.quads.count()
> 9421
> db.nodes.count()
> 375

cayley_v0.5.0_darwin_amd64
mongodb-osx-x86_64-2.6.12

**Comment by robertmeta** [comment]
Do you have a public dataset you could test with so we could attempt to reproduce with same data?

**Comment by offero** [comment]
I'll have to anonymize it. Here's a quick sample of what it looks like:

> "AAA" "REL_A" "ZZZ" .
"BBB" "REL_A" "ZZZ" .
"CCC" "REL_A" "ZZZ" .
"DDD" "REL_A" "ZZZ" .
"EEE" "REL_A" "ZZZ" .
"FFF" "REL_A" "ZZZ" .
"GGG" "REL_A" "ZZZ" .
"HHH" "REL_A" "ZZZ" .
"III" "REL_A" "ZZZ" .
"JJJ" "REL_A" "ZZZ" .
"KKK" "REL_A" "ZZZ" .

**Comment by robertmeta** [comment]
Maybe you can get same bug with the sample 30kmovies data?

**Comment by offero** [comment]
I was able to import to 30kmovies data.

> db.quads.count()
471705

The problem is repeatable. It must be something with the file or the literals...

**Comment by dennwc** [comment]
Do you have the same problem while importing dataset from the CLI directly?

**Comment by offero** [comment]
>  ./cayley load --config=cayley.cfg --quads=rels_all.nq
E0709 22:20:23.092158 18447 cayley.go:290] db: failed to load data: quad exists

**Comment by kortschak** [comment]
Do you get the same error with another backend?

**Comment by dennwc** [comment]
There is an option to skip duplicates somewhere. Or you can start a clean import.

**Comment by offero** [comment]
This worked for me. I had a neo4j database that had duplicate edges so my nquads export script seemingly had the same edges twice.

> ./cayley load --config=cayley.cfg --quads=rels_all.nq --alsologtostderr --ignoredup

Maybe add the same kind of error message in the http response when it fails?

**Comment by dennwc** [comment]
Sure, need to find out why request fails that way.

**Comment by dennwc** [comment]
There was a bug when HTTP interface will drop an error and report a successful write. It was fixed some time ago, so I'll close this.
