### ISSUE TITLE
Javascript API source?

### ISSUE THREAD

**Issue by mcollina** [cayleygraph/cayley#45]
I'm the author of [LevelGraph](http://github.com/mcollina/levelgraph), congrats for doing this project! I have been using the very same technique for storing graph database in LevelDB for quite some time and it works great!

I would like to know where are the sources of the JS APIs, I would love to see if I can adopt the same interface for LevelGraph, so we can have a Gremlin.js thing.

**Comment by robertmeta** [comment]
This seems like it was asked/answered -- if anything else needs to be done ping this ticket and I will look at reopening it.
