### ISSUE TITLE
UI: Typed Quad JSON Formatting Issue

### ISSUE THREAD

**Issue by carnalim** [cayleygraph/cayley#454]
I have been using one of the more recent builds I entered in a sample quad as follows:
`<matt> <likes> <coffee> <uuid-1>`

When I query for Matt like so:
`g.V("<matt>").All()`

I get the following weird Unicode formatting in the UI:

```
{
     "result": [
      {
       "id": "\u003cmatt\u003e"
      }
     ]
    }
```

**Comment by dennwc** [comment]
It's a valid JSON encoding of `<matt>`. UI does not decode the output, thus you see the value escaped.

**Comment by carnalim** [comment]
Is it something that should be changed for the UI?

**Comment by dennwc** [comment]
Maybe UI can decode output to show it nicely to the user. In any case, I'm not the one who will do it right now, sorry.
