### ISSUE TITLE
Has() seems to re-arrange order of Iterate()?

### ISSUE THREAD

**Issue by kris-runzer** [cayleygraph/cayley#467]
Using the Go library, if I try the following my values come back in the defined Out() order:

```
p := cayley.StartPath(qs, quad.String("a")).Out("name", "authed_by")

values, _ := p.Iterate(nil).AllValues(qs)

fmt.Println("name =", values[0].Native().(string))  // matches to name
fmt.Println("auth =", values[1].Native().(string))  // matches to authed by
```

If I try to to add a Has() into the path my values indexing get's swapped.

```
p := cayley.StartPath(qs, quad.String("a")).
    Has("type", quad.String("organization")).
    Out("name", "authed_by")

values, _ := p.Iterate(nil).AllValues(qs)

fmt.Println("name =", values[0].Native().(string))  // matches to authed by
fmt.Println("auth =", values[1].Native().(string))  // matches to name
```

Is there something broke or a is there a concept I'm not understanding with how Has() works?

Thanks

**Comment by dennwc** [comment]
It is not guarantied that Iterate order is stable. It may return items in any order depending on how backend handles the query.
Out argument are meant to be equal, thus this query means traverse "name" or "authed_by" in any order.
If you want to simply save values on each of these predicates, use Save.
If you want to traverse but distinguish between predicates later, use OutWithTags.

**Comment by kris-runzer** [comment]
Just making sure I understand this; is this what you meant?

```
p := cayley.StartPath(qs, quad.String("a")).
	Has("type", quad.String("organization")).
	Save("name", "name").
	Save("authed_by", "authed_by")

_ = p.Iterate(nil).TagValues(qs, func(m map[string]quad.Value) {
	name "= m["name"].Native().(string)
        authedBy := m["authed_by"].Native().(string)

        ....
})
```

**Comment by dennwc** [comment]
Correct

**Comment by kris-runzer** [comment]
Awesome.  Thanks for the help!
