### ISSUE TITLE
Unable to install in Mac

### ISSUE THREAD

**Issue by mukteshkrmishra** [cayleygraph/cayley#479]
Hi I am trying to install Cayley in Mac.

I followed the steps provided in:
http://oren.github.io/books/cayley/010_foundations/install.html

However when I try to execute executable I got following error:
 /usr/local/bin/cayley 
-bash: /usr/local/bin/cayley: cannot execute binary file

I changed permission also for cayley executable still got the same error.

Please help.

**Comment by dennwc** [comment]
Hi @mukteshkrmishra,

I'm not sure why this error may happen. Are you sure that Cayley binary corresponds to your OS/architecture? I cannot think of another reasons of why it might happen.

**Comment by oren** [comment]
The instruction above are for installing Cayley from source.
 I believe that the recommended way to install Calyey (at least the stable version) is to download the binary from here: https://github.com/cayleygraph/cayley/releases

@dennwc please correct me if i am wrong

**Comment by pbsladek** [comment]
@mukteshkrmishra brew worked fine for me. brew install cayley

**Comment by dennwc** [comment]
Considering resolved
