### ISSUE TITLE
Building cayley: "use of internal package not allowed"

### ISSUE THREAD

**Issue by tamethecomplex** [cayleygraph/cayley#485]
Hi,

I am trying to build cayley using the build instructions at "https://github.com/cayleygraph/cayley/blob/master/docs/Contributing.md".  I am on go v 1.7.

When performing the build step, I get these 4 package import errors, all with "use of internal package not allowed":

**$ go build ./cmd/cayley**
package ./cmd/cayley
        imports github.com/cayleygraph/cayley/internal: use of internal package not allowed
package ./cmd/cayley
        imports github.com/cayleygraph/cayley/internal/config: use of internal package not allowed
package ./cmd/cayley
        imports github.com/cayleygraph/cayley/internal/db: use of internal package not allowed
package ./cmd/cayley
        imports github.com/cayleygraph/cayley/internal/http: use of internal package not allowed

What am I doing wrong?

**Comment by dennwc** [comment]
Hi @tamethecomplex,

I suspect there is something wrong with vendor directory. Please check if it contains Cayley already.
I heard of the similar problem when project directory already contained vendor directory with the same project.

**Comment by tamethecomplex** [comment]
Hi @dennwc ,

That was it!  I had a version of cayley installed globally at %GOPATH%/src/github.com/cayley.  I deleted the globally installed version, re-ran "go build ./cmd/cayley", and the binary built / tested successfully.  Thanks for your help.
