### ISSUE TITLE
loading quad causes an unexpected parse error.

### ISSUE THREAD

**Issue by hgztheyoung** [cayleygraph/cayley#488]
cayley_v0.6.0_windows_amd64>cayley init -config=cayley.cfg.wikidata -quads=data\wikidata-simple-statements.nt -ignoredup

`
E1105 11:06:15.476609    3468 cayley.go:301] failed to parse "<http://www.wikidata.org/entity/Q2120110> <http://www.wikidata.org/entity/P646-freebase> <http://rdf.freebase.com/ns/HARDAH MUNICIPALITY HOSPITAL> .": invalid N-Quad: unexpected rune 'H' at 137
`

it seems that <http://rdf.freebase.com/ns/HARDAH MUNICIPALITY HOSPITAL> is parsed as <http://rdf.freebase.com/ns/HARDAH(object)  MUNICIPALITY(Label) and HOSPITAL becomes an error.

**Comment by kortschak** [comment]
I would say working as intended. That is not a valid n-quad. You could percent-encode the space to fix it.

**Comment by hgztheyoung** [comment]
Is there a configuration to ignore this line and deal with the rest?
I didn't figure out how to percent-encode my data for now......
Since it's my problem, I will close this issue later.
Thanks for your reply.

**Comment by ZChristine** [comment]
i have the same problem too, have you ever solved it

**Comment by dennwc** [comment]
@ZChristine Can you provide more details?

**Comment by ZChristine** [comment]
cayley.exe http -i ./data/statements.nq -d memstore --host=:64210
db: failed to load data: failed to parse "<http://www.semanticweb.org/dezh/ontologies/disease#Bladder neck contracture> <http://www.semanticweb.org/dezh/ontologies/disease#hasAlias> <http://www.semanticweb.org/dezh/ontologies/disease#contracture of vesical neck> .": invalid N-Quad: unexpected rune 'v' at 188
It seemed that if there were not other symbols , just spaces between words, it will fail to parse the data.I have tried percent-code to clean the nq file but the conditions needed to consider are too much, so I wonder if there was another way to fix it

**Comment by ZChristine** [comment]
@dennwc

**Comment by dennwc** [comment]
The quad is definitely invalid and doesn't conform to the NQuads standard.

But if you are familiar with Go, you can use our NQuads reader in "raw" mode - it will accept this kind of quads and you can programmatically change them to IRIs to get the correct file. Let me know if this way works for you. If not, I can provide a binary that does the conversion.

**Comment by ZChristine** [comment]
Actually I have not used go before. So if you could offer a binary that does the conversion, it would be really thankful. @dennwc
