### ISSUE TITLE
Gizmo: accumulate results in map()

### ISSUE THREAD

**Issue by jasondouglas** [cayleygraph/cayley#49]
Other finals seem to work fine.  For example this works:

```javascript
g.Emit({
    "films" : g.V().Has("/film/film/directed_by", director_id).TagArray()
});
```
But this gets: `{"error" : "(anonymous): Line 6:1 Unexpected token } (and 3 more errors)"}`
```javascript
g.Emit({
    "films" : g.V().Has("/film/film/directed_by", director_id).ForEach(function(d){
      return d;
    });
});
```

... or any other variation of function body (like a nested g.Emit());

You might wonder what I'm trying to do... it's format an entire tree.  g.Emit() seems to be the only way to do optional fields in an object, so I was trying to figure out how to nest that.

**Comment by dennwc** [comment]
There is no error on HEAD for first example.
Will implement accumulation a bit later.

**Comment by iddan** [comment]
Correction: `.forEach()` shouldn't accumulate results, `.map()` should.

**Comment by iddan** [comment]
Closing this as #878 will not include steps that accept a function.
