### ISSUE TITLE
Can't authenticate with discourse.cayley.io

### ISSUE THREAD

**Issue by tamethecomplex** [cayleygraph/cayley#491]
Hi,

I am trying to join your online community but am having issues.  I tried authenticating with Github but get the below message.  I also tried signing up with a plain email address, but I don't receive the confirmation email (even in the spam folder).  I was wondering if anyone else also has this issue?

![image](https://cloud.githubusercontent.com/assets/17109209/20140709/ace5ba6a-a65a-11e6-8c9f-e99e6179bcb7.png)

**Comment by dennwc** [comment]
Yes, we had a similar report few days ago. This issue is related to Discourse upgrade. @robertmeta is working on rollback to stable version.

**Comment by tamethecomplex** [comment]
Ok, thanks!

**Comment by dennwc** [comment]
Should be fixed now. @tamethecomplex Please try to register again.

**Comment by tamethecomplex** [comment]
It worked this time, thanks!
