### ISSUE TITLE
`cayley http` read-only by default

### ISSUE THREAD

**Issue by why-toblerone-why** [cayleygraph/cayley#495]
When starting `cayley http`, the instance should be read-only by default unless a flag has been set explicitly.

**Comment by dennwc** [comment]
Makes sense. If everyone thinks it's a good idea, I'll change the default value for in #492.

**Comment by dennwc** [comment]
On a second though it seems confusing. Some people import data via http interface and it's not obvious that you need should pass `--ro=false` flag. Let's leave it RW by default.
