### ISSUE TITLE
Transversing a tree in Cayley

### ISSUE THREAD

**Issue by tonyalaribe** [cayleygraph/cayley#496]
How do you walk an entire tree in cayley to generate json? Without looping and making multiple requests at each level? Especially for a tree that could go as far as 8 levels, with each node having one to 100 children? I'm using a remotely hosted mongodb database, so keeping requests down would be nice.

I'm using cayley as a library, but converting a gremlin query to golang code shouldnt be an issue.

**Comment by dennwc** [comment]
Give a try to #475, it might be merged soon. For now, it will make all these requests. But it will get better over time, as we optimize each backend for such queries.

**Comment by tonyalaribe** [comment]
Thanks @dennwc for the quick reply, though i still have no idea how to user the layer to walk entire trees.

**Comment by dennwc** [comment]
Assuming you want to load all items via `<isChildOf>` link:
```Go
type Item struct{
   ID quad.Value `quad:"@id"`
   Childred []Item `quad:"isChildOf < *"`
}

var items []Item
err = schema.SaveTo(nil, qs, &items, quad.IRI("start_node"))
```

**Comment by dennwc** [comment]
@tonyalaribe continuing our IRC discussion:

You are writing quads this way:
```Go
var user, parent string
err = store.AddQuad(quad.Make(user, quad.IRI("isChildOf"), parent, nil))
```
So `user` and `parent` becomes `quad.String`.

And then query them as:
```Go
err = schema.SaveTo(nil, qs, &items, quad.IRI("some_user"))
```
But, again, Cayley forces strict type checks now, thus `quad.String(user)` will be different from `quad.IRI("some_user")`. So please change all node IDs to be IRIs (preferable), or change the query to start from `quad.String("some_user")`.

**Comment by tonyalaribe** [comment]
Thanks @dennwc . It finally works. I have updated the gist with the code that works.

https://gist.github.com/tonyalaribe/e82838a32a2d677a726c7f2ade228838

**Comment by tonyalaribe** [comment]
@dennwc I still have a bit of an issue.  While the tree structure is maintained in the results, it seems nodes with no children have an ID of null.  So, i'm only able to see parent nodes.

I updated the gist to show the json result, and the test function. 

https://gist.github.com/tonyalaribe/e82838a32a2d677a726c7f2ade228838

**Comment by dennwc** [comment]
The code is different from the log output - it has no Name field for an Item struct, for example. Please update it.

Also, addToTree function writes an additional parent-isChildOf->child relationship for some reason.

**Comment by tonyalaribe** [comment]
Hello @dennwc 

Sorry about that. I have updated the gist to the actual code in use.

**Comment by tonyalaribe** [comment]
https://gist.github.com/tonyalaribe/e82838a32a2d677a726c7f2ade228838

**Comment by dennwc** [comment]
```Go
type Item struct{
   Name     quad.Value `quad:"name < *"`
}
```
Name can be changed from reverse to forward traversal. Also, it can be of string type:
```Go
type Item struct{
   // ...
   Name     string `quad:"name"`
}
// quad should be reversed, and name conversion can be omitted because it's a string already
err = store.AddQuad(quad.Make(quad.IRI(user), quad.IRI("name"), name, nil))
```
It seems that there is a bug in slice handling. Try adding "optional" tag, it should work:
```Go
type Item struct{
   // ...
   Children []Item     `quad:"isChildOf < *,optional"`
}
```

**Comment by tonyalaribe** [comment]
It works now. Thanks.

**Comment by tonyalaribe** [comment]
How do i get the total number of nodes using this method? Without walking the returned object. Or is that the only way?

**Comment by dennwc** [comment]
If you already received the tree, you already know a total number of nodes. 
You want to get a total number of all users, or the number of users in this tree? If the later, we'll need to merge #470 first.

**Comment by tonyalaribe** [comment]
I meant to get the number of users within the tree. It seems #470 has been open since September.

**Comment by dennwc** [comment]
Okay, then you definitely need to wait for that PR. We will merge it in two weeks at most.

**Comment by tonyalaribe** [comment]
Looking forward to it
