### ISSUE TITLE
Shadow Caylay Github project?

### ISSUE THREAD

**Issue by romansky** [cayleygraph/cayley#497]
When searching for a Docker image for Caylay I stumbled on this:
http://cayleydb.github.io/
Doesn't appear to be official Caylay project site, still looked that way until a closer inspection..

**Comment by dennwc** [comment]
Looks like a blog about Cayley hosted as GitHub pages. I don't see anything that we can or should do about it. So closing this.
Feel free to reopen if you have any suggestions.
