### ISSUE TITLE
Decouple web interface from database

### ISSUE THREAD

**Issue by arriba-arriba-el-gongolero** [cayleygraph/cayley#500]
Having the web interface mixed with the database source code is quite confusing. I'm pretty sure at least 2 directories are for the web interface, `static/` and `templates/`; I don't know/understand if there are other.

Would it be possible to separate all the code for the web interface from the database code, for example in a single sub-directory or on a different repository completely? This should also make it easier to plug in different interfaces at will; for example you can ship cayley with a minimalist one by default, and let people replace this code with another interface if they prefer.

**Comment by dennwc** [comment]
I agree that having separate directories for web interface is confusing. And yes, we will decouple API and web interface server to separate packages later.

**Comment by iddan** [comment]
The new frontend will be separated correctly.
