### ISSUE TITLE
Replace CDN libraries with local files

### ISSUE THREAD

**Issue by arriba-arriba-el-gongolero** [cayleygraph/cayley#501]
The [current web interface](https://github.com/cayleygraph/cayley/blob/master/templates/head.tmpl) retrieves some files from remote, 3rd party CDNs. For example from googleapis.com and cloudflare.com. **This is not** a good design decision for a series of reasons, most notably concerning users privacy and security.
These files should be replaced with local copies served from the `static/` folder.

**Comment by dennwc** [comment]
Yes, we should embed these dependencies at least in a release build. But not a priority right now.
