### ISSUE TITLE
Cayley against MongoDB HTTP delete API doesn't really work

### ISSUE THREAD

**Issue by lnshi** [cayleygraph/cayley#517]
In the built-in UI page `http://localhost:64210/ui/write`, do single write:
```
Subject   -> </user/shortid/23TplPdS>
Predicate -> <userId>
Object    -> 23TplPdS
Label     -> companyA
```

Then check the MongoDB by running `db.nodes.find()`, I got:
```
mongos> db.nodes.find()
{ "_id" : "c509af0208b646e01695a7c270977407d8f1ef5e", "Name" : { "val" : "/user/shortid/23TplPdS", "iri" : true }, "Size" : 1 }
{ "_id" : "b7d703ca4c0a8f7df776f77eb81bcea5f75360cd", "Name" : { "val" : "23TplPdS" }, "Size" : 1 }
{ "_id" : "2b0a40170d82e2e506c20d56db10d9dbfda9c51c", "Name" : { "val" : "userId", "iri" : true }, "Size" : 1 }
{ "_id" : "87173f776f1eea566c0981f86a5ccb77059bbf33", "Name" : { "val" : "companyA" }, "Size" : 1 }
```

Then tried to delete with the exactly same filling in the `Remove a quad` field, then check the MongoDB, the exactly same data are still there:
```
mongos> db.nodes.find()
{ "_id" : "c509af0208b646e01695a7c270977407d8f1ef5e", "Name" : { "val" : "/user/shortid/23TplPdS", "iri" : true }, "Size" : 0 }
{ "_id" : "b7d703ca4c0a8f7df776f77eb81bcea5f75360cd", "Name" : { "val" : "23TplPdS" }, "Size" : 0 }
{ "_id" : "2b0a40170d82e2e506c20d56db10d9dbfda9c51c", "Name" : { "val" : "userId", "iri" : true }, "Size" : 0 }
{ "_id" : "87173f776f1eea566c0981f86a5ccb77059bbf33", "Name" : { "val" : "companyA" }, "Size" : 0 }
```

Also tried to fill in without the `greater than sign >` and the `less than sign <`, still same result.

Also tried to call the API directly in Postman, with or without the `greater than sign >` and the `less than sign <`:
```
[
	{
		"subject": "/user/shortid/23TplPdS",
		"predicate": "userId",
		"object": "23TplPdS",
		"label": "companyA"
	}
]
```
get back response `{"result": "Successfully deleted 1 quads."}`, but checked the MongoDB, still same result, the exactly same data are still there.

What is going wrong? or the 'delete' is designed just modifying some kind of tags, will not really delete the data?

**Comment by dennwc** [comment]
You may notice that Size attribute (ref-count) for node becomes zero after deletion. And the quad should be removed as well. Cayley also preserves a log of all operation, so you will still find quad in log, if you look at stored data. In all these cases queries inside Cayley should skip these values.

But yes, this an issue, it should remove nodes with zero ref count.

**Comment by lnshi** [comment]
Ok, so in version v0.6.1 the nodes with 0 ref count will all get removed?

One more question regarding the deletion: is that if I inserted the N-Quads data with `label` then when I want to delete it I must also provide the `label`? That is how Cayley actually deal with the `label`(subgraph)?

If I inserted with `label`, but not provide when delete, will coz any problem, like orphan garbage data?

**Comment by dennwc** [comment]
@lnshi Yes, they will be removed properly.

If label is specified, then delete should also mention label, or quad will not be removed at all.

**Comment by lnshi** [comment]
Ok, when 0.6.1 is out i will do the test and come back to close this issue.
