### ISSUE TITLE
'/write/file/nquad' when error happens doesn't return valid JSON format response body

### ISSUE THREAD

**Issue by lnshi** [cayleygraph/cayley#523]
One of the error response body is:

```
{"error" : "add </user/shortid/23TplPdS> -- <userId> -> "23TplPdS": quad exists"}
```

Cannot be `JSON.parse` parsed.

**Comment by dennwc** [comment]
Thanks for the report. It should be fixed in #521 for both old and new API.

**Comment by dennwc** [comment]
Fixed

**Comment by lnshi** [comment]
@dennwc thanks for notifiying, just pulled the latest docker image from [Quary](https://quay.io/repository/cayleygraph/cayley?tag=latest&tab=tags) and run the test cases, seems `/api/v1/write` still returns invalid JSON response(`{ result: 'Successfully wrote 11 quads.' }`), but `/api/v2/write` seems fine, I guess I will just do the v2 APIs and enforce users to use the v2 APIs.
