### ISSUE TITLE
ToValue() not return string as expected, but a characters Array.

### ISSUE THREAD

**Issue by lnshi** [cayleygraph/cayley#524]
As test case [query.ToValue() line:170](https://github.com/lnshi/node-cayley/blob/master/test/apis/callback.js), the response is:

```
{ result:
   [ '<',
     '/',
     'u',
     's',
     'e',
     'r',
     '/',
     's',
     'h',
     'o',
     'r',
     't',
     'i',
     'd',
     '/',
     '4',
     '6',
     'J',
     'u',
     'z',
     'c',
     'y',
     'x',
     '>' ] }
```

Expect response is a string.

**Comment by dennwc** [comment]
`ToValue` returns one result as JS value by definition. Test tries to iterate over this string and returns separate characters. Thus, Gizmo does exactly what you asked it to do.

**Comment by lnshi** [comment]
oh, right, got it, thanks, will do the necessary adjustment to the test case.
