### ISSUE TITLE
Timeout error in production, on an app running in dokku

### ISSUE THREAD

**Issue by tonyalaribe** [cayleygraph/cayley#526]
Good day,

I have an application running with cayley and a mongo db backend. The app runs very well locally, but in production the queries run until nginx issues a time out error. 

```
func AddToTree(name, user, parent string) error {
	c := config.Get()
	// Initialize the database
	graph.IgnoreDuplicates = true
	err := graph.InitQuadStore("mongo", c.MONGOSERVER, nil)
	if err != nil {
		log.Println(err)
	}
	
	store, err := cayley.NewGraph("mongo", c.MONGOSERVER, nil)
	if err != nil {
		log.Println(err)
		return err
	}
	defer store.Close()

	err = store.AddQuad(quad.Make(quad.IRI(user), quad.IRI("isChildOf"), quad.IRI(parent), nil))
	if err != nil {
		log.Println(err)
		return err
	}

	err = store.AddQuad(quad.Make(quad.IRI(user), quad.IRI("name"), name, nil))
	if err != nil {
		log.Println(err)
		return err
	}

	return nil
}

```

Where  c.MONGOSERVER (dbpath) is something like mongodb://dbname:password@dokku-mongo-entrenet:27017/dbname

Is it possible that my dbpath isnt in the right format?

**Comment by dennwc** [comment]
We use `mgo` driver for MongoDB, and according to [docs](https://godoc.org/gopkg.in/mgo.v2#Dial) your address format is correct.

I'll need more information for this issue. First of all, make sure that MongoDB host (`dokku-mongo-entrenet`) is accessible from that machine.

**Comment by tonyalaribe** [comment]
The dbpath is accessible, since I also use the database for other storage purposes. And those are not affected.   When I call the AddToTree function in production, it runs for a few minutes, before I get a timeout error

**Comment by tonyalaribe** [comment]
I logged each function call, to know where the function stops excecuting, and it seems it stops at 
``
err := graph.InitQuadStore("mongo", c.MONGOSERVER, nil)
	if err != nil {
		log.Println(err)
	}
``

I really wonder what I'm getting wrong, since the same db path is being used for other db requests

**Comment by tonyalaribe** [comment]
Is it possible to pass in a mongodb session for a specific database, for cayley to use? so instead of passing database paath, I just give it the session? Also, what are the possible values for graph.Options? It just appears as a map[string]interface{}. Can the session be passed through it? Thanks.

**Comment by tonyalaribe** [comment]
I fixed the issue by passing a session into graph.Options.

``
c := config.Get()
	// Initialize the database

	opts := graph.Options{}
	opts["session"] = c.MongoSession.Copy()
	graph.IgnoreDuplicates = true
	err := graph.InitQuadStore("mongo", c.MONGOSERVER, opts)
	if err != nil {
		log.Println(err)
	}
	opts = graph.Options{}
	opts["session"] = c.MongoSession.Copy()

	store, err := cayley.NewGraph("mongo", c.MONGOSERVER, opts)
	if err != nil {
		log.Println(err)
		return err
	}
	defer store.Close()
``

But this is just a work around. There has to be something wrong with the way the db path url is parsed.

**Comment by dennwc** [comment]
Should be fixed now
