### ISSUE TITLE
It seems 'tags' doesn't work properly for 'path.Both([predicatePath], [tags])'

### ISSUE THREAD

**Issue by lnshi** [cayleygraph/cayley#532]
It seems 'tags' doesn't work properly for `path.Both([predicatePath], [tags])`, refer the test case here [path.Both([predicatePath], [tags]): line 493](https://github.com/lnshi/node-cayley/blob/master/test/apis/callback.js), which the res will be:

```
{ result: [ { id: '</user/shortid/23TplPdS>' } ] }
```

no tag there.

**Comment by dennwc** [comment]
@lnshi Thanks for your report!
