### ISSUE TITLE
Go Test in GAE datastore reports no test files

### ISSUE THREAD

**Issue by jzhu077** [cayleygraph/cayley#539]
When I run go test in 
```
cayleygraph/cayley/graph/gaedatastore 
```
It outputs
```
?   	github.com/cayleygraph/cayley/graph/gaedatastore	[no test files]
```

**Comment by dennwc** [comment]
@jzhu077 GAE files contain `// +build appengine appenginevm` directive, thus you'll need to specify these build tags to run tests for it.

**Comment by jzhu077** [comment]
@dennwc Thanks for your prompt reply. I am new to Cayley will you be able to guide me though these settings? eg what command should I run to set the build tags if I have the following emulator environment
```
export DATASTORE_DATASET=myapp-158821
export DATASTORE_EMULATOR_HOST=localhost:8541
export DATASTORE_EMULATOR_HOST_PATH=localhost:8541/datastore
export DATASTORE_HOST=http://localhost:8541
export DATASTORE_PROJECT_ID=myapp-158821
```

**Comment by dennwc** [comment]
@jzhu077 You can run the same go commands, but with `-tags appengine`. For example `go test -tags appengine ./cayleygraph/cayley/graph/gaedatastore`. Same for any other go command command.
