### ISSUE TITLE
MySQL connection example/docs

### ISSUE THREAD

**Issue by mpmlj** [cayleygraph/cayley#540]
Hi,

Could you please provide documentation/example connecting to a MySQL back-end from from Cayley library?
I can connect to PostgreSQL without problems, however, when trying to replace a connection string to MySQL, driver throws errors as if it cannot connect to PostgreSQL, ex.:

````Go
path := "mysql://root:root@127.0.0.1:3306/cayley?charset=utf8"

	graph.InitQuadStore("sql", path, nil)

	// Create a brand new graph
	store, err := cayley.NewGraph("sql", path, nil)
	if err != nil {
		log.Fatalln(err)
	}
````

will throw: "ERROR: Couldn't open database at mysql://root:root@127.0.0.1:3306/cayley?charset=utf8: &errors.errorString{s:"pq: SSL is not enabled on the server"} "

Please advise.

P.S.
From you experience, between MySQL and PostgreSQL, what database would you advise for Cayley back-end and why?

Thank you!!
D

**Comment by mpmlj** [comment]
OK. Found an approach that seems to be working:
1. Need to set flavor in the options.
2. Connection string needed an update.

````Go
	path := "root:root@/cayley?charset=utf8"

	opt := graph.Options{}
	opt["flavor"] = "mysql"
	graph.InitQuadStore("sql", path, opt)

	store, err := cayley.NewGraph("sql", path, opt)
	if err != nil {
		log.Fatalln(err)
	}
````

Could you please confirm that this is a correct approach?

Thanks
D

**Comment by dennwc** [comment]
Hi @mpmlj,

Yes, in order to use other SQL implementations you need to specify flavor option. And yes, connection string should also be changed according to one supported by SQL driver for that flavor.

If I remember correctly, Postgres was faster than MySQL in our integration benchmarks.

**Comment by mpmlj** [comment]
Thank you, @dennwc !
