### ISSUE TITLE
non ascii quad support

### ISSUE THREAD

**Issue by zhouhoo** [cayleygraph/cayley#544]
**Description**
can cayley support import non ascii quad data?
I recently use cayley to store and query Chinese knowledge graph  using  the quad format as testdata.nq ,like this:
萨德 不属于 韩国 .

load process work fine, but in my postgres database, all the data is store in the form  like Unicode, and value_string field is empty ,which is different from the example.

so what is the problem?

**Steps to reproduce the issue:**
just as the doc example.
**Received results:**

```
(program output or server response)
```
|       value        | value_string | datatype | language | iri | bnode | value_int | value_bool | value_float | value_time 
--------------------------------------------+--------------------+--------------+----------+----------+-----+-------+-----------+------------+-------------+------------
 \x34f201bc507e33caaef736de328bf041234d1138 | \x0a03e68891       |              |          |          |     |       |           |            |             | 
 \x3941fd46c1009302ae81635a62cee5d3686643ee | \x0a06e5b19ee4ba8e |              |          |          |     |       |           |            |             | 

**Expected results:**
|       value        | value_string | datatype | language | iri | bnode | value_int | value_bool | value_float | value_time 
--------------------------------------------+--------------------+--------------+----------+----------+-----+-------+-----------+------------+-------------+------------
 \x34f201bc507e33caaef736de328bf041234d1138 | 萨德       |              |          |          |     |       |           |            |             | 
 \x3941fd46c1009302ae81635a62cee5d3686643ee | 韩国 |              |          |          |     |       |           |            |             | 

**Output of `cayley version` or commit hash:**

```
(paste your output here)
```

**Environment details:**

Backend database: `(database and version)`
postgres 9.7

**Comment by dennwc** [comment]
Hi @zhouhoo,

Can you please also provide a sample nquads file for your case? You may also try escaping nquads literals.

**Comment by dennwc** [comment]
I will assume quads were not escaped properly. Feel free to reopen in other case.
