### ISSUE TITLE
Locked Postgres connections

### ISSUE THREAD

**Issue by steffansluis** [cayleygraph/cayley#545]
At some point, the Postgres backend will fail with `sql_iterator.go:361] Couldn't get cursor from SQL database: pq: too many connections for role`. This has happened to me consistently over the past few days after executing a bunch of GraphQL queries (manually), some of which fail, some of which return a lot of data. 

Unfortunately, I'm not sure what causes the issue, but shortly before the issue presented itself most recently, I got the error `quadstore.go:466] Couldn't execute value lookup: sql: no rows in result set` a few times. In any case, the result of whatever is breaking is a Postgres that is locked, causing a build up of connections that eventually reaches the connection limit, causing Cayley to start retuning `null` results for all queries.

If I can help narrow it down, please let me know. I'm sorry I couldn't be more specific but I've been testing pretty much all aspects of both the GraphQL and the Gizmo API, so it's difficult to say what exactly causes the connection to freeze.

**Comment by dennwc** [comment]
@steffansluis Thanks for report! It seem like some iterator is not closed properly in GraphQL. I'll try to locate it, and if I can't we should narrow the case down.

**Comment by dennwc** [comment]
Should be fixed in master. Feel free to reopen if problem remains.
