### ISSUE TITLE
Speed: Gizmo vs GraphQL

### ISSUE THREAD

**Issue by steffansluis** [cayleygraph/cayley#556]
So, I've played around with both of these quite a lot, and it seems to me that GraphQL is faster than Gizmo. Furthermore, Gizmo response times seem to be quite unpredictable as well. Executing the same query multiple times can result in a range of response times from 1 to 5 seconds. Is there something obvious I'm missing? Do Gizmo queries just not scale well for some reason?

In any case, I just wanted to get the question out there, I can provide some actual examples but I don't have them handy right now. I also understand that Gizmo and GraphQL might serve different use cases, but even so, Gizmo seems to be slower at what should essentially be the same traversal.

**Comment by barakmich** [comment]
That's almost certainly the case; Gizmo provides a full JS environment, which can be overkill for relatively straightforward traversals. The GraphQL endpoint is just the necessary parser.

Both build the same structures (iterator trees) underneath to actually perform the query, but one has a lot more overhead.

That it ranges from 1 to 5 seconds, however, suggests something is strange -- it shouldn't vary that wildly. Do you have an example query we can look at?

**Comment by steffansluis** [comment]
@barakmich Sorry for my long silence. Will look into this further soon.

**Comment by dennwc** [comment]
Needs to be checked on v0.7

**Comment by iddan** [comment]
Hey @steffansluis, do you observe the same latency on the latest releases?

**Comment by iddan** [comment]
Closing for no response. @steffansluis if the issue persists on the latest releases please comment and we'll reopen the issue.
