### ISSUE TITLE
Consider evaluating BuntDB over BoltDB

### ISSUE THREAD

**Issue by jzelinskie** [cayleygraph/cayley#582]
[BuntDB](https://github.com/tidwall/buntdb) is a similar API to BoltDB, but allows for custom indexes. I'm sure these could be used for great performance benefit when storing quads.

**Comment by barakmich** [comment]
I looked it over. While the custom indexes are a cool trick, they're not a
benefit, as far as I can see. Yeah, this means we're doing a bit more by
hand, but we also get to do it minimally. And using strings for all KVs is
an odd API choice -- useful if you're just trying to persist something,
maybe not for extending the DB, which is what we're doing, more or less.

That said, I welcome someone to measure it.
