### ISSUE TITLE
UI: usability

### ISSUE THREAD

**Issue by dennwc** [cayleygraph/cayley#598]
- [x] format results automatically
- [x] show spinner when the query is in progress
- [ ] allow to save queries
- [ ] send query on Ctrl-Enter or Shift-Enter

_(marked items are done in a new UI)_

**Comment by iddan** [comment]
`Cmd + Enter` works in the new (in progress) UI https://cayley-ui.netlify.com/

**Comment by iddan** [comment]
Tracked on [Cayley Web](https://github.com/cayleygraph/web/issues)
