### ISSUE TITLE
Accumulo backend

### ISSUE THREAD

**Issue by jsmorph** [cayleygraph/cayley#6]
I'm interested in using [Accumulo](https://accumulo.apache.org/) as a back end.  Opinions?  Should be relatively easy since Accumulo presents an API similar to LevelDB.  Then you'd have pretty decent horizontal scalability (with the usual caveats re graphs, round trips, etc).

**Comment by robertmeta** [comment]
Moving this to our feature request discussion area: https://discourse.cayley.io/t/accumulo-storage-engine/194
