### ISSUE TITLE
Remove `Size()` from the iterator interface, use `Stats()`

### ISSUE THREAD

**Issue by barakmich** [cayleygraph/cayley#611]
Since `Stats()` contains the `Size()` information, let's use that one instead. 

This may cost more; `Stats()` *may* talk to a backend. So maybe a `quick` flag or similar makes sense.

Thoughts?

**Comment by dennwc** [comment]
I think of two more alternatives:
1. Add a parameter to Size to set an expected type (exact, estimate, wild guess).
2. Remove Size, but make a separate argument to Stats that specifies what fields to return in that struct.
