### ISSUE TITLE
GraphQL: directive to support LabelContext morphism

### ISSUE THREAD

**Issue by steffansluis** [cayleygraph/cayley#614]
So I was thinking, right now there is not really a way to restricts GraphQL queries to a specific subgraph (right?). I looked through the code a bit ([/query/graphql/graphql.go](https://github.com/cayleygraph/cayley/blob/61125879b57ebd2277876ed95fffd244fc4bf8df/query/graphql/graphql.go) and [graph/path/path.go](https://github.com/cayleygraph/cayley/blob/aba38b3804454f6e0bf712442c42621b2011b2a2/graph/path/path.go)), and it seems pretty easy to add a new directive that executes the `LabelContext` morphism on the path object. Any thoughts on this?

**Comment by dennwc** [comment]
Yes it should be easy enough. But what exactly you want to filter? Only current object's properties, or all of them recursively?

**Comment by steffansluis** [comment]
I would think it works similarly to the way the labels work in Gizmo, where you restrict a part of your query to a particular sub-graph. The GraphQL directive would work in a similar way as `@opt` except it would have the labels as arguments. The underlying code would just call `LabelContext` on the path with the labels provided through the directive. So only the sub-query labeled with the directive is filtered.

**Comment by dennwc** [comment]
But you expect `@label` to propagate into the property, right?

For example, should inner "name" be affected by `LabelContext` or not?

```graphql
{people{
   name
   follows @label("fb") {
      name
   }
}}
```

**Comment by steffansluis** [comment]
Yes. The inner name would be affected. I think this would also be valid (Getting the google status of all your facebook followers).
```graphql
{people{
   name
   follows @label("fb") {
      name,
      status @label("google")
   }
}}
```

**Comment by steffansluis** [comment]
I suppose what follows is that calling `@label` with arguments would set the labelcontext back to the entire graph

**Comment by dennwc** [comment]
Done, check [GraphQL.md](https://github.com/cayleygraph/cayley/blob/master/docs/GraphQL.md)
