### ISSUE TITLE
fail to build cayley in china

### ISSUE THREAD

**Issue by gzliudan** [cayleygraph/cayley#623]
**Description**

**Steps to reproduce the issue:**
1. mkdir -p ~/cayley && cd ~/cayley
2. export GOPATH=`pwd`
3. export PATH=$PATH:~/cayley/bin
4. mkdir -p bin pkg src/github.com/cayleygraph
5. cd src/github.com/cayleygraph
6. git clone https://github.com/cayleygraph/cayley
7. cd cayley
8. curl https://glide.sh/get | sh
9. glide install

**Received results:**

```
[INFO]  --> Fetching github.com/tylertreat/BoomFilters.
[INFO]  --> Fetching golang.org/x/net.
[INFO]  --> Fetching golang.org/x/sys.
[INFO]  --> Fetching golang.org/x/text.
[INFO]  --> Fetching google.golang.org/appengine.
[INFO]  --> Fetching gopkg.in/mgo.v2.
[INFO]  --> Fetching gopkg.in/yaml.v2.
[WARN]  Unable to checkout golang.org/x/sys
[ERROR] Update failed for golang.org/x/sys: Cannot detect VCS
[WARN]  Unable to checkout golang.org/x/net
[ERROR] Update failed for golang.org/x/net: Cannot detect VCS
[WARN]  Unable to checkout golang.org/x/text
[ERROR] Update failed for golang.org/x/text: Cannot detect VCS
[WARN]  Unable to checkout google.golang.org/appengine
[ERROR] Update failed for google.golang.org/appengine: Cannot detect VCS
[ERROR] Failed to install: Cannot detect VCS
Cannot detect VCS
Cannot detect VCS
Cannot detect VCS
```

**Environment details:**
OS: centos 7.3
golang: 1.8.3

**Comment by dennwc** [comment]
It's not directly related to Cayley.
Try following these steps for each dependency that cannot be downloaded directly:
https://github.com/northbright/Notes/blob/master/Golang/china/get-golang-packages-on-golang-org-in-china.md
