### ISSUE TITLE
Allow custom limit for FollowRecursive() recursion depth

### ISSUE THREAD

**Issue by danbo** [cayleygraph/cayley#624]
ie with 

g.V('vertex').FollowRecursive(g.M().Out('child')).All()

there is currently no way to limit the recursion depth.

Perhaps we could add an optional second parameter for this, ie

g.V('vertex').FollowRecursive(g.M().Out('child'), 5).All()

for a maximum child depth of 5.

Original discussion here: https://discourse.cayley.io/t/followrecursive-parent/912/4

**Comment by dennwc** [comment]
@phyrwork Thanks! Closing.
