### ISSUE TITLE
string/json encoding of quad values is confusing 

### ISSUE THREAD

**Issue by steffansluis** [cayleygraph/cayley#628]
I'm getting some weird results with the Gizmo API. When running a query like:
```
g.Emit(g.V("<http://myurl.org/blabla>")
	.Out("<http://schema.org/about>")
	.Limit(1) // Results in [{ id: \u003chttp://dbpedia.org/resource/Arithmetic_mean\u003e" }]
	.In("<http://schema.org/about>")
	.Count())
```
I get a the expected `"result":[88]`. When I try to get the count directly, I get `"result":[0]`.

```
g.Emit(g.V("\u003chttp://dbpedia.org/resource/Arithmetic_mean\u003e")
  	.In("<http://schema.org/about>")
  	.Count())
```

Even when I iterate, it breaks, resulting in `"result":[0]`:
```
  g.V("<http://myurl.org/blabla>")
  	.Out("<http://schema.org/about>")
  .Limit(1)
  .ForEach(function(e) {
    g.Emit(g.V(e.id)
  	.In("<http://schema.org/about>")
    	.Count());
  });
```

If necessary I can provide some data to reproduce, although the query should serve as a basic guide to how the data is structured. My best guess for now is that it has something to do with the difference between `<` and `\u003c`? I'm running a recent build of Cayley (built from a quay.io image yesterday) and the queries I'm running used to work on a previous version of Cayley (I can find out which with some effort if it helps).

Edit: Substituting `<` and `\u003c` either way doesn't seem to matter.

**Comment by dennwc** [comment]
Can't reproduce it on memory and Bolt. Can you please provide a minimal data sample and query for this issue?

**Comment by steffansluis** [comment]
The following quads seems to reproduce the problem for me:
```
<http://doc.com/things?q=abcd-1> <http://schema.org/about> "<http://dbpedia.org/resource/Arithmetic_mean>" .
<http://doc.com/things?q=abcd-2> <http://schema.org/about> "<http://dbpedia.org/resource/Arithmetic_mean>" .
<http://doc.com/things?q=abcd-3> <http://schema.org/about> "<http://dbpedia.org/resource/Arithmetic_mean>" .
<http://doc.com/things?q=abcd-4> <http://schema.org/about> "<http://dbpedia.org/resource/Arithmetic_mean>" .
<http://doc.com/things?q=abcd-5> <http://schema.org/about> "<http://dbpedia.org/resource/Arithmetic_mean>" .
```

with query:
```
g.Emit(g.V("<http://dbpedia.org/resource/Arithmetic_mean>")
	.In("<http://schema.org/about>")
	.Count())
```

yields `{"result":[0]}`.

The Cayley instance is running on a PostgreSQL DB and does contain other quads, although that shouldn't really affect the result. I wrote the quads using ` curl --fail -H "Content-Type: multipart/form-data" -XPOST -F NQuadFile=@seeds/cayley.nq ${my_actual_problematic_db_endpoint}/api/v1/write/file/nquad`. If this doesn't work I'll try to reproduce on a clean instance.

**Comment by dennwc** [comment]
In your example, you have a string literal instead of IRI in object. You have `"<http://dbpedia.org/resource/Arithmetic_mean>"`, but it should be `<http://dbpedia.org/resource/Arithmetic_mean>` (no quotes).

**Comment by steffansluis** [comment]
I see, that will probably fix my problem, but the behavior is the query is still not correct right?

**Comment by dennwc** [comment]
You mean the last reproducer or the first query? Last one behaves correctly. For the first one I'll need a new reproducer.

**Comment by steffansluis** [comment]
Ok, I think I understand. Because the object of the quads is a string, it's a valid output for the `.Out(about)` but not a valid input for the `.In(about)`. The behavior of the queries does makes sense, but it looks very strange because the IRI and the string version of the result look the same. Not sure what to do about that, but this does explain the behavior of the queries and solve my problem.

**Comment by dennwc** [comment]
It should work in both cases actually. I'm not sure why it happens with your query, so I'll need a real reproducer. In the last example that you provided it was an typo in the dataset (extra quotes).

**Comment by steffansluis** [comment]
So I didn't make a typo, I wrote the quads with quoted IRIs, which leads to the results looking the same as unquoted IRIs but behaving differently because they are different things. According to @dennwc, this is known to cause confusion and in the process of being addressed. Feel free to close this issue :smiley:.
