### ISSUE TITLE
please update Quickstart-As-Application.md

### ISSUE THREAD

**Issue by ec1oud** [cayleygraph/cayley#629]
The command line options have all changed so those instructions don't work as-is anymore.

**Comment by ec1oud** [comment]
Or is it the other way around: 0.6.1 (the release) is too old for these instructions now?

**Comment by dennwc** [comment]
Yes, our master branch tracks 0.7 release currently. Docs for 0.6.1 can be found [here](https://github.com/cayleygraph/cayley/tree/v0.6.1).
