### ISSUE TITLE
Higher-level Go API

### ISSUE THREAD

**Issue by barakmich** [cayleygraph/cayley#64]
Tracking for this discussion that keeps happening -- now it's got a number.

Basically, it'd be great to write queries (or, more explicitly, build iterator trees) without having to be so mechanistic in building the iterator trees. Exposing such an API makes it easier for people using Cayley as a library, makes it easier to write query languages (that have repeated patterns in a lot of places) and, perhaps, make it easier to talk about external API connections -- essentially, the wire format for building iterator trees. Which would allow interesting bindings for other languages without catting together Javascript. 

This may be directly related to the Gremlin API, in that one may influence the other and vice versa.

**Comment by flosse** [comment]
I hope that's the right place to ask:
Where can I find some introductions for using cayley as a library? Is there a hello world example? And do you know a real world example of a go application that's using cayley (no matter which API is used) ?

**Comment by iddan** [comment]
Documentation for using Cayley as a lib can be found here: https://github.com/cayleygraph/cayley/blob/master/docs/Quickstart-As-Lib.md.
As far as I understand this feature was resolved and can be closed. @robertmeta @dennwc

**Comment by dennwc** [comment]
@iddan Yes, I think we can close it. Most of it is implemented I believe. For everything else we have a more focused issues open.
