### ISSUE TITLE
ui: detached nodes in query shape visualizer

### ISSUE THREAD

**Issue by dennwc** [cayleygraph/cayley#642]
https://discourse.cayley.io/t/query-shape-result-different/980

**Comment by iddan** [comment]
This issue is resolved with the new UI:
When running:
```bash
./cayley http --load data/30kmoviedata.nq.gz
```
And executing:
```javascript
function getId(x) { return g.V(x).In("<name>") }
getId("The Shawshank Redemption").Out("</film/film/directed_by>").As("source").
In("</film/film/directed_by>").As("target").All()
```
It will yield the graph:
<img width="1792" alt="Screenshot 2019-12-17 at 00 31 56" src="https://user-images.githubusercontent.com/12671072/70948683-a6793080-2064-11ea-9882-d8e4c375afd3.png">
