### ISSUE TITLE
Gizmo: Filter a predicate value without tags

### ISSUE THREAD

**Issue by relvacode** [cayleygraph/cayley#650]
A common pattern for us is to follow a predicate link, filter a set of nodes and return to the original node set, like so:

    g.V().Tag("_n").Out("concentration_ng").Filter(gt(5)).Back("_n")

This is quite verbose and also adds the `_n` tag to the query results which may not be desired.

It would be great to have a `Filter` method that shortcuts this, perhaps `HasFilter`?

    g.V().HasFilter("concentration_ng", gt(5))

**Comment by dennwc** [comment]
I decided not to extend Gizmo API, but to allow to pass comparisons to existing Has/HasR calls:
```
g.V().Has("concentration_ng", gt(5))
```

**Comment by relvacode** [comment]
That is even better thank you!
