### ISSUE TITLE
DynamoDB backend

### ISSUE THREAD

**Issue by dennwc** [cayleygraph/cayley#654]
This might be not the best backend to support, but it's included to test how well NoSQL level (#652) can be generalized.

DynamoDB presents few challenges for the port like hash-based indexes, limited number of indexes, limited query support, etc.

The port is mostly done, but if any problems arise it will be pushed to later point releases.

**Comment by iddan** [comment]
Backend support was moved to a [separate project](https://github.com/hidal-go/hidalgo).

**Comment by iddan** [comment]
This issue is now tracked [here](https://github.com/hidal-go/hidalgo/issues/6)
