### ISSUE TITLE
Google Datastore backend

### ISSUE THREAD

**Issue by dennwc** [cayleygraph/cayley#656]
We support GAE for quite some time now, but it was not updated since v0.5 and lacks most new features.

Since #652 is nearly done it makes sense to port GAE to it. This should will minimize maintenance effort in the future.

**Comment by wsh** [comment]
I'll try to do this for the Cloud Datastore API, which doesn't require running in App Engine Standard. :smile: The #652 approach (i.e. near the elastic and mongo backends) makes sense to me.

**Comment by dennwc** [comment]
Sounds good! Please let me know if you have any questions regarding implementation.

**Comment by mbrukman** [comment]
@wsh — any progress on the Datastore backend? Also, is the current GAE Datastore backend production-capable? Datastore is not listed in the backend section of https://github.com/cayleygraph/cayley#features, hence the question.

**Comment by wsh** [comment]
Finally got a chance to work on this. :) https://github.com/cayleygraph/cayley/compare/master...wsh:add-cloud-datastore. I don't want to spam you all with a pull request until it's a bit further along, but am happy to open one if you'd like (and would welcome feedback). (FYI, in case it's not obvious, I'm not very experienced with Go.)

**Comment by dennwc** [comment]
@wsh Great news! Thanks for taking a time to work on it :)

Can you please open a PR against [this tree](https://github.com/hidal-go/hidalgo/tree/master/legacy/nosql)?

**Comment by Cidan** [comment]
This looks like a stale PR, @wsh would you like help merging this?

**Comment by iddan** [comment]
Backend support was moved to a separate project.

**Comment by iddan** [comment]
This issue is now tracked [here](https://github.com/hidal-go/hidalgo/issues/7)
