### ISSUE TITLE
Rocksdb backend

### ISSUE THREAD

**Issue by jsmorph** [cayleygraph/cayley#67]
See [`rocksdb`](http://rocksdb.org/) and its curious [benchmarks](https://github.com/facebook/rocksdb/wiki/Performance-Benchmarks).

[`github.com/DanielMorsing/rocksdb`](https://github.com/DanielMorsing/rocksdb) provides Go bindings for rocksdb.  That repo is a fork of [`github.com/jmhodges/levigo`](https://github.com/jmhodges/levigo), which is a wrapper around the C++ LevelDB.  That API isn't too different from [`github.com/syndtr/goleveldb`](https://github.com/syndtr/goleveldb)'s API, which is the basis for the current LevelDB support.

I've got rough code running; not too bad.

The obvious problem is that standard rocksdb support would cost a external native code dependency.  Requiring `librocksdb.{so,a}` to run Cayley using another back end is bad.  Not sure how to address that problem.  Maybe for now just include the `graph/rocksdb` directory, but leave `rocksdb` out of `db/{load,init}.go`?

**Comment by iddan** [comment]
Backend support was moved to a [separate project](https://github.com/hidal-go/hidalgo).

**Comment by iddan** [comment]
This issue is now tracked [here](https://github.com/hidal-go/hidalgo/issues/5)
