### ISSUE TITLE
cannot get any result after upgrade docker image from 0.7.0-alpha to 0.7.0

### ISSUE THREAD

**Issue by alucardpj** [cayleygraph/cayley#671]
**Description**

I previously use cayley docker image with the cayley version 0.7.0-alpha, the docker image ID is 103a0aa5941f. The backend is mongo. And I store some data via that container. 
Today I upgrade the docker image to cayley version 0.7.0, with the image ID 146344a99fe1, but I cannot get any result, the result is always 
{
	"result": null
}

**Steps to reproduce the issue:**
1. pull cayley docker image with image id 103a0aa5941f, create a container with backend mongo, store some data.
2. upgrade cayley docker image to ID 146344a99fe1, create another container with the same backend
3. run searching in new container

**Received results:**

always receive 
```
{
	"result": null
}
```

**Expected results:**
the data previously stored

**Output of `cayley version` or commit hash:**
previous cayley docker image is
```
Cayley version: 0.7.0-alpha
Git commit hash: 9134bc4b2980
```
now the new docker image is
```
Cayley version: 0.7.0
Git commit hash: 6f8446e4171e
```

**Environment details:**

Backend database: `(database and version)`
mongodb, 3.4.10

**Comment by dennwc** [comment]
v0.7.0 has some backward incompatible changes, as version number suggests. This was also mentioned in release notes:

> Storage format for backends received an upgrade bringing backward incompatible changes. Check [migration guide](./docs/Migration.md) for more details. It only affects the database format, HTTP API remains backward-compatible.

**Comment by dennwc** [comment]
Sorry, missed one detail: Mongo still work if you run it as `mongo1` - it was switched to new implementation right before the release, so it was not enabled in alpha.

**Comment by alucardpj** [comment]
thanks for your help, I'll do the migrating.
