### ISSUE TITLE
404 not found: browser client (0.7.0)

### ISSUE THREAD

**Issue by gauravtiwari** [cayleygraph/cayley#672]
**Description**

In-browser query visualiser is returning **404 not found**

**Steps to reproduce the issue:**
```
brew upgrade cayley
```

Followed the guide here: 

https://github.com/cayleygraph/cayley/blob/master/docs/Quickstart-As-Application.md#quick-preview

```
I1228 20:03:34.666503   80944 cayley.go:63] Cayley version: 0.7.0 (6f8446e4171ebc84955dd0ff91927510ba1aee16)
I1228 20:03:34.667026   80944 database.go:180] using backend "memstore"
I1228 20:03:34.701608   80944 http.go:51] loadede
I1228 20:03:34.701808   80944 http.go:66] listening on 127.0.0.1:64210, web interface at http://127.0.0.1:64210
```

**Received results:**

![screen shot 2017-12-28 at 20 08 46](https://user-images.githubusercontent.com/771039/34422052-f0af0796-ec0a-11e7-8244-1dc86e2fe282.png)

**Environment details:**

Backend database: 0.7.0

**Comment by gauravtiwari** [comment]
Figured it out, need to supply `--assets` option

```
cayley http --assets=/usr/local/share/cayley/assets
```

**Comment by gauravtiwari** [comment]
BTW is it not possible to symlink assets relative to binary so it doesn't need that extra option?

**Comment by dennwc** [comment]
@gauravtiwari Yes, it expects `templates`, `static` and `docs` to be in a local dir.

I think it would be better if we add `./assets` and `/usr/local/share/cayley/assets` to a list of checked paths as well. Reopening.

**Comment by gauravtiwari** [comment]
Will make a PR 👍

**Comment by gauravtiwari** [comment]
@dennwc At the moment if I run cayley like this i.e. not from same directory: 

```bash
# using download binary from github
# assets inside ./bin/cayley
./bin/cayley 
```

it throws 404. Does it look for assets relative to process root? If I move everything inside root directory and then run cayley like so: 

```bash
# using download binary from github
# assets next to it
./cayley 
```

it seems to pickup assets fine. 

Also, I was wondering may be we add default lookups for config file as well? i.e. `./cayley.yml` and `./cayley.json` and  `./config/cayley.yml` and `./config/cayley.json` (something like this?)
