### ISSUE TITLE
 Multiple backend stores

### ISSUE THREAD

**Issue by ShalokShalom** [cayleygraph/cayley#684]
Homepage: 
LevelDB, Bolt, PostgreSQL, MongoDB, In-memory, ephemeral
Readme: 
Bolt, LevelDB, MongoDB, ElasticSearch, PostgreSQL, CockroachDB, MySQL, In-memory, ephemeral

**Comment by dennwc** [comment]
Fixed via https://github.com/cayleygraph/website/commit/f99a91e797a40c2bf74b99afc0493627c94141e3
