### ISSUE TITLE
TiKV backend

### ISSUE THREAD

**Issue by shenli** [cayleygraph/cayley#688]
[TiKV](https://github.com/pingcap/tikv) is a distributed Key-Value storage with ACID Transaction. It has Golang client.
Is it possible to use TiKV as the backend of cayley? I can not find a tutorial for this task. Is there any example?
Thanks!

**Comment by dennwc** [comment]
TiKV is not currently supported by Cayley, but it can be easily implemented (see interfaces in [kv.go](https://github.com/cayleygraph/cayley/blob/master/graph/kv/kv.go)).

TiDB supports MySQL protocol, thus Cayley should be able to run on top of it using `mysql` backend.

**Comment by shenli** [comment]
@dennwc Thanks!
I think it is not difficult to implement a driver for TiKV. I will have a try. I think it would be more efficient to use TiKV as the backend instead of TiDB.

**Comment by dennwc** [comment]
@shenli Any updates on the new backend? If you have any problems implementing KV interfaces, please let me know.

**Comment by ShalokShalom** [comment]
Oh, that is interesting :O

**Comment by iddan** [comment]
Backend support was moved to a separate project.

**Comment by iddan** [comment]
This issue is now tracked [here](https://github.com/hidal-go/hidalgo/issues/8)
