### ISSUE TITLE
Optimise cockroachdb backend

### ISSUE THREAD

**Issue by dsymonds** [cayleygraph/cayley#691]
**Description**

The [CockroachDB](https://www.cockroachlabs.com) backend for Cayley in `graph/sql/cockroach`, added in #299 is significantly slower than it could be. cockroachdb/cockroach#17108 advises a transformation that according to my tests can speed up bulk insertions by 4-5x.

I'm willing to work at upstreaming my improved code if this general effort is wanted.

**Comment by dsymonds** [comment]
Sorry, forgot to mention the underlying reason: CockroachDB is a distributed database, so is much more sensitive to round-trips than usual SQL backends. The current transactions that Cayley generates are far too round-trip heavy.

**Comment by dsymonds** [comment]
I'm sorry, I'm not sure how to interpret that. @dennwc, are you saying that you're going to take this on?

**Comment by dennwc** [comment]
@dsymonds I'd like to include this patch into next minor release. If you will work on this, it's awesome, but if not - I will fix it just before the release.

**Comment by dsymonds** [comment]
Okay, I'll see if I can handle it this week; if you don't see a pull request from me then you can interpret that as me not having enough time.  ;-)
