### ISSUE TITLE
Cayley_0.7.1_windows_368.zip contains malware

### ISSUE THREAD

**Issue by dogfoodsilo4** [cayleygraph/cayley#696]
The release file Cayley_0.7.1_windows_368.zip contains malware.  See attached.

Category: Trojan
Name: Trojan:Win32/Fuerboos.A!cl
Items: C:\Cayley\cayley_0.7.1_windows_386\cayley.exe

![3](https://user-images.githubusercontent.com/10741833/36599075-1a94d582-18a6-11e8-885e-2a7beb7fa460.PNG)

Cayley_0.7.1_windows_amd64.zip does not appear to be affected.

Is it possible to get an updated clean release?

**Comment by dennwc** [comment]
These binaries was cross-compiled from Linux, so I'm pretty sure it's a false positive.

Related: https://github.com/junegunn/fzf/issues/1110

**Comment by dennwc** [comment]
Closing this, see https://github.com/golang/go/issues/23759 for more details
