### ISSUE TITLE
glide install fails on Windows 10 Pro

### ISSUE THREAD

**Issue by rajkrishnamurthy** [cayleygraph/cayley#703]
**Description**

**Steps to reproduce the issue:**
1. git cloned the repo.
2. cd cayley
3. Downloaded 13.x release Glide from https://github.com/Masterminds/glide/releases
4. Set system path to point to glide.exe
5. Ran glide install

**Received results:**

```
[ERROR] Unable to export dependencies to vendor directory: Error moving files: exit status 1. output: Access is denied.
        0 dir(s) moved.

```

**Expected results:**

**Output of `cayley version` or commit hash:**

```
(paste your output here)
```

**Environment details:**

Backend database: `(database and version)`

**Comment by rajkrishnamurthy** [comment]
Temporary workaround:
Works when glide is downgraded to 0.12.

**Comment by dennwc** [comment]
We will use dep in the new release, thus this would be fixed along the way.
