### ISSUE TITLE
Is it possible to support elasticsearch 6.x?

### ISSUE THREAD

**Issue by alvinh** [cayleygraph/cayley#711]
Hi, is it possible to support elasticsearch 6,x? After 6.x version release, multiple types in the same index had been removed, so we will encounter the following error when we use "elastic" as backend with 6.x version.

**Received Exception:**
Error: elastic: Error 400 (Bad Request): Rejecting mapping update to [cayley] as the final mapping would have more than 1 type: [nodes, log] [type=illegal_argument_exception]

Many thanks....

**Comment by dennwc** [comment]
Sure, we will support it.

**Comment by alvinh** [comment]
Hi dennwc, thanks for your prompt reply. But i still encountered the same problem when connecting to elasticsearch 6.x.

**Received Exception:**
Error: elastic: Error 400 (Bad Request): Rejecting mapping update to [cayley_nodes] as the final mapping would have more than 1 type: [nodes, log] [type=illegal_argument_exception]

Many thanks....

**Comment by dennwc** [comment]
@alvinh Sorry, I cannot reproduce. I'm testing it on ElasticSearch v6.2.4 (Docker image) and Cayley version v0.7.3. Make sure you updated to the latest version and in case it still doesn't work, please paste an output of `cayley version`.

**Comment by alvinh** [comment]
Hi @dennwc, the output and config file are as below, thanks.

**Cayley Output:**
[root@m01 cayley_0.7.3_linux_amd64]# ./cayley http --host=0.0.0.0:64211 --config=cayley_elasticsearch_config.yml
I0424 17:25:25.802240  116372 cayley.go:63] Cayley version: 0.7.3 (782194b030b5170bbb0852c5e29f209e8012be37)
I0424 17:25:25.802372  116372 cayley.go:76] using config file: cayley_elasticsearch_config.yml
I0424 17:25:25.802454  116372 database.go:187] using backend "elastic" (http://127.0.0.1:9201)
Error: elastic: Error 400 (Bad Request): Rejecting mapping update to [cayley_nodes] as the final mapping would have more than 1 type: [nodes, log] [type=illegal_argument_exception]

**Config File**
store:
  backend: elastic
  address: "http://127.0.0.1:9201"
  read_only: false
query:
  timeout: 30s
load:
  ignore_duplicates: false
  ignore_missing: false
  batch: 10000

**Comment by dennwc** [comment]
Everything looks good, but it still tries to use an old code path. It might happen because of failed ES version detection. Let's try to debug it with your version of ElasticSearch. Please PM me on Slack.

**Comment by dennwc** [comment]
Was a cluster misconfiguration issue
