### ISSUE TITLE
GraphQL is breaking 

### ISSUE THREAD

**Issue by steffansluis** [cayleygraph/cayley#717]
Running a Gizmo query `g.V("<someId>").All()` returns about 1150 results. Running the GraphQL query:

```
{
    nodes(id: "<someId>") {
      http://www.w3.org/1999/02/22-rdf-syntax-ns#type @opt
    }
}
```

returns a 503 because of a query timeout.

Edit: The Gizmo query returns after about 5 sec.

**Comment by steffansluis** [comment]
Fiddled around some more. Without the `@opt` it works fine, so it seems the problem is there.

**Comment by steffansluis** [comment]
Hmmm, my phrasing might have been a bit ambiguous. The main point was that GraphQL seems to take a lot more time than Gizmo to do essentially the same thing, namely retrieve some directly related (optional) thing(s) given a starting point. I should mention that I have about 5 million quads in my Postgres backed Cayley, which is probably part of the reason why it is so slow. Nevertheless, the discrepancy between the two APIs seemed like something you would want to know about.

**Comment by dennwc** [comment]
I understand this, and I think I know why it might take so long for `@opt` query.

The thing I don't understand is how can it return 1150 results for a query that selects a single node. This is what I'm trying to ask.

**Comment by steffansluis** [comment]
Ah, sorry, that was a bad typo on my part. I meant `g.V("<someId>").Out().All()` indeed (I understand your previous message a lot better as well now).

**Comment by dennwc** [comment]
OK, makes sense now :) Then an equivalent GraphQL query should be something like:
```
{
    nodes(id: "<someId>") {
      any: * {
        http://www.w3.org/1999/02/22-rdf-syntax-ns#type @opt
      }
    }
}
```
Although I'm not sure we support this star syntax.

Still not sure how a one-node GraphQL in your first post can timeout. Maybe something is broken in id queries.

**Comment by dennwc** [comment]
@steffansluis I need more information about this one. Can you please send exact queries you run? If you could provide a test data as well it would be ideal.

**Comment by dennwc** [comment]
I assume it's the same as #740.
