### ISSUE TITLE
Elasticsearch backend configuration options

### ISSUE THREAD

**Issue by olivere** [cayleygraph/cayley#730]
I'm the author of `github.com/olivere/elastic` that you're using as a storage backend for Elasticsearch. I've seen issues popping up in Elastic that describe connection problems when using ES as a backend with Cayley.

These connection problems typically stem from the fact that Elastic (the Go client) is using a process called [sniffing](https://github.com/olivere/elastic/wiki/Sniffing) to do client-side load-balancing between the nodes of an Elasticsearch cluster (I didn't invent this: All the official Elasticsearch clients have this.) However, sniffing may fail due to the nodes not being routable (e.g. running ES in a Docker container will return private IPs by default).

Long story short: If you're using Elastic, it might be necessary to pass additional options into the `elastic.NewClient(...)` function, e.g. for disabling sniffing or disabling health checks. However, Cayley is [currently not passing](https://github.com/cayleygraph/cayley/blob/master/graph/nosql/elastic/elastic.go#L35) any [additional parameters](https://github.com/olivere/elastic/wiki/Configuration), and I don't see how I might be able to configure this in Cayley.

But maybe I have a solution.

Elastic has a subpackage [`github.com/olivere/elastic/config`](https://github.com/olivere/elastic/blob/release-branch.v6/config/config.go) that allows to users to pass a URL with query parameters. These parameters will be parsed and a `*config.Config` structure is returned. You can pass that `*config.Config` into [`elastic.NewClientFromConfig(*config.Config)`](https://github.com/olivere/elastic/blob/release-branch.v6/client.go#L296) to get a client.

That'd allow to keep your configuration simple (it's just a URL) and make users capable of configuring their Elasticsearch connection however they need.

I'm not sure if you're interested in this feature, but if you are and I can help, just let me know. :-)

**Comment by dennwc** [comment]
@olivere Thanks for sharing these configuration details, your solution can indeed be integrated into Cayley easily and we are definitely interested in this.

However, we are currently in the transition to v0.8 and as a part of this transition, we want to move all backend-specific code to a separate project called [Hidalgo](https://github.com/hidal-go/hidalgo). So all the changes will probably happen there, but we may decide to send a hotfix in Cayley as well.

In any case, thank you for reaching out. We highly appreciate it :)

**Comment by iddan** [comment]
This issue is now tracked [here](https://github.com/hidal-go/hidalgo/issues/9)
