### ISSUE TITLE
Add Gremlin "Except" and "Retain" filtering methods

### ISSUE THREAD

**Issue by pbnjay** [cayleygraph/cayley#74]
Along with requisite "Aggregate" method as described here:
https://github.com/tinkerpop/gremlin/wiki/Except-Retain-Pattern

This'll allow much better query support and output.

**Comment by robertmeta** [comment]
Moved this over to feature requests as it seems to have been sitting here without much implementation for a long time, maybe over there it will generate some new excitement: https://discourse.cayley.io/t/add-gremlin-except-and-retain-filtering-methods/239
