### ISSUE TITLE
Tagged version 0.7.4 reports as version 0.7.3

### ISSUE THREAD

**Issue by danbo** [cayleygraph/cayley#750]
https://github.com/cayleygraph/cayley/blob/431ee2850fa29f8f7dfa0de6a03c07237871d504/version/version.go#L4

**Comment by dennwc** [comment]
Indeed, this was a mistake when tagging the release. Will fix it.

**Comment by dennwc** [comment]
Should be fixed now:
https://github.com/cayleygraph/cayley/releases/tag/v0.7.4-2
