### ISSUE TITLE
Allow to embed the server

### ISSUE THREAD

**Issue by vtolstov** [cayleygraph/cayley#755]
does it possible to embed server into own app and configure it pragmatically?

**Comment by vtolstov** [comment]
?

**Comment by dennwc** [comment]
It's possible to embed Cayley itself, but not the server in the current state.

There is no reason to disallow embedded mode, we just haven't had any use cases for it.

Can you please elaborate a bit what kind of functionality do you want to expose?

**Comment by iddan** [comment]
Closing as no reply was given for too long. @vtolstov if this is still an issue please comment and we'll reopen the issue.
