### ISSUE TITLE
gizmo, saveOptional ignoring labelContext

### ISSUE THREAD

**Issue by 3pCode** [cayleygraph/cayley#758]
Description:

The saveOpt function in gizmo does not currently respect the label context specified. The documentation specifies the behaviour of saveOpt as being the same as save, with the difference that it will return an empty string if the predicate does not exist. However save(), respects the label context set whereas saveOpt (and saveOptR as well) do not respect the label.

Problem seems to be in saveOptionalMorphism (and saveOptionalReverseMorphism) in morphism_apply_functions.go (lines 351, 361), it is calling SaveVia, instead of SaveViaLabels which allows for the labelSet property of the context to be passed in. 

**Steps to reproduce the issue:**
Reproducer is below (this can pasted into gizmo_test.go)

```
var graphLabelQueries = []struct {
	message string
	data    []quad.Quad
	query   string
	limit   int
	tag     string
	expect  []string
	err     bool
}{
	// SaveOpt, should behave exactly as Save in this scenario. But Save is ignoring the LabelContext, while Save, respects it.
	// This results in SaveOpt currently returning both smart_person, and cool_person. But only cool_person should be returned.
	{
		message: "get a single vertex",
		query: `
			g.V("<greg>").LabelContext("<smart_graph>").SaveOpt("<status>", "statusTag").All()
		`,
		tag:    "statusTag",
		expect: []string{"smart_person"},
	},
}

func TestLabelContext(t *testing.T) {
	simpleGraph := testutil.LoadGraph(t, "../../data/testdata.nq")
	for _, test := range graphLabelQueries {
		test := test
		t.Run(test.message, func(t *testing.T) {
			rec := func() {
				if r := recover(); r != nil {
					t.Errorf("Unexpected panic on %s: %v", test.message, r)
				}
			}
			defer rec()
			if test.tag == "" {
				test.tag = TopResultTag
			}
			quads := simpleGraph
			if test.data != nil {
				quads = test.data
			}
			limit := test.limit
			if limit == 0 {
				limit = -1
			}
			got, err := runQueryGetTag(rec, quads, test.query, test.tag, limit)
			if err != nil {
				if test.err {
					return //expected
				}
				t.Error(err)
			}
			sort.Strings(got)
			sort.Strings(test.expect)
			if !reflect.DeepEqual(got, test.expect) {
				t.Errorf("got: %v expected: %v", got, test.expect)
			}
		})
	}
}
```

**Received results:**
--- FAIL: TestLabelContext (0.00s)
    --- FAIL: TestLabelContext/get_a_single_vertex (0.00s)
    	gizmo_test.go:796: got: [cool_person smart_person] expected: [smart_person]
FAIL

Note that this test returns output of cool_persion, and smart_person, only smart_person is  a valid status for the graph label smart_graph. If the test is modified to use Save, instead of SaveOpt, then the test passes, returning only smart_person as a status.

**Expected results:**
SaveOpt would respect the graph label, and the above test would return only smart_person.

**Output of `cayley version` or commit hash:**

```
0.7.5
```

**Environment details:**

Backend database: `memstore`

**Comment by dennwc** [comment]
Thanks for tracking this down! Sure, the proposed fix is perfectly valid. Please file a PR with it (and the test case, of course).

Next time feel free to send a PR directly :)

**Comment by dennwc** [comment]
Fixed in https://github.com/cayleygraph/cayley/pull/760
