### ISSUE TITLE
schema: support defined types

### ISSUE THREAD

**Issue by dncohen** [cayleygraph/cayley#768]
**Description**

Hi.  I'm new to Cayley, so please forgive any newbie-ness.  I'm considering whether to use Cayley for a project.  One of the things I hope to do is write structs into Cayley and read them back out.  I'm hoping the schema package works out for this.

One of my structs includes fields of defined types (https://golang.org/ref/spec#Type_definitions), i.e.

`type MyCustomType string`

This leads to Cayley failing to write with "unsupported type: MyCustomType"

**Steps to reproduce the issue:**
1. Apply patch (below) to examples/hello_schema/main.go
2. `go run main.go`
3. Observe the error

Here's the patch (`git diff`)

```
index e3fe2f1..2e6fb98 100644
--- a/examples/hello_schema/main.go
+++ b/examples/hello_schema/main.go
@@ -19,6 +19,8 @@ import (
        _ "github.com/cayleygraph/cayley/voc/core"
 )

+type TestString string
+
 type Person struct {
        // dummy field to enforce all object to have a <id> <rdf:type> <ex:Person> relation
        // means nothing for Go itself
@@ -26,6 +28,8 @@ type Person struct {
        ID      quad.IRI `json:"@id"`     // tag @id is a special one - graph node value will be stored in this field
        Name    string   `json:"ex:name"` // field name (predicate) may be written as json field name
        Age     int      `quad:"ex:age"`  // or in a quad tag
+
+       Test TestString `quad:"test"`
 }

 type Coords struct {
@@ -76,6 +80,7 @@ func main() {
        bob := Person{
                ID:   quad.IRI("ex:bob").Full().Short(),
                Name: "Bob", Age: 32,
+               Test: "foo",
        }
        fmt.Printf("saving: %+v\n", bob)
        id, err := sch.WriteAsQuads(qw, bob)

```

**Received results:**

```
2019/02/15 05:33:02 unsupported type: main.TestString
```

**Expected results:**

**Output of `cayley version` or commit hash:**

```
f0dd103fbc44c697e7a063279b5850ec4a7b403a
```

**Comment by dncohen** [comment]
Here's a change to schema/writer.go that I'm currently experimenting with.  Not sure whether it is the right approach or not...

```
@@ -133,15 +133,20 @@ func (w *writer) writeAsQuads(rv reflect.Value) (quad.Value, error) {
       rt = rv.Type()
       kind = rt.Kind()
     }
+
+  case reflect.String:
+    return quad.String(rv.String()), nil
+
   }
   // check if it's a type that quads package supports
   // note, that it may be a struct such as time.Time
   if val, ok := quad.AsValue(rv.Interface()); ok {
     return val, nil
   }
+
   // TODO(dennwc): support maps
   if kind != reflect.Struct {
-    return nil, fmt.Errorf("unsupported type: %v", rt)
+    return nil, fmt.Errorf("unsupported type: %v (%s)", rt, kind)
   }
   // get conversion rules for this struct type
   rules, err := w.c.rulesFor(rt)

```

**Comment by dennwc** [comment]
Thank you for another detailed report :)

Yes, the proposed change makes sense in general, but it may need to be implemented a bit more carefully. Consider this example:

```golang
type TestIRI quad.IRI
```

Since `quad.IRI` is of a string kind, it will be converted to `quad.String` instead of `quad.IRI` with the patch you suggested. Unfortunately I don't remember if there is a way to examine the underlying type via reflect. If not, we can use the kind and document it somewhere.

**Comment by dncohen** [comment]
I believe the specific case you mentioned is handled differently, because quad.IRI implements quad.Value.  There's a check for that, immediately before the kind switch.

(still experimenting...I'll post more if I learn anything useful.)

**Comment by dennwc** [comment]
You are right, but this form of "typedef" won't inherit methods from `IRI`.

**Comment by dncohen** [comment]
Ah, thanks for correcting me there.

I've seen in a couple places `TODO(dennwc): rewrite to shapes`, but I haven't found any example at all of a query that uses shapes.  I see graph/shape/*.go, but not really grokking it.  Is there an example or recommended reading to understand shapes? (apologies for going off-topic)

**Comment by dennwc** [comment]
No worries.

All queries currently use `path` lib to construct the query, but it uses `shape` under the hood.

The best way to check how it works is to execute Cayley with `CAYLEY_DEBUG_SHAPES=true` and run some simple query. This will print a query shape in form of Go objects. If you indent it, you will see how the query is structured. There will be filters on quads, lookups on nodes, etc.

The next step is to enable `CAYLEY_DEBUG_OPTIMIZER=true` - it will print a second query shape, this time after an optimization pass. This one will depend on the backend, but should be more readable.
