### ISSUE TITLE
All() does not return all results

### ISSUE THREAD

**Issue by maaahooo** [cayleygraph/cayley#770]
**Description**

Hi, 

i have a question concerning returning all nodes. In my DB,

`g.V('node-2323').Out().Out().Out().All() ` returns 100 nodes, but
`g.V('node-2323').Out().Out().Out().GetLimit(2000) ` returns the actual number of 1287 nodes.

Why is the output of All() limited to 100?

I tried it in repl and through the HTTP API.

My storage backend is leveldb.

Thanks!

**Comment by numrut** [comment]
This is the expected behavior. See https://github.com/cayleygraph/cayley/issues/718#issuecomment-398709801

Use `?limit=-1` or `.GetLimit(-1)` to disable the limit.

**Comment by dennwc** [comment]
Indeed, we limit the number of results returned by HTTP APIs so people don't end up listing the whole graph by accident. Setting the limit to `-1` will solve your issue.
