### ISSUE TITLE
kv: write tests fail with bloom filter disabled

### ISSUE THREAD

**Issue by hypirion** [cayleygraph/cayley#771]
**Description**

I am looking into disabling the Bloom filter used by KV-stores in order to trade some RAM with reduced write performance (It doesn't seem to be used for read operations, and that is effectively all the operations I do on my dataset). When I'm doing so, it looks like the Cayley tests assumes the bloom filter never returns false positives, even though it could. I am not sure if this is an issue in practice, but it feels worrisome that tests fail by removing what seems to only be an optimisation.

**Steps to reproduce the issue:**
1. Modify [this line](https://github.com/cayleygraph/cayley/blob/f3cae7f1e94149ced3d0a9b0c358359792495dd7/graph/kv/indexing.go#L938) of `testBloom` to `return true`.
2. run `go test ./...`, and notice that you receive a lot of errors
3. (optional) Verify that you get no errors when you revert the change

**Received results:**

It seems like all subpackages of `github.com/cayleygraph/cayley/graph/kv` fail their tests when the "BloomFilter" is set to return true all the time.

I would expect none of the KV packages to fail if I replace the bloom filter test with a function that returns true all the time. 

**Output of `cayley version` or commit hash:**

This happened on commit f3cae7f1e94149ced3d0a9b0c358359792495dd7

**Comment by dennwc** [comment]
We [don't use](https://github.com/cayleygraph/cayley/blob/master/graph/kv/indexing.go#L645) positive results from `testBloom` function.

However, you are right, the test indeed fails with bloom filter disabled. Will check why it happens.
