### ISSUE TITLE
No information provided on homepage for how to contribute

### ISSUE THREAD

**Issue by xavierh93** [cayleygraph/cayley#782]
**Description**

There is no file on the homepage to learn how you can start contributing to this project.  I know you have one but it would be a good idea to keep it on the homepage so new people could find it a lot easier.  

Not everyone is going to know to click on the docs folder to find the contributing.md file

**Comment by marti1125** [comment]
Hi, I could suggest you some examples. Could I work on this?
https://github.com/nayafia/contributing-template
https://gist.github.com/PurpleBooth/b24679402957c63ec426

**Comment by dennwc** [comment]
@marti1125 Of course, contributions are welcome! Unfortunately I don't have time to work on it currently :(

**Comment by marti1125** [comment]
Hi @dennwc 
Do I need to modify? this: https://github.com/cayleygraph/cayley/blob/master/docs/Contributing.md
what do you expect?

**Comment by dennwc** [comment]
Yes, updating `Contributing.md` would be nice. Also, we should add a link to that page from `README.md`.

**Comment by marti1125** [comment]
I am trying to build from source, well I have to modify some the instructions, I think

```
GO111MODULE=on go mod download

go build ./cmd/cayley 

```
after run `go build` I got this: https://gist.github.com/marti1125/b8c289babffa996e77c974605f4f7421

**Comment by dennwc** [comment]
@marti1125 Thanks for reporting it, opened an issue for it: https://github.com/cayleygraph/cayley/issues/826

**Comment by dennwc** [comment]
@marti1125 Can you please share the output of your `go env`? It looks like the problem is on your side.

Also please try this:
```
GO111MODULE=on go mod download
GO111MODULE=on go build ./cmd/cayley
```

**Comment by marti1125** [comment]
sure!

```
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/willy.aguirre/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/willy.aguirre/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build500448538=/tmp/go-build -gno-record-gcc-switches"
```

**Comment by marti1125** [comment]
@dennwc yep it works! my mystake

```
I0923 06:22:41.020975   15259 command.go:805] Cayley version: v0.7.x-dev (dev snapshot)
I0923 06:22:41.021252   15259 repl.go:56] using backend "memstore"
I0923 06:22:41.023200   15259 repl.go:60] loaded "data/testdata.nq" in 1.879572ms
creating new history file: ".cayley_history"
cayley> 

```

**Comment by dennwc** [comment]
Great. We should update the `Contributing.md` page and specify that on Go < 1.13 you need to add `GO111MODULE=on` to all commands.
