### ISSUE TITLE
Gizmo: Is() + Filter(regex()) doesn't work

### ISSUE THREAD

**Issue by iddan** [cayleygraph/cayley#790]
**Description**
When combining `.Is()` & `.Filter(regex()` queries no result is returned while each of them does.

**Steps to reproduce the issue:**
Query:
```javascript
g.AddNamespace("rdf", "http://www.w3.org/1999/02/22-rdf-syntax-ns#")
g.AddNamespace("rdfs", "http://www.w3.org/2000/01/rdf-schema#")
g.AddNamespace("symptoms", "http://khealth.ai/ontology/symptoms#")

g
.V()
.Tag("id")
.Out(g.Uri("rdf:type"))
.Is("<http://khealth.ai/ontology/symptoms#Symptom>")
.Tag("type")
.Back("id")
.Out(g.Uri("rdfs:label"))
.Tag("label")
.Filter(regex("(?i)Headache"))
.Skip(10)
.GetLimit(10)
```

**Received results:**

```json
{
	"result": null
}
```

**Expected results:**

The intersection of:
```javascript
g.AddNamespace("rdf", "http://www.w3.org/1999/02/22-rdf-syntax-ns#")
g.AddNamespace("rdfs", "http://www.w3.org/2000/01/rdf-schema#")
g.AddNamespace("symptoms", "http://khealth.ai/ontology/symptoms#")

g
.V()
.Tag("id")
.Out(g.Uri("rdf:type"))
// .Is("<http://khealth.ai/ontology/symptoms#Symptom>")
.Tag("type")
.Back("id")
.Out(g.Uri("rdfs:label"))
.Tag("label")
.Filter(regex("(?i)Headache"))
.Skip(10)
.GetLimit(10)
```
and:
```javascript
g.AddNamespace("rdf", "http://www.w3.org/1999/02/22-rdf-syntax-ns#")
g.AddNamespace("rdfs", "http://www.w3.org/2000/01/rdf-schema#")
g.AddNamespace("symptoms", "http://khealth.ai/ontology/symptoms#")

g
.V()
.Tag("id")
.Out(g.Uri("rdf:type"))
.Is("<http://khealth.ai/ontology/symptoms#Symptom>")
.Tag("type")
.Back("id")
.Out(g.Uri("rdfs:label"))
.Tag("label")
//.Filter(regex("(?i)Headache"))
.Skip(10)
.GetLimit(10)
```

**Output of `cayley version` or commit hash:**

https://github.com/cayleygraph/cayley/commit/8d1602b73e9a7d1d65537590c8cc4528c36de261

**Environment details:**

Backend database: memory

**Comment by dennwc** [comment]
Is it possible to share the dataset part so I can debug the issues? As an option, you can share it privately on Slack.

**Comment by iddan** [comment]
Sending it on Slack

**Comment by iddan** [comment]
Did you get to check that? The issue still persists with the latest version.

**Comment by dennwc** [comment]
A few notes:

Changing `Out().Is().Back()` to `Has()` doesn't make any difference, so it's not related to `Back()`. This query still fails:

```javascript
g.AddNamespace("rdf", "http://www.w3.org/1999/02/22-rdf-syntax-ns#")
g.AddNamespace("rdfs", "http://www.w3.org/2000/01/rdf-schema#")
g.AddNamespace("symptoms", "http://khealth.ai/ontology/symptoms#")

g
.V()
.Tag("id")
.Has(g.Uri("rdf:type"), "<http://khealth.ai/ontology/symptoms#Symptom>")
.Out(g.Uri("rdfs:label"))
.Tag("label")
.Filter(regex("(?i)Headache"))
.Skip(10)
.GetLimit(20)
```

On the other hand, removing `Skip(10)` and setting `GetLimit(20)` to compensate does the trick. So it must be related to how `Skip` works.

**Comment by dennwc** [comment]
@iddan Actually, I don't think it's a bug, at least in this particular case.

If `Skip` is removed, the query works and produces exactly 1 results. Thus adding `Skip(10)` skips that result and returns nothing.

And executing the query to find all `Symptom` objects leads to only one that can match that regexp pattern. So I think everything works as intended.

Can you please check it on your side as well?

**Comment by iddan** [comment]
You are right. Seems like it's working. Closing.
