### ISSUE TITLE
Docker Builds Tags & Docker Hub

### ISSUE THREAD

**Issue by iddan** [cayleygraph/cayley#793]
**Description**
When I started using Cayley I first looked in Google for its docker image but got some odd results. I think it has to do in part to the fact it has no official Docker Hub builds - the go-to registry for open source containers.
Now that I'm using the container from Quay I'm not able to use a specific version rather a historical one or `latest` which Docker only updates manually a problem when sharing container configurations.
I suggest setting up a Docker Hub automated build that will build each release and in addition assign `latest` tag. This way it will be easier to integrate. We can even go further and suggest Cayley to the Docker library and allow users to do:
```dockerfile
docker run cayley
```

**Comment by dennwc** [comment]
[Organization](https://hub.docker.com/?namespace=cayleygraph) created, will set up a build after the integration is enabled by @barakmich.

**Comment by iddan** [comment]
I could have done it if I was part of the organisation :)

**Comment by dennwc** [comment]
Setup done, first (dev) build available, and automated build enabled:
https://hub.docker.com/r/cayleygraph/cayley
Now we need to push previous tags and update docs.
