### ISSUE TITLE
Read API: Check if client gone away

### ISSUE THREAD

**Issue by iddan** [cayleygraph/cayley#805]
**Description**
As written in the TODO comment here: https://github.com/cayleygraph/cayley/blob/master/server/http/api_v2.go#L369 the Read API should check if the client has gone away to stop writing quads.
Because it currently doesn't many calls to the Read API lead Cayley process to go up to 100% capacity of the computer and hang.

**Comment by dennwc** [comment]
`TODO` was about suppressing an error, but I found another one that was related to this issue. Should be fixed now, feel free to reopen if it's not.
