### ISSUE TITLE
Docker crashes on load

### ISSUE THREAD

**Issue by iddan** [cayleygraph/cayley#812]
**Description**
On weaker machines, if the graph's container gets to a certain amount of workload it crashes without a proper explanation. Happens often on our low-end MacBooks, but not so often on our high-end MacBooks.

**Output of `cayley version` or commit hash:**

```
Cayley version: v0.7.x-dev
Git commit hash: b9dabbed3f75
```

**Environment details:**

Backend database: `memory`

**Comment by dennwc** [comment]
I don't have a Mac to verify it. Is it an OOM issue?

**Comment by iddan** [comment]
Might be. Only thing I can tell you the container is exiting with no exception.

**Comment by dennwc** [comment]
Can you please check the memory consumption during the event as well? And there is no logs in the Docker container either?

Without any additional information this issue is basically a "wontfix": we are not even sure it's related to Cayley and not to the system/Docker configuration, for example.

**Comment by iddan** [comment]
I'll check with the people complaining in the office on Sunday (it's a working day in Tel Aviv) and let you know.

**Comment by iddan** [comment]
Seems like the situation is okay for now. Will open a new issue if I'll hear new complaints
