### ISSUE TITLE
Web doesn't work in latest chrome and opera

### ISSUE THREAD

**Issue by colben** [cayleygraph/cayley#818]
# Environment
- CentOS7
- Cayley 0.7.5
- Chrome lastest
- Opera latest
- Firefox 52 ESR

# Issue
- firefox 52 works fine
![aa](https://user-images.githubusercontent.com/7829126/64221853-d7dc4f00-cf00-11e9-8f8c-a119fce0bbfd.png)

- chrome and opera display like this
![bb](https://user-images.githubusercontent.com/7829126/64221870-e0348a00-cf00-11e9-99e0-e3f577f38d45.png)

**Comment by iddan** [comment]
Can you please check https://cayley-ui.netlify.com/ ?

**Comment by iddan** [comment]
Closing, as no answer was provided. If you encounter issues with the new UI please open an issue in [Cayley Web](https://github.com/cayleygraph/web/issues)
