### ISSUE TITLE
Feature Suggestion: Using JSON-LD for Gizmo results

### ISSUE THREAD

**Issue by iddan** [cayleygraph/cayley#820]
**Description**
Currently, Gizmo returns JSONs of strings which may or may not be valid n3 values. This is a non-standard behaviour that is hard to integrate with other systems.

**Examples**
Results of IRIs:
```json
{ "@id": "bob" }
```

Results of literals:
```json
"Bob"
```

Results of literals with language:
```json
{ "@language": "en", "@value": "Bob" }
```

Results of literals with type:
```json
{
    "@value": "2010-05-29T14:17:39+02:00",
    "@type": "http://www.w3.org/2001/XMLSchema#dateTime"
}
```

All together
```json
{
   "id": { "@id": "bob" },
   "name": "Bob",
   "englishName": { "@value": "Bob", "@language": "en" },
   "timeCreated": {
      "@value": "2010-05-29T14:17:39+02:00",
      "@type": "http://www.w3.org/2001/XMLSchema#dateTime"
   }
}
```

**Future Proposals**
 * It might be better to change `id` default property

**Comment by iddan** [comment]
Took a deeper look into Gremlin. It seems like you need to be explicit about the return type you get there.
To get nodes:
```javascript
g.V()
```
To get values:
```javascript
g.V(1).values('name')
```
To get tags
```
g.V().as('a').out().as('b').out().as('c').select('a','b','c')
```
Which I find more explicit and simple

**Comment by iddan** [comment]
Here is a basic implementation: https://github.com/cayleygraph/cayley/pull/821

**Comment by iddan** [comment]
@dennwc what do you think about the previous comment?

**Comment by dennwc** [comment]
@iddan It's definitely a nicer way for selecting results. May also help the optimizer to some extent.

**Comment by iddan** [comment]
Merged https://github.com/cayleygraph/cayley/pull/821
