### ISSUE TITLE
Hasura vs Cayley vs Dgraph

### ISSUE THREAD

**Issue by rrjanbiah** [cayleygraph/cayley#823]
Context:

* https://github.com/hasura/graphql-engine/issues/2883
* https://github.com/dgraph-io/dgraph/issues/3997

Dgraph is having a very good comparison documentation on Cayley vs Dgraph. Similarly, from Cayley perspective, if there is any official comparison against other counterparts, it will be helpful

**Comment by iddan** [comment]
- Hasura is a fully compatible [GraphQL](https://graphql.org/) implementation on top of [PostgresSQL](https://www.postgresql.org/), a relational SQL database
 - Dgraph is a triplestore graph database exposing a partially compatible GraphQL implementation as it's query language
 - Cayley is a triplestore graph database exposing a partially compatible GraphQL implementation as it's secondary query language, exposing a partially compatible Gremlin implementation as it's primary query language

**Comment by rrjanbiah** [comment]
@iddan Thank you so much for your precise summary

In my understanding,

* Both Hasura and Prisma offer GraphQL "backend API" system. While Hasura uses PostgreSQL, Prisma supports other relational databases
* Cayley is a "graph database" but using other relational database as datastore

*Quote from https://docs.dgraph.io/dgraph-compared-to-other-databases/*

> Cayley acts like a graph layer, providing a clean storage interface that could be implemented by various stores, for, e.g., PostGreSQL, RocksDB for a single machine, MongoDB to allow distribution. In other words, Cayley hands over data to other databases. While Dgraph uses Badger, it assumes complete ownership over the data and tightly couples data storage and management to allow for efficient distributed queries.

* Dgraph is again a "graph database" but using its own datastore. They claim that only Dgraph is horizontally scalable. But, AFAIK, using Citus, we can horizontally scale Postgres too. Also, Dgraph team says that they're working on GraphQL layer, but their document https://docs.dgraph.io/master/query-language/ says they already support GraphQL variant.

So, I was trying to understand which is having edge over the rest. In other words, which one can be used as both "backend API system" as well as graph database... again using GraphQL.

**Comment by iddan** [comment]
From the perspective of GraphQL DGraph is more focused on their GraphQL interface, but by definition it is not fully compliant with standard GraphQL libraries unlike Hasura which implement a fully complaint GraphQL interface on top of Postgres.
Prisma is similar to Cayley in the sense as it provide GraphQL and client APIs around other datastores. Unlike Prisma, Cayley uses a specific data model: the Linked Data Model and automatically makes the data efficiently queryable.

**Comment by rrjanbiah** [comment]
@iddan Thanks again for your explanation. 

Do you mean to say that Cayley has an edge over Prisma for "backend API" use cases too (especially for normal SPA sites)?

**Comment by iddan** [comment]
Prisma currently doesn't create indexes automatically (https://github.com/prisma/prisma/issues/1300) so you need to maintain the indexes on the database level and the schema in Prisma. Cayley on the other hand creates the indexes for itself and so is Hasura.

**Comment by iddan** [comment]
| Product | Index | GraphQL Full Compatibility | Imperative API | External Datastore |
| -------- | ----- | --------------------------- | --------------- | ------------------ |
| Cayley   | ✅    | ❌                                           | ✅                     | ✅                           |
| Dgraph  | ✅    | ❌                                           | ❌                     | ❌                           |
| Hasura  | ✅     | ✅                                           | ❌                     | ✅ .                        |
| Prisma   | ❌     | ✅                                          | ✅                     | ✅                           |

**Comment by rrjanbiah** [comment]
Awesome @iddan Thank you so much for your explanation. Very helpful.

**Comment by rrjanbiah** [comment]
FWIW, marked for `documentation` but not done yet in doc @iddan

**Comment by iddan** [comment]
True, I'll add a document later. I closed it because I thought I answered your question. PR is welcome as well!
