### ISSUE TITLE
Installation documentation

### ISSUE THREAD

**Issue by iddan** [cayleygraph/cayley#825]
**Description**
As Cayley is available in HomeBrew, Snap, Docker Hub and binaries I think we should have a page describing the different options, listing recommended options first and update Quickstart as Application.
What are all the supported releases of Cayley? I couldn't find an `apt-get`, `pacman` or `choco` releases but I've might missed something.
Inspiration can be taken from: https://docs.mongodb.com/manual/installation/#tutorial-installation

**Comment by dennwc** [comment]
We were contacted at some point by Debian/Ubuntu maintainers to create the package and add it to the registry, but Cayley was not ready at that point.

Recently I added a config for [goreleaser](https://goreleaser.com/) which can generate a `.deb`, `.rpm` and a few other kinds of packages automatically.

And yes, having a page dedicated to installation options is definitely a must.

**Comment by iddan** [comment]
Solved in 4bb9a3cd91e3129f618100da20b2385a8e3be98a
