### ISSUE TITLE
Docs hosting

### ISSUE THREAD

**Issue by dennwc** [cayleygraph/cayley#841]
We should consider hosting our docs somewhere else. Github was a nice support for Markdown, but hosts like https://readthedocs.org/ allow more customization, can provide search, as well as show multiple versions of APIs. Versions specifically already hit us in the past.

**Comment by iddan** [comment]
We can also try GitBook

**Comment by iddan** [comment]
I created a GitBook repository: https://cayley.gitbook.io/cayley/ it syncs with `/docs`

**Comment by dennwc** [comment]
Great, thanks! We can test it and see how it goes. So let's leave this open for now.

**Comment by iddan** [comment]
Documentation link in README now points to GitBook
