### ISSUE TITLE
Gizmo: Alias outPredicates and inPredicates with outE and inE

### ISSUE THREAD

**Issue by iddan** [cayleygraph/cayley#844]
**Description**
As part of #791 a low hanging fruit is aliasing `outPredicates()` and `inPredicates()` with `outE()` and `inE()` respectively to make them compliant with Gremlin.

**Comment by dennwc** [comment]
I think it may be a bit harder than that. `outPredicates()` returns a list of all predicate _values_, while `outE()` traverses to all _edges/quads_ (with a specific predicate value).

**Comment by iddan** [comment]
Hm... So they are not the same. Currently, we don't return quads in any of the methods. My bad.
