### ISSUE TITLE
Include assets with binary

### ISSUE THREAD

**Issue by iddan** [cayleygraph/cayley#845]
**Description**
Currently, static assets are included in the release of Cayley separately from the binary. It makes things a little more complex in the Dockerfile and maybe other releases. Instead, we can include the static assets as part of the binary with https://github.com/gobuffalo/packr and reduce the complexity.

**Comment by iddan** [comment]
@dennwc What do you think?

**Comment by dennwc** [comment]
Yes, I think it's a good idea. We can try including it into v0.7.6.
