### ISSUE TITLE
Gizmo: has(Path, Value)

### ISSUE THREAD

**Issue by iddan** [cayleygraph/cayley#852]
**Description**
Currently, `has()` can only get a single property to compare value to. It should also get a path.
For example: for the data:
```json
[
    { "@id": "roy",  "repository": [{ "@id": "foo", "languge": "javascript" }] },
    { "@id": "dan",  "repository": [{ "@id": "bar", "languge": "go" }] },
    { "@id": "joe",  "repository": [{ "@id": "baz", "languge": "javascript" }] }
]
```
To get all the users that have JavaScript repositories
Instead of doing:
```javascript
g.V().tag("user").out("<repository>").has("<language>", "javascript").back("user").all()
```
It will be possible to do:
```javascript
g.V().tag("user").has(g.M().out("<repository>").out("<language>"), "javascript").all()
```
It basically means aliasing `.has(path, value)` to `.and(path.is(value).back())`

**Comment by dennwc** [comment]
Implemented in the `path` package. We can potentially make this a part of v0.8.0.
