### ISSUE TITLE
Update Brew to 0.7.7

### ISSUE THREAD

**Issue by iddan** [cayleygraph/cayley#866]

**Comment by dennwc** [comment]
Should this be moved to the UI repo now?

**Comment by iddan** [comment]
Nope. Publishing the Cayley package should be discussed here. We published for Linux but didn’t for Mac

**Comment by iddan** [comment]
https://github.com/Homebrew/homebrew-core/pull/49841

**Comment by iddan** [comment]
Second attempt: https://github.com/Homebrew/homebrew-core/pull/53729
