### ISSUE TITLE
assets flag deprecation error after 0.7.6 upgrade

### ISSUE THREAD

**Issue by chenrui333** [cayleygraph/cayley#868]
**Description**

Trying to do the brew upgrade to 0.7.6 (PR, https://github.com/Homebrew/homebrew-core/pull/45317).

But found assets flag deprecation error after the installation. Might need some help on finding out why.

I have removed the `assets` references in the test step. 

**Steps to reproduce the issue:**
Jenkins log would be helpful on this part:
https://jenkins.brew.sh/job/Homebrew%20Core%20Pull%20Requests/49829/version=mojave/console

**Received results:**

The version console log is as below:
```
$ /usr/local/Cellar/cayley/0.7.6/bin/cayley version
ERROR: logging before flag.Parse: E1014 12:27:54.075636   14500 cayley.go:142] The assets flag is deprecated as assets are provided as part of the binary.
Cayley version: 0.7.6
Git commit hash: 9c843ed
```

**Expected results:**

Expecting clean output.

**Output of `cayley version` or commit hash:**

As above.

**Environment details:**

Backend database: `(database and version)`

**Comment by iddan** [comment]
Hey, thank you for reporting! I found the bug that caused that and am releasing a new version that fixes it.

**Comment by iddan** [comment]
[Version 0.7.7](https://github.com/cayleygraph/cayley/releases/tag/v0.7.7) was released with a fix to this bug.

**Comment by chenrui333** [comment]
That sounds great, thanks!!
