### ISSUE TITLE
LinkedQL (Gizmo Serialization)

### ISSUE THREAD

**Issue by iddan** [cayleygraph/cayley#877]
**Description**
By now we only have Gizmo which is based on a JavaScript runtime. LinkedQL will be the next generation querying language using an AST instead of a query string and JSON-LD as the communication format. The AST should be easily created by different clients which will expose interfaces native to their environment.

**Comment by iddan** [comment]
### Format
In Gizmo we created Paths with JavaScript chaining methods:
```javascript
g.V().all()
```
The same operation will be represented in LinkedQL like:
```json
{
    "@type": "linkedql:All",
    "parent": {
        "@type": "linkedql:NewVertex",
    }
}
```

**Comment by iddan** [comment]
### Namespaces
Namespaces not registered in Cayley before query execution should be resolved by the client.

**Comment by iddan** [comment]
### Motivation
 - Stating up the GoJa VM takes time and can't be easily optimized
 - Implementation of non-tag-array results is hard in Gizmo
 - Creating a JavaScript string from client libraries is hard and slow

**Comment by Joshfindit** [comment]
As a critic of some fundamental parts of GraphQL, I’m curious: where does LinkedQL fit in to the overall workflow?

**Comment by iddan** [comment]
LinkedQL is a [query language](https://en.wikipedia.org/wiki/Query_language) for [Linked Data](https://www.w3.org/standards/semanticweb/data) heavily inspired by [Gremlin](http://tinkerpop.apache.org/gremlin.html) and our current QL, Gizmo.
The format of LinkedQL is a [JSON-LD](https://json-ld.org) document representing a tree of steps. GraphQL format is text in a C-like syntax.
Both languages operate on entities and their links. LinkedQL is a [hybrid language](https://en.wikipedia.org/wiki/Declarative_programming#Hybrid_languages) as it allows you to define how the graph of entities should be traversed and outputted, GraphQL is fully declarative as it only allows you to define the output format of the data.
Initially, we will publish official clients for Go, JavaScript, and Python. Similarly to the various client libraries for GraphQL. Unlike GraphQL we currently don't plan to publish a server-side framework.
LinkedQL output is JSON-LD, unlike GrahpQL which outputs JSON (not standardly linked) data.

**Comment by iddan** [comment]
### Example
JavaScript client:
```JavaScript
g
.V()
.tag("entity")
.save(g.IRI("schema:givenName"))
.tagArray();
```

LinkedQL AST Representation:
```json
{
    "@base": "http://cayley.io/linkedql#",
    "@type": "TagArray",
    "from": {
        "@type": "Save",
        "via": { "@id": "https://schema.org/givenName" },
        "from": {
            "@type": "Tag",
            "tags": ["entity"],
            "from": {
                "@type": "Vertex"
            }
        }
    }
}
```

**Comment by iddan** [comment]
### API Changes
#### Default return
By default the return value will be simple values
#### `.select()`
Instead of `.tagArray()` there will be `.select()` step which can return all tags or specific tags.

**Comment by iddan** [comment]
### API
```go
type Vertex struct {
	Values []quad.Value `json:"values"`
}

type Out struct {
	From ValueStep `json:"from"`
	Via  ValueStep `json:"via"`
	Tags []string  `json:"tags"`
}

type As struct {
	From ValueStep `json:"from"`
	Tags []string  `json:"tags"`
}

type Intersect struct {
	From        ValueStep   `json:"from"`
	Intersected []ValueStep `json:"intersected"`
}

type Is struct {
	From   ValueStep    `json:"from"`
	Values []quad.Value `json:"values"`
}

type Back struct {
	From ValueStep `json:"from"`
	Tag  string    `json:"tag"`
}

type Both struct {
	From ValueStep `json:"from"`
	Via  ValueStep `json:"via"`
	Tags []string  `json:"tags"`
}

type Count struct {
	From ValueStep `json:"from"`
}

type Except struct {
	From     ValueStep `json:"from"`
	Excepted ValueStep `json:"excepted"`
}

type Filter struct {
	From   ValueStep `json:"from"`
	Filter Operator  `json:"filter"`
}

type Follow struct {
	From     ValueStep `json:"from"`
	Followed ValueStep `json:"followed"`
}

type FollowReverse struct {
	From     ValueStep `json:"from"`
	Followed ValueStep `json:"followed"`
}

type Has struct {
	From   ValueStep    `json:"from"`
	Via    ValueStep    `json:"via"`
	Values []quad.Value `json:"values"`
}

type HasReverse struct {
	From   ValueStep    `json:"from"`
	Via    ValueStep    `json:"via"`
	Values []quad.Value `json:"values"`
}

type In struct {
	From ValueStep `json:"from"`
	Via  ValueStep `json:"via"`
	Tags []string  `json:"tags"`
}

type InPredicates struct {
	From ValueStep `json:"from"`
}

type Labels struct {
	From ValueStep `json:"from"`
}

type Limit struct {
	From  ValueStep `json:"from"`
	Limit int64     `json:"limit"`
}

type OutPredicates struct {
	From ValueStep `json:"from"`
}

type Save struct {
	From     ValueStep `json:"from"`
	Via      ValueStep `json:"via"`
	Tag      string    `json:"tag"`
	Optional bool      `json:"optional"`
}

type SaveInPredicates struct {
	From ValueStep `json:"from"`
	Tag  string    `json:"tag"`
}

type SaveOutPredicates struct {
	From ValueStep `json:"from"`
	Tag  string    `json:"tag"`
}

type SaveReverse struct {
	From     ValueStep `json:"from"`
	Via      ValueStep `json:"via"`
	Tag      string    `json:"tag"`
	Optional bool      `json:"optional"`
}

type Skip struct {
	From   ValueStep `json:"from"`
	Offset int64     `json:"offset"`
}

type Union struct {
	From      ValueStep   `json:"from"`
	Unionized []ValueStep `json:"unionized"`
}

type Unique struct {
	From ValueStep `json:"from"`
}

type Order struct {
	From ValueStep `json:"from"`
}
```

**Comment by iddan** [comment]
Optional should not be a flag, rather a step.

**Comment by iddan** [comment]
Should rename Morphism to something more clear.

**Comment by iddan** [comment]
Save should be renamed and allow saving multiple properties.

**Comment by iddan** [comment]
`.propertiesAs({ [property: string]: IRI })` should replace `.save(iri, tag)` for aliasing property name to something else.

**Comment by iddan** [comment]
Morphism name ideas:
 - Annonymous as it is called in Gremlin
 - Placeholder as it is called in Scala, Lodash, Ramda, and ReasonML

**Comment by iddan** [comment]
`.reverseProperties()` should wrap saved properties in the document with `@reverse`
