### ISSUE TITLE
How to do CRUD opeations in cayley???

### ISSUE THREAD

**Issue by vzool** [cayleygraph/cayley#891]

**Comment by iddan** [comment]
Hello @vzool and thank you for trying Cayley and taking the time to open an issue.
(C) To create data you can use the `/api/v2/write` endpoint. you can post it JSON-LD data or data in any other supported RDF format.
(R) To read data you can either use `/api/v2/query` endpoint or `/api/v2/read` endpoint for very simple data queries.
(U) To update data you'd need to first delete the update you want to update, and then create the updated data.
(D) To delete data you can use the `/api/v2/delete` endpoint. You can post it JSON-LD data or data in any other supported RDF format.
