### ISSUE TITLE
Unable to enter the container

### ISSUE THREAD

**Issue by zdYng** [cayleygraph/cayley#892]
[root@test ~]# docker run -p 64210:64210 -d cayleygraph/cayley:v0.7.5
30a8ff783ce6eb54e7c78a6366aa7ae6524c25820e3f02c53b6880be8433d514

[root@test ~]# docker ps
CONTAINER ID        IMAGE                             COMMAND                  CREATED              STATUS                                                                                                                                        PORTS                              NAMES
30a8ff783ce6        cayleygraph/cayley:v0.7.5         "cayley http --asset…"   3 seconds ago        Up 3 seconds                                                                                                                                  0.0.0.0:64210->64210/tcp           xenodochial_leavitt

[root@test ~]# docker exec -it 30a8ff783ce6 /bin/bash
OCI runtime exec failed: exec failed: container_linux.go:345: starting container process caused "exec: \"/bin/bash\                                                                                                                          ": stat /bin/bash: no such file or directory": unknown

**Comment by zdYng** [comment]
![image](https://user-images.githubusercontent.com/17880611/69405383-7f1b9600-0d3a-11ea-87c8-b56c0ae55720.png)
这是什么情况

**Comment by zdYng** [comment]
What's happening here

**Comment by dennwc** [comment]
We build a container from scratch to save size, so it doesn't contain the shell even.

Do you want to extract something specific from an image? Maybe I can help to tell where it is, so you can use `docker cp` to get it.

**Comment by zdYng** [comment]
Yes, I want to enter the container because some configuration files need to be modified externally

**Comment by iddan** [comment]
Another option is copying the Cayley binary to a different container:
```Dockerfile
FROM cayleygraph/cayley:v0.7.6 as cayley

# Any base image you want here
FROM alpine
# Copy the Cayley binary to the image
COPY --from=cayley /bin/cayley /bin/cayley
ENTRYPOINT ["cayley", "http", "--host=:64210"]
```

**Comment by iddan** [comment]
Closing for now. @zdYng if you still need help feel free to reopen the issue.

**Comment by lagc03** [comment]
I tried this method and the web interface does not work, im sure its ported correctly to the host. Anything I could be missing?
