### ISSUE TITLE
cayley.io is down

### ISSUE THREAD

**Issue by aomarks** [cayleygraph/cayley#947]
Seems like the cayley.io website is down. I get a timeout. Tried a few times today.

**Comment by trivigy** [comment]
@iddan any guidance appreciated.

**Comment by iddan** [comment]
Hey, I haven't changed it for a long time. @barakmich do you know what's up with that?

**Comment by ackbyte** [comment]
Same here. The Webserver system (147.75.97.124) behind cayley.io seems to be down :neutral_face:

**Comment by akuckartz** [comment]
9 days...

**Comment by trivigy** [comment]
@barakmich would you object if I will move the site to a github pages based hosting? This way it will not rely on custom namespace routing. At least this one I should be able to quickly fix this and https://github.com/cayleygraph/cayley/issues/949.

**Comment by dennwc** [comment]
I agree that we should switch to Github Pages to avoid relying on a dedicated server.

**Comment by barakmich** [comment]
Back now -- not at all opposed to Github Pages or similar, but I had to unwedge the old server on Packet
