### ISSUE TITLE
Cayley.io is down again

### ISSUE THREAD

**Issue by theikkila** [cayleygraph/cayley#961]
Related to #947 site seems to be down again.

**Comment by mt35-rs** [comment]
Still down, FYI.

**Comment by mkalus** [comment]
Such a shame, this really is cool project worth continuing.

**Comment by amery** [comment]
there are plenty contributor who could take it over if the main developer had to move on. even if it mean giving up the name

**Comment by dennwc** [comment]
I'm open to adding someone to the project to keep the development. See #963 .

**Comment by amery** [comment]
> I'm open to adding someone to the project to keep the development. See #963 .

hi @dennwc, I'm not a contributor (yet) but I pushed the site to cloudflare pages in case you want to set a CNAME and bring cayley.io back up
https://cayleygraph-website.pages.dev/

it comes from https://github.com/amery/cayleygraph-website/tree/built, for some reason their `hugo` integration didn't work out of the box, will try to fix that so it comes directly out of _master_

**Comment by eraserhd** [comment]
https://cayleygraph.github.io/ works now.  The website repo was renamed to [cayleygraph/cayleygraph.github.io](https://github.com/cayleygraph/cayleygraph.github.io) to make this work.

The `cayley.io` domain will not work until we can get a CNAME.   Perhaps @barakmich, says Dennis.

**Comment by eraserhd** [comment]
We're live again!
